// 3.7.1: las voces del amor en la aldea. Todo lo que dicen las vecinas solteras cuando les tirás un piropo,
// las invitás a salir, te declarás, les proponés casamiento o les hablás de los chicos, y lo que comentan los
// vecinos (con humor) cuando se enteran. Las reglas están en amor.js; acá sólo hay texto.
//
// Tierno y con humor, para todo público: nada explícito (el «ñiki ñiki» es un fundido: no se muestra ni se
// describe nada). Sin nada religioso (el casamiento es civil, con el juez de paz) y sin economía (nadie cobra
// ni vende: el anillo lo hace Anselmo con un canto rodado, y las cartas las lleva el tren).
//
// Marcas que reemplaza amor.js: {nombre} (tu apodo, o como te dice cada una), {ella} (el nombre de ella),
// {lugar} (un lugar del valle o de la aldea, con artículo), {hijo} (el nombre de un hijo), {dias}, {quien},
// {otra}, {dia}, {cita}.
//
// Módulo puro: sólo datos.

// ---------------------------------------------------------------- cada una
// piropo: lo que contesta cuando le tirás un piropo (gusto: le gustó; rie: se ríe y cambia de tema; no: no
// es el día). cita: si acepta salir, si no puede, y lo que charlan en la cita (dos renglones). favorito: lo que
// dice de su lugar preferido (ahí conviene declararse y proponer). declaracion y propuesta: sí o no. boda: lo
// que dice ante el juez de paz. celos: cuando se entera de que salís con otra. carta: cuando le llega tu carta
// por el correo. flores: cuando le das un ramo. chicos: cuando le hablás de tener un hijo.
export const VOCES_AMOR = {
  veterinaria: {
    piropo: {
      gusto: ['¿Eso fue un piropo? Mirá que yo estoy acostumbrada a que me hablen los caballos, no los vecinos. Me gustó, eh.', 'Ay, callate. Bueno, no te calles. Decilo de nuevo.'],
      rie: ['Ja, ¿te lo enseñó Don Ramón? Tiene el mismo olor a mate cocido.'],
      no: ['Hoy no, que me pateó una mula y estoy de pocas pulgas.'],
    },
    cita: { si: 'Dale. Pero si en el camino hay un perro rengo, primero lo atiendo y después somos novios… digo, salimos. Salimos.', no: 'Hoy no puedo: tengo una oveja con fiebre esperándome. Otro día, en serio.',
      charla: ['¿Sabías que los caballos duermen parados? Yo a veces también, cuando hay guardia.', 'Me gusta que no me apurás. Los animales se dan cuenta de quién es buena gente, y yo también.'] },
    favorito: 'El mallín al atardecer, cuando los caballos bajan a tomar agua. Es lo más lindo que conozco, y conozco muchos caballos.',
    declaracion: { si: ['¿Novios? Sí. Sí, sí. Perdón, me salió como cuando sale bien un parto: de golpe y con ganas.'], no: 'Me caés muy bien, pero todavía no. Dame un tiempo, que yo voy despacio, como con los potrillos.' },
    propuesta: { si: ['¿Con un anillo de Anselmo? ¡Sí! Y que los perros de la aldea vengan al casamiento, que son mis pacientes favoritos.'], no: 'Es muy pronto. No me lo tomes a mal: quiero estar segura, como cuando receto.' },
    boda: 'Prometo cuidarte como a mis animales: con paciencia, con mate y sin hacerte esperar en la sala.',
    celos: 'Me contaron que andás saliendo con otra. No me hables por unos días, que estoy con la sangre caliente.',
    carta: 'Me llegó tu carta. La leí en el corral y las gallinas se me quedaron mirando como diciendo «¿y esa cara?».',
    flores: '¿Flores para mí? Las voy a poner en el frasco del jarabe para la tos. Bueno, lo lavo antes.',
    chicos: 'Un hijo… Me imagino una casa con barro en la puerta y un perro en cada silla. Me encanta la idea.',
  },
  fotografa: {
    piropo: {
      gusto: ['Esa frase merecía una foto. No te muevas… no, ya pasó. Igual me la guardo.', 'Me pusiste colorada. Con esta luz se nota, ¿no? Qué vergüenza.'],
      rie: ['Muy lindo, pero tenés el sol de frente: salió todo quemado.'],
      no: ['Hoy estoy de mal humor: se me veló un rollo entero. Otro día.'],
    },
    cita: { si: 'Sí. Llevo la cámara, pero prometo no sacarte más de veinte fotos.', no: 'Hoy no: tengo que revelar. Si me distraigo, salen todos verdes. Otro día.',
      charla: ['Mi abuelo decía que la foto buena es la que sacás cuando bajás la cámara. Ahora entiendo.', 'Mirá esa nube: parece un perro con sombrero. No, no la voy a fotografiar. Quiero mirarla con vos.'] },
    favorito: 'El mirador a las cinco de la tarde. La luz entra de costado y el valle parece pintado a mano.',
    declaracion: { si: ['Sí. Esto lo tendría que haber fotografiado: tu cara cuando te dije que sí.'], no: 'Todavía no. Sos lindo de mirar, pero yo tardo en revelar lo que siento.' },
    propuesta: { si: ['¡Sí! ¡Sí! ¿Quién nos saca la foto del casamiento? No importa: me la saco yo con el disparador.'], no: 'Me encanta el anillo, pero dame un poco más. Quiero que sea para siempre, como las fotos de mi abuelo.' },
    boda: 'Prometo mirarte con los mismos ojos de hoy, aunque se te ponga el pelo blanco. Y prometo no ponerte en fila para la foto.',
    celos: 'Me dijeron que andás con otra. La foto ya la vi, no hace falta que me la expliques. Dejame unos días.',
    carta: 'Llegó tu carta. La puse en el cuarto oscuro, colgada con los broches. Es lo único que no voy a revelar nunca.',
    flores: 'Flores… las voy a fotografiar antes de que se marchiten. Y después también.',
    chicos: 'Un hijo. Ya me imagino el álbum: el primer diente, la primera nevada, la primera vez que se come una frutilla con tierra.',
  },
  andinista: {
    piropo: {
      gusto: ['¿Me estás tirando onda? Ja. Mirá que soy de escalar rápido, eh.', 'Uy. Eso me dejó más agitada que la subida al Tronador.'],
      rie: ['Lindo. Ahora repetilo con cuarenta kilos en la espalda y a tres mil metros.'],
      no: ['Hoy no estoy para piropos: me torcí el tobillo bajando del filo.'],
    },
    cita: { si: '¡Vamos! Llevá abrigo, agua y avisá a dónde vas. Ah, no, vas conmigo. Igual llevá abrigo.', no: 'Hoy no puedo: tengo que revisar las cuerdas. Otro día subimos a donde quieras.',
      charla: ['¿Viste que desde arriba los problemas se ven chiquitos? Eso es lo que más me gusta de subir.', 'Con vos camino más despacio. No sé si es porque te espero o porque no quiero llegar.'] },
    favorito: 'La torre. Desde ahí arriba se ve todo el valle de una, como desde una cumbre, pero sin congelarse.',
    declaracion: { si: ['Sí. Siento lo mismo que en una cumbre: ganas de gritar y miedo de mirar para abajo. Sí.'], no: 'Todavía no. Me gusta ir de a poco, haciendo base. No te apures.' },
    propuesta: { si: ['¡Sí! Y la luna de miel, en un refugio de montaña. Con estufa. Y sin sombreros volando.'], no: 'Me encanta, pero dejame aclimatarme. A mucha altura de golpe, uno se marea.' },
    boda: 'Prometo atarme a vos con la cuerda roja y no soltarte nunca, ni en la bajada.',
    celos: 'Me enteré de que salís con otra. Me dejaste colgada del arnés. No me hables por unos días.',
    carta: 'Me llegó tu carta. La leí en el refugio, tres veces. A la tercera ya me la sabía de memoria, como los mapas.',
    flores: '¡Flores! Las de abajo son más grandes que las de la montaña. Pero estas son las más lindas.',
    chicos: 'Un hijo… Lo voy a llevar a la montaña atado con una cuerda, como mi tío a mí. Bueno, primero que aprenda a caminar.',
  },
  herbolaria: {
    piropo: {
      gusto: ['Mirá vos. Eso no se arregla con ningún yuyo. Y no quiero que se cure.', 'Me lo guardo, como a las hojas de canelo: entre las páginas de un libro.'],
      rie: ['Muy dulce. Para eso tengo un té de matico, que baja el azúcar.'],
      no: ['Hoy no tengo la cabeza para eso. El monte estuvo raro, y yo también.'],
    },
    cita: { si: 'Sí. Pero antes de ir, le pedimos permiso al lugar. Siempre.', no: 'Hoy no puedo: estoy secando yuyos y si los dejo, se humedecen. Otro día, de verdad.',
      charla: ['¿Sentís el olor? Es el poleo. Mi abuela decía que donde crece el poleo, la gente se queda.', 'Contigo me pasa lo que con el monte: no hace falta hablar mucho para estar bien.'] },
    favorito: 'Los arrayanes. Tienen la corteza fría y color canela, y el silencio ahí adentro es como un abrazo.',
    declaracion: { si: ['Sí. Le pedí permiso al monte antes de que vinieras, ¿sabés? Y me dijo que sí.'], no: 'Todavía no. Las cosas buenas crecen despacio. Tenele paciencia a esta planta.' },
    propuesta: { si: ['Sí. Mi abuela diría que es un buen lawen, este. Un remedio para toda la vida.'], no: 'Todavía no. No es que no quiera: es que quiero que el tiempo sea el justo, como la cosecha.' },
    boda: 'Prometo pedirte permiso, cuidarte cuando te duela algo y dejarte siempre un poco de lo mejor.',
    celos: 'Me contaron que salís con otra. Al monte no se le saca de más, y a la gente tampoco. Dejame sola unos días.',
    carta: 'Me llegó tu carta. La guardé entre las hojas de canelo: así se queda con el perfume.',
    flores: 'Gracias. ¿Las cortaste con permiso? Seguro que sí. Las pongo en agua y les hablo un poco.',
    chicos: 'Un hijo… Le voy a enseñar a saludar a cada árbol antes de sacarle una hoja. Como a mí.',
  },
  pintora: {
    piropo: {
      gusto: ['Ay. Eso tiene un color que no existe en ningún tubo. Gracias.', 'Me quedé sin palabras. Y sin pintura, pero eso es otra cosa.'],
      rie: ['Qué lindo. ¿Me lo repetís despacio, que lo quiero pintar?'],
      no: ['Hoy no: arruiné un cuadro entero y estoy enojada con el mundo. Con vos no, con el mundo.'],
    },
    cita: { si: '¡Sí! Llevo la libreta de bocetos, por las dudas. Por las dudas de que estés lindo.', no: 'Hoy no puedo: la pintura está fresca y si la dejo, se me corre todo. Otro día.',
      charla: ['¿Ves que las sombras nunca son negras? Son violetas, azules… Desde que te conozco las veo más claras.', 'Me gustaría pintarte. No ahora, eh. Cuando te olvides de que te estoy mirando.'] },
    favorito: 'El alero de las pinturas. Alguien pintó esas manos hace miles de años. Ahí siento que pintar es lo más viejo del mundo.',
    declaracion: { si: ['Sí. Sí. Este cuadro lo estaba pintando hace tiempo y no me animaba a firmarlo.'], no: 'Todavía no. Me gusta este boceto, pero le falta. Esperá un poco.' },
    propuesta: { si: ['¡Sí! Y voy a pintar el cartel del casamiento yo, con letras que se vean desde la estación.'], no: 'Todavía no. Es que tengo miedo de arruinarlo, como cuando un cuadro está casi listo.' },
    boda: 'Prometo pintarte todos los días, aunque sea en la cabeza, y no pedirte nunca que te quedes quieto.',
    celos: 'Me dijeron que salís con otra. Ese color no me gusta nada. Dejame unos días con mis pinceles.',
    carta: 'Llegó tu carta. Le hice un dibujito en el margen. No te la devuelvo, eh: es mía.',
    flores: '¡Flores! Ya sé qué voy a pintar mañana. Y pasado. Y toda la semana.',
    chicos: 'Un hijo… Lo dejo pintar todas las paredes, como mi mamá a mí. Bueno, las de adentro no.',
  },
  ceramista: {
    piropo: {
      gusto: ['¡Ay! Me hiciste reír con las manos llenas de barro. Ahora tengo barro en la cara. Valió la pena.', 'Mirá que soy prima de Mario: si me rompés el corazón, te hace leña.'],
      rie: ['Qué lindo. Lástima que lo dijiste mientras se me desarmaba un jarro.'],
      no: ['Hoy no: se me rajó toda la hornada. Estoy de mal humor.'],
    },
    cita: { si: '¡Dale! Me lavo las manos y voy. Bueno, me lavo un poco.', no: 'Hoy no puedo: el horno está prendido y no lo puedo dejar solo. Otro día.',
      charla: ['El barro tiene memoria, ¿sabías? Si lo tratás con cariño antes del horno, después no se raja.', 'Con vos me pasa algo raro: no me dan ganas de hablar de cerámica. Bueno, un poco sí.'] },
    favorito: 'El puente del arroyo. Ahí abajo está el barro colorado, el mejor de la cordillera. Y el agua suena lindo.',
    declaracion: { si: ['¡Sí! Esperá que se lo cuento a Mario. No, mejor no, que se pone pesado. Sí, sí.'], no: 'Todavía no. Todo lo que se apura en el horno se raja. Esperemos un poco.' },
    propuesta: { si: ['¡Sí! ¡Sí! Y les hago a todos los invitados un jarro con su nombre. Bueno, a los que me caen bien.'], no: 'Ay, es muy pronto. Dejame que se seque un poco esto, antes de meterlo al horno.' },
    boda: 'Prometo cuidarte como al barro bueno: con agua, con paciencia y sin apuro.',
    celos: 'Me contaron que salís con otra. Mario ya está afilando el hacha. Mentira. Pero no me hables por unos días.',
    carta: 'Me llegó tu carta. Le dejé una huella de barro sin querer. Ahora es una carta firmada por los dos.',
    flores: '¡Flores! Ya sé: les hago un florero. Mañana sale del horno.',
    chicos: 'Un hijo… Con las manos chiquitas en el barro, haciendo un cenicero torcido para regalarte. Me muero.',
  },
  botera: {
    piropo: {
      gusto: ['Mirá vos, el del kayak sabe decir cosas lindas. Me dejaste sin viento en la vela.', 'Uy. Eso me gustó más que el olor a brea, y eso es mucho decir.'],
      rie: ['Lindo. Ahora decímelo remando contra el viento.'],
      no: ['Hoy no. Se me partió un tablón y estoy con la cabeza en otra cosa.'],
    },
    cita: { si: 'Bueno, vamos. Pero si hay viento, el que rema sos vos.', no: 'Hoy no puedo: tengo un bote dado vuelta esperándome. Otro día salimos.',
      charla: ['Mi viejo decía que el agua no se domina: se acompaña. Con la gente pasa lo mismo.', 'No soy de hablar mucho. Pero con vos el silencio no pesa. Eso es raro.'] },
    favorito: 'El muelle, cuando el lago está quieto y se ve la cordillera dada vuelta en el agua.',
    declaracion: { si: ['Sí. Ya está, lo dije. Ahora no me mires así, que me pongo colorada como la brea caliente.'], no: 'Todavía no. Yo navego con cuidado. Dame un poco más de agua.' },
    propuesta: { si: ['Sí. Y el anillo lo voy a cuidar más que al remo de mi viejo. Y eso ya es decir.'], no: 'Todavía no. No quiero salir al agua sin revisar el casco. Esperá un poco.' },
    boda: 'Prometo remar para el mismo lado que vos, aunque haya viento en contra.',
    celos: 'Me enteré de que salís con otra. No me gusta navegar en aguas turbias. Dejame unos días.',
    carta: 'Me llegó tu carta. La leí en el muelle. Nicanor me preguntó por qué me reía sola. No le dije nada.',
    flores: 'Flores… nadie me regala flores a mí. Me regalan brea. Gracias, en serio.',
    chicos: 'Un hijo… Le voy a enseñar a calafatear antes que a caminar. No, mentira. Un poco después.',
  },
  astronoma: {
    piropo: {
      gusto: ['Eso fue más lindo que una lluvia de estrellas. Y yo vi muchas.', 'Ay. Me hiciste olvidar en qué constelación estaba.'],
      rie: ['Muy lindo. Pero la Cruz del Sur no señala al sur exacto, así que no te creo del todo.'],
      no: ['Hoy no estoy para eso: dormí tres horas y estuvo nublado toda la noche.'],
    },
    cita: { si: 'Sí. Pero si se despeja el cielo, te hablo de estrellas toda la noche. Estás avisado.', no: 'Hoy no puedo: hay que calibrar el telescopio. Otro día, prometido.',
      charla: ['¿Ves aquella? La luz que te llega salió hace siglos. Y llegó justo esta noche, para nosotros.', 'Antes miraba para arriba para no pensar. Ahora miro para arriba y pienso en vos. Es un problema.'] },
    favorito: 'El observatorio de noche, con la cúpula abierta. Es el único lugar donde el cielo entra por el techo.',
    declaracion: { si: ['Sí. Esto lo calculé mil veces y siempre me daba lo mismo: sí.'], no: 'Todavía no. Hay cosas que tardan en llegar, como la luz. Esperá un poco.' },
    propuesta: { si: ['Sí. Mi papá estaría feliz. Él decía que la luz llega tarde, pero llega. Vos llegaste.'], no: 'Todavía no. Quiero que la órbita sea estable. Dame un poco más.' },
    boda: 'Prometo mirarte como miro el cielo: todas las noches, con paciencia y sin cansarme nunca.',
    celos: 'Me contaron que salís con otra. Eso es un eclipse, y de los largos. No me hables por unos días.',
    carta: 'Me llegó tu carta. La leí con la linterna roja, a medianoche. Las estrellas se pusieron celosas.',
    flores: 'Flores de día, para la que vive de noche. Las voy a mirar cuando me despierte. Gracias.',
    chicos: 'Un hijo… La primera noche que vea las Nubes de Magallanes le voy a contar que son dos galaxias. Y se va a dormir. Bueno.',
  },
  guardaparque: {
    piropo: {
      gusto: ['Eso no lo anoto en el registro. Me lo guardo yo.', 'Mirá vos. Primera vez que alguien me deja sin palabras en el monte.'],
      rie: ['Lindo. Pero en el parque no se le tiran piropos a la guardaparque, eh. Te dejo pasar por esta vez.'],
      no: ['Hoy no. Estoy cansada y tengo tres planillas atrasadas.'],
    },
    cita: { si: 'Dale. Pero vamos por el sendero, que se respeta.', no: 'Hoy no puedo: tengo recorrida. Otro día, sin falta.',
      charla: ['Mi abuelo me enseñó a leer huellas. Las tuyas las reconozco desde lejos: pisás despacio, como el que respeta.', 'Me gusta estar con vos porque no hace falta hacer ruido.'] },
    favorito: 'El faro, a la tardecita. Desde ahí se ve el lago entero y se cuentan los cisnes sin molestarlos.',
    declaracion: { si: ['Sí. Te venía siguiendo el rastro hace rato, ¿sabés? No me daba cuenta.'], no: 'Todavía no. Yo soy como el huemul: me acerco de a poco. Esperá.' },
    propuesta: { si: ['Sí. Josefina se va a reír de mí un año entero. No me importa: sí.'], no: 'Todavía no. Dejame que lo piense en la recorrida. Pienso mejor caminando.' },
    boda: 'Prometo cuidarte como cuido el bosque: todos los días, sin que se note, y para siempre.',
    celos: 'Me dijeron que salís con otra. Esas huellas no me gustan. Dejame unos días.',
    carta: 'Me llegó tu carta. La guardé en el cuaderno de campo, entre el pudú y el huemul. Es el avistaje más lindo.',
    flores: 'Flores… ¿de dónde las sacaste? Ah, de un claro, bien. Del parque no se saca nada. Gracias.',
    chicos: 'Un hijo… Lo llevo a la seccional y le enseño las huellas antes que las letras. Bueno, las dos.',
  },
  enfermera: {
    piropo: {
      gusto: ['Mirá vos. Me subiste la presión, y eso que la tengo siempre bien.', 'Qué lindo. Hace mucho que nadie me decía algo así.'],
      rie: ['Muy amable. Igual abrigate, que el frío entra por los pies.'],
      no: ['Hoy no, querido. Tuve un día largo en el puesto.'],
    },
    cita: { si: 'Sí, con gusto. Pero si alguien se tuerce un tobillo en el camino, lo atiendo primero.', no: 'Hoy no puedo: tengo guardia en el puesto. Otro día.',
      charla: ['En el hospital aprendí que lo más importante es escuchar. Con vos es fácil: decís cosas lindas.', 'Me gusta que me preguntes cómo estoy. Yo siempre pregunto, y a mí casi nadie me pregunta.'] },
    favorito: 'La plaza, a la tardecita, cuando se prenden los faroles y los chicos se van a cenar.',
    declaracion: { si: ['Sí. A mi edad una ya no se hace la difícil. Sí, con todo el corazón.'], no: 'Todavía no. Me cuido mucho, ¿sabés? Dame un poco más de tiempo.' },
    propuesta: { si: ['Sí. Mi bisabuelo cruzó el mar para llegar al Chubut. Yo sólo tengo que cruzar la plaza. Sí.'], no: 'Todavía no. No es un no: es un todavía. Sé paciente conmigo.' },
    boda: 'Prometo cuidarte antes de que te enfermes, escucharte siempre y abrigarte los pies.',
    celos: 'Me contaron que salís con otra. Eso duele más que un esguince. Dejame unos días.',
    carta: 'Me llegó tu carta. La leí en la camilla del puesto, con la puerta cerrada. Me hizo bien.',
    flores: 'Flores para la enfermera. Las pongo en el puesto: a los pacientes les hace bien verlas. A mí también.',
    chicos: 'Un hijo… Ayudé a nacer a tantos que nunca pensé que me iba a tocar. Me encanta la idea.',
  },
  galesa: {
    piropo: {
      gusto: ['Oh! Diolch… gracias, quiero decir. Me hiciste poner colorada como la tetera.', 'Qué lindo. En galés eso tiene una palabra que no tiene traducción. Ahora la tiene.'],
      rie: ['Muy dulce. ¿Querés otra porción de torta negra? Así te endulzo yo a vos.'],
      no: ['Hoy no, cariad. Se me quemó la torta y estoy de malas.'],
    },
    cita: { si: 'Sí. Llevo una canasta con torta negra y la tetera chica.', no: 'Hoy no puedo: la galería se llena a la tarde. Otro día, con gusto.',
      charla: ['Mi nain decía que el té tiene que reposar para que salga bueno. Lo nuestro también, ¿no?', 'Me gusta que vengas a la galería aunque no tengas sed.'] },
    favorito: 'La galería de la casa de té, a la hora de cerrar, cuando queda la estufa prendida y ya no hay nadie.',
    declaracion: { si: ['Sí. Mi tatarabuela cruzó el mar en el Mimosa para que yo dijera que sí en este valle. Sí.'], no: 'Todavía no, cariad. El té no se apura. Esperá un poco.' },
    propuesta: { si: ['Sí. Y en la fiesta va a haber torta negra para todos. Y té. Mucho té.'], no: 'Todavía no. Quiero estar segura, como cuando pruebo la torta antes de servirla.' },
    boda: 'Prometo una taza de té caliente cada vez que llegues mojado, y una silla al lado de la estufa para siempre.',
    celos: 'Me contaron que salís con otra. Ese té está frío. No me hables por unos días.',
    carta: 'Me llegó tu carta. La guardé en la lata de la torta negra. Es el lugar más seguro de la casa.',
    flores: '¡Flores! Las pongo en la mesa del medio de la galería, para que todos pregunten de quién son.',
    chicos: 'Un hijo… Le voy a enseñar galés en la mesa y castellano en la calle, como a mí. Y a hacer torta negra.',
  },
  nelida: {
    piropo: {
      gusto: ['¡Ay! ¿Eso me lo dijiste a mí? Ercilia, ¿escuchaste? Ah, no está. Mejor.', 'Me hiciste perder la cuenta de los kilos de yerba. Ahora tengo que contar todo de nuevo. Valió la pena.'],
      rie: ['Muy lindo. Lo anoto en el cuaderno del almacén, entre la harina y los fósforos.'],
      no: ['Hoy no: Ercilia me retó por el vuelto y estoy con la cara larga.'],
    },
    cita: { si: '¡Sí! Le aviso a Ercilia que salgo. Bueno, no le aviso nada, que se pone a preguntar.', no: 'Hoy no puedo: hay que reponer todo el estante de los fideos. Otro día.',
      charla: ['¿Sabés que anoto todo lo que pasa en el pueblo? Hoy voy a anotar esto. Con letra linda.', 'Mi mamá me decía que sabía sumar. Lo que no sabía era esto.'] },
    favorito: 'El andén de la estación, cuando llega el tren de la tarde. Yo llegué así, en el tren, con una valija y un cuaderno.',
    declaracion: { si: ['¡Sí! ¡Sí! Esperá que respiro. Sí. Ya está. ¡Sí!'], no: 'Todavía no. No te enojes. Es que me pongo nerviosa y me tiembla todo.' },
    propuesta: { si: ['¡Sí! ¡Mamá se va a desmayar! Y Ercilia también. Sí, sí, sí.'], no: 'Todavía no. Soy joven y me asusto. Dame un poco más.' },
    boda: 'Prometo anotar cada día lindo que pasemos en el cuaderno, y no dejar de sumar nunca.',
    celos: 'Me contaron que salís con otra. Yo me entero de todo, ¿sabés? Trabajo en el almacén. Dejame unos días.',
    carta: 'Me llegó tu carta. La escondí abajo del mostrador. Ercilia preguntó qué era. Le dije que una lista de pedidos.',
    flores: '¡Flores! Las pongo en el mostrador. Todos van a preguntar. Que pregunten.',
    chicos: 'Un hijo… Le voy a enseñar a sumar con los porotos del almacén, como me enseñó mi mamá.',
  },
};

// ---------------------------------------------------------------- las frases de todos
export const FRASES_AMOR = {
  // el menú de la charla (vecindad-juego.js)
  titulo: { coquetear: 'Coquetear…', nuestro: 'Lo nuestro…', reconquistar: 'Lo nuestro…' },
  sub: { amor: '¿Qué le decís?', cita: '¿A dónde la invitás?', casa: '¿Dónde viven?', correo: '¿A quién le escribís?', anillo: '¿Qué le pedís?' },
  opcion: {
    piropo: 'Tirarle un piropo', mimo: 'Decirle algo lindo', cita: 'Invitarla a salir…', flores: 'Regalarle un ramo de flores', declararse: '¿Querés ser mi novia?',
    proponer: 'Proponerle casamiento (con el anillo)', convivir: 'Proponerle vivir juntos…', casa: '¿Dónde vivimos?…', chicos: 'Hablar de los chicos', buscar: '¿Y si buscamos un hijo?',
    niki: 'Ñiki ñiki…', reconquistar: 'Pedirle volver', refugio: 'En mi refugio', suya: 'En tu casa', volver: 'Mejor no',
    carta: 'Mandarle una carta de amor a {ella}', ramo: 'Mandarle un ramo de flores a {ella}', anillo: 'Encargarle un anillo (con un canto rodado)', retirar: 'Retirar el anillo',
  },
  // lo que dice ella o lo que pasa
  yaHoyPiropo: '¡Ya me dijiste algo lindo hoy! No gastes todo de una vez.',
  enojada: ['No tengo ganas de hablar de eso. Todavía estoy enojada.', 'Dejame, que todavía me dura el enojo.'],
  noPuedeCita: 'Ya tenemos una cita pendiente. Primero esa, ¿no?',
  sinHueco: 'Hoy y mañana no tengo un rato libre para eso. Otro día, ¿dale?',
  citaAcordada: 'Quedamos: {cita}, el {dia} a las {hora}. No llegues tarde.',
  citaHoy: 'Quedamos: {cita}, hoy a las {hora}. No llegues tarde.',
  citaManiana: 'Quedamos: {cita}, mañana a las {hora}. No llegues tarde.',
  citaEmpieza: ['¡Viniste! Ya pensaba que me ibas a dejar plantada.', '¡Hola! Llegaste justo.'],
  citaFin: ['Qué lindo rato. Gracias por invitarme.', 'Me la pasé muy bien. Hay que repetirlo.'],
  plantada: 'Te esperé un buen rato… Otra vez avisá, ¿sí?',
  sinFlores: 'En invierno no hay flores en el monte. Mandale una carta, que también llega.',
  yaFlores: '¡Si ya me regalaste flores hoy! Vas a tener que hacerme un florero.',
  noTodavia: 'Esto recién empieza. Salgamos un poco más antes de hablar de eso, ¿sí?',
  sinAnillo: 'Para eso te falta el anillo. Anselmo los hace con un canto rodado del arroyo.',
  convivirSi: 'Sí. Dale. Vivamos juntos.',
  convivirNo: 'Todavía no. Me gusta mi casa. Dame un poco más.',
  casaElegida: { refugio: 'Al refugio, entonces. Llevo mis cosas de a poco: una caja por día.', suya: 'Acá, entonces. Te hago lugar en el ropero. Un poquito, eh.' },
  chicosHoy: 'Hoy ya hablamos de eso. Mañana seguimos, que me da cosa.',
  buscarSi: 'Sí. Busquemos un hijo. Si viene, que venga con salud.',
  buscarNo: 'Todavía no. Primero casémonos, y después vemos.',
  buscarYa: 'Ya lo estamos buscando. Las cosas llegan cuando llegan.',
  maximoHijos: 'Con dos ya tenemos la casa llena. ¡Y el corazón también!',
  embarazo: '{ella} te dice al oído que va a tener un bebé. Faltan unos {dias} días.',
  esperando: 'Ya falta poco: unos {dias} días. A la noche se mueve como un pez.',
  nikiAntes: ['Los chicos ya duermen… ¿Apagamos la luz?', '¿Nos vamos a dormir? Bueno, a dormir dormir no…'],
  nikiSinChicos: ['¿Apagamos la luz?', '¿Nos vamos a dormir? Bueno, a dormir dormir no…'],
  nikiNo: { dia: 'Shh, ¿de día? Esperá que sea de noche.', chicos: 'Los chicos todavía andan despiertos. Más tarde.', casa: 'Acá no. En casa.', hoy: 'Hoy ya, ¿eh? Ahora a dormir de verdad.', enojada: 'Hoy no. Todavía estoy enojada con vos.' },
  nikiDespues: 'Un rato de mimos. Descansás de verdad y amanecés de buen ánimo.',
  reconquistaSi: 'Bueno… sí. Volvamos a intentarlo. Pero esta vez no me descuides.',
  reconquistaNo: 'Todavía no. Me lastimaste. Seguí viniendo, que a lo mejor…',
  reconquistaTodavia: 'Primero salgamos de nuevo, como al principio. Después vemos.',
  separacion: '{ella} se cansó de esperarte y se volvió a su casa con los chicos. «Si querés arreglarlo, vas a tener que venir a buscarme.»',
  separacionSinChicos: '{ella} se cansó de esperarte y se volvió a su casa. «Si querés arreglarlo, vas a tener que venir a buscarme.»',
  corto: '{ella} te dejó: «Si no venís nunca, esto no es un noviazgo».',
  seEnfrio: 'Con {ella} la cosa se enfrió: hace días que no la ves.',
  descuido: 'Hace días que no ves a {ella}. Te extraña.',
  vuelven: '¡{ella} y vos vuelven a estar juntos!',
  // el correo (Benigno en la estafeta y Ercilia en el almacén)
  correo: {
    carta: 'Una carta de amor para {ella}. La mando con el tren de mañana. Tranquilo, que no la leo. Bueno, no mucho.',
    ramo: 'Un ramo para {ella}. Le pongo un poco de agua en el frasco y va con el tren de mañana, como un pasajero más.',
    yaHoy: 'A {ella} ya le mandaste algo hoy. No la vas a tapar de correspondencia, ¿no?',
    sinFlores: 'En invierno no hay flores, che. Mandale una carta, que abriga igual.',
    entregada: { carta: 'Tu carta le llegó a {ella}', ramo: 'Tu ramo le llegó a {ella}' },
    entregadaSub: 'Con el tren de la mañana',
  },
  // Anselmo, el herrero
  anillo: {
    pide: 'Un anillo. Con un canto rodado del arroyo, ¿no? Lo pulo hasta que brille como un ojo de agua. En tres días está.',
    sinCanto: 'Para un anillo necesito un canto rodado del arroyo. Uno lindo, liso. Traeme uno y te lo hago.',
    sinNovia: 'Un anillo es cosa seria, muchacho. Primero tené novia, después hablamos.',
    haciendo: 'El anillo todavía está en la fragua. Pocha dice que lo pulo demasiado. Mañana o pasado está.',
    listo: 'Acá está tu anillo. Pocha lloró cuando lo vio. Yo no, eh. Se me metió una chispa en el ojo.',
    yaTenes: 'Ya tenés el anillo. Ahora el que tiene que hacer algo sos vos.',
    avisoListo: 'Anselmo terminó el anillo', avisoListoSub: 'Pasá a buscarlo por la herrería',
  },
  // el casamiento civil (el juez de paz llega en el tren de la mañana; nada religioso)
  boda: {
    fecha: 'Nos casamos el {dia}, a las once, en la biblioteca popular. El juez de paz viene en el tren de la mañana.',
    aviso: 'Hoy te casás con {ella}', avisoSub: 'A las once, en la biblioteca popular',
    escena: [
      'El juez de paz de Esquel se acomoda los anteojos y abre el libro de actas. Ernesto y Pocha son los testigos.',
      '«Estamos acá para unir en matrimonio a dos vecinos de la Aldea de los Duendes. ¿Quieren decir algo?»',
    ],
    si: '«Sí, quiero.» Ella también dice que sí, y la biblioteca entera aplaude. Pocha llora a moco tendido.',
    firma: 'Firman el acta. Afuera, Cholo arranca con un chamamé y la abuela Herminia tira arroz como si fuera nieve.',
    postergada: '{ella} te esperó en la biblioteca con el juez de paz y no viniste. El casamiento pasó para el {dia}.',
    avisoCasados: 'Te casaste con {ella}', avisoCasadosSub: 'Ahora decidan dónde viven',
  },
  // los hijos
  hijos: {
    nacio: '¡Nació {hijo}!', nacioSub: 'La mamá y {hijo} están bien. La casa suma un cuarto',
    crecio: { chico: '{hijo} ya camina y habla hasta por los codos', adolescente: '{hijo} ya es adolescente y se encierra en su cuarto', joven: '{hijo} ya es grande: elige su oficio' },
    charla: {
      bebe: ['{hijo} anoche se despertó tres veces. Pero cuando se ríe, se me pasa todo.', '¿Viste cómo te agarra el dedo {hijo}? No te suelta más.'],
      chico: ['{hijo} preguntó por qué el cielo es celeste. Le dije que te pregunte a vos.', '{hijo} juntó doce piedras en el arroyo y dice que una es un huevo de dinosaurio.'],
      adolescente: ['{hijo} anda con cara de que todo le da vergüenza. Sobre todo nosotros.', '{hijo} quiere que lo dejemos ir solo al lago. Yo digo que sí, pero con vos.'],
      joven: ['{hijo} ya trabaja de lo suyo. A veces lo miro y no lo puedo creer.', '¿Te acordás cuando {hijo} no llegaba a la mesa? Ahora hay que agacharse para darle un beso.'],
    },
    nombres: { nene: ['Lautaro', 'Tomás', 'Ramiro', 'Lihuel', 'Joaquín', 'Facundo', 'Benjamín', 'Ignacio'], nena: ['Malén', 'Catalina', 'Pilar', 'Rayén', 'Julieta', 'Lucila', 'Amancay', 'Clara'] },
  },
  // las habilidades que te enseña tu esposa
  habilidad: { aviso: 'Aprendiste de {ella}: {nombre}', avisoSub: '{texto}' },
  // lo que comentan los vecinos (con humor) cuando se enteran
  comentario: {
    novios: ['Así que vos y {ella}… ¡Ya me enteré! En esta aldea todo se sabe antes de que pase.', '¿Es verdad lo de {ella}? ¡Qué lindo! Ya era hora de que alguien se animara.'],
    comprometidos: ['¡Me dijeron que te casás con {ella}! ¿Me invitan? Más vale que me inviten.', 'Así que hay anillo. Anselmo no habla de otra cosa. Bueno, tampoco habla mucho.'],
    casados: ['¡Felicidades, recién casado! Se te nota en la cara: andás como bobo.', '¡Qué linda la fiesta! Todavía me duelen los pies de bailar.'],
    nacio: ['¡Felicidades por {hijo}! Dicen que tiene tu nariz. Pobre criatura. ¡Es un chiste!', '¡Un bebé en la aldea! Ya le estoy tejiendo unos escarpines.'],
    separados: ['Me enteré de lo de {ella}. Ánimo, que todo tiene arreglo. Casi todo.'],
    volvieron: ['¡Volviste con {ella}! Ya sabía yo. El que se va, vuelve.'],
    'dos-a-la-vez': ['Así que andás con {ella} y con {otra}… Mirá que la aldea es chica, eh. Muy chica.', 'Me contaron que salís con dos. ¿Vos te pensás que acá no se ve todo desde el almacén?'],
    cita: ['Te vi con {ella} en {lugar}. Muy acarameladitos. No digo nada, eh.', '¿Era {ella} la que estaba con vos en {lugar}? No, no pregunto nada. Bueno, sí.'],
  },
  // los chismosos le ponen más ganas
  chisme: {
    novios: ['¡Mirá quién viene! El novio de {ella}. Contame todo, que no se lo digo a nadie. Bueno, a Ercilia sí.'],
    'dos-a-la-vez': ['Escuchame una cosa: {ella} y {otra} se cruzaron en la vereda y no se saludaron. ¿Sabés algo de eso? Porque yo sí.'],
    cita: ['¡Te vi en {lugar} con {ella}! Medio pueblo te vio. El otro medio se enteró por mí.'],
  },
  // para la radio y el diario de la aldea (3.7.4): una línea con humor por cada novedad
  radio: {
    novios: 'Novedades del corazón: {ella} y nuestro vecino del refugio andan de novios. Los vieron tomados de la mano frente al almacén.',
    comprometidos: 'Atención, aldea: hay anillo. Anselmo lo hizo con un canto rodado y Pocha jura que no lloró. Lloró.',
    casados: 'Se casaron {ella} y el vecino del refugio. El juez de paz se llevó torta para el viaje de vuelta.',
    nacio: 'Llegó {hijo}, el vecino más chico de la aldea. Pesó lo que pesa un buen zapallo.',
    separados: 'Se separaron {ella} y el vecino del refugio. Desde esta radio, ánimo a los dos.',
    volvieron: 'Volvieron {ella} y el vecino del refugio. La aldea respira aliviada y Pocha también.',
    'dos-a-la-vez': 'Un vecino del refugio sale con {ella} y con {otra} a la vez. Se le recomienda abrigarse: va a hacer frío.',
    cita: 'Vieron a {ella} y al vecino del refugio en {lugar}. Ella dice que fueron a mirar el paisaje. El paisaje no opina.',
  },
};
