// Tanda F: el modo Desafío.
// Invasores, taller, logros y nido. Las entradas que son fragmentos de código
// o de CSS (no textos de pantalla) quedan idénticas a propósito.
export const EN_F = {
  "; s.title = r.texto; const m = document.createElement('i'); m.textContent = e.ok ? 'se puede' : e.motivo; li.append(b, s, m); li.addEventListener('mousedown', (ev) => { ev.preventDefault(); ev.stopPropagation(); fabricar(i); }); ul.appendChild(li); }); const d = D(); document.getElementById('taller-intro').textContent =": "; s.title = r.texto; const m = document.createElement('i'); m.textContent = e.ok ? 'se puede' : e.motivo; li.append(b, s, m); li.addEventListener('mousedown', (ev) => { ev.preventDefault(); ev.stopPropagation(); fabricar(i); }); ul.appendChild(li); }); const d = D(); document.getElementById('taller-intro').textContent =",
  "); } else if (r.reforzar) { for (const [k, n] of Object.entries(e.refuerzo.pide)) ctx.gastar(k, n); const antes = e.obra.plano.nombre; obras.reemplazarPlano(e.obra, e.refuerzo.a); efectos.polvo({ x: e.obra.datos.x, y: e.obra.datos.y + 1, z: e.obra.datos.z }, 12); ctx.alGuardarObras?.(); ctx.nota(": "); } else if (r.reforzar) { for (const [k, n] of Object.entries(e.refuerzo.pide)) ctx.gastar(k, n); const antes = e.obra.plano.nombre; obras.reemplazarPlano(e.obra, e.refuerzo.a); efectos.polvo({ x: e.obra.datos.x, y: e.obra.datos.y + 1, z: e.obra.datos.z }, 12); ctx.alGuardarObras?.(); ctx.nota(",
  ")); bloque.appendChild(el('div', 'logro-records-texto', textoRecords(logros.records(d)))); contenedor.appendChild(bloque); const { hechos, total } = logros.progreso(); contenedor.appendChild(el('div', 'logro-progreso',": ")); bloque.appendChild(el('div', 'logro-records-texto', textoRecords(logros.records(d)))); contenedor.appendChild(bloque); const { hechos, total } = logros.progreso(); contenedor.appendChild(el('div', 'logro-progreso',",
  "; } else if (esHoraDeAtaque(p.horas) && !d.oleadaTerminada && d.oleadaNoche === claveNoche(p.dia, p.horas)) { const conJefe = jefeVivo() ? ' · ¡el jefe del nido!' : ''; texto = eventos.nodrizaActiva ?": "; } else if (esHoraDeAtaque(p.horas) && !d.oleadaTerminada && d.oleadaNoche === claveNoche(p.dia, p.horas)) { const conJefe = jefeVivo() ? ' · ¡el jefe del nido!' : ''; texto = eventos.nodrizaActiva ?",
  "; hud.classList.toggle('critica', d.salud < 30); } acumuladoHud += dt; if (acumuladoHud < 0.25) return; acumuladoHud = 0; const p = progreso(); const n = vivos(); let texto; const esp = d.especial ?": "; hud.classList.toggle('critica', d.salud < 30); } acumuladoHud += dt; if (acumuladoHud < 0.25) return; acumuladoHud = 0; const p = progreso(); const n = vivos(); let texto; const esp = d.especial ?",
  "; } // Con el segundo acto abierto, el día deja de ser sólo la pausa entre noches. const nido = d.victoria ? resumenNido(d.nido, p.horas) : null; if (nido && !nido.caido) texto +=": "; } // Con el segundo acto abierto, el día deja de ser sólo la pausa entre noches. const nido = d.victoria ? resumenNido(d.nido, p.horas) : null; if (nido && !nido.caido) texto +=",
  ", fraccion, buscando: true }; } const enteras = camarasEnteras(nido); const abierto = estaAbierto(horas); return { fraccion, abierto, enteras, texto: abierto ?": ", fraccion, buscando: true }; } const enteras = camarasEnteras(nido); const abierto = estaAbierto(horas); return { fraccion, abierto, enteras, texto: abierto ?",
  "La nodriza cayó, pero el nido sigue entero. Los restos de nave te van a decir dónde está: se rompe de día, cuando el caparazón se abre": "The mothership is down, but the nest is still whole. The ship wrecks will tell you where it is: you break it by day, when the shell opens",
  ": ''; if (!siguenLasNoches(d)) { // Con el nido abajo no hay noche que contar: va primero que todo lo demás. texto =": ": ''; if (!siguenLasNoches(d)) { // Con el nido abajo no hay noche que contar: va primero que todo lo demás. texto =",
  ": ''; const conJefe = tipos.includes('jefe') ? ' · ¡viene el jefe del nido!' : ''; if (nuevaNoche) ctx.nota(": ": ''; const conJefe = tipos.includes('jefe') ? ' · ¡viene el jefe del nido!' : ''; if (nuevaNoche) ctx.nota(",
  "Clic derecho: disparo cargado que atraviesa a todos los de la línea (150, gasta 3 cargas).": "Right click: a charged shot that punches through everyone in the line (150, uses 3 charges).",
  "); } else if (k === 'flechas' || k === 'emplastos') { d[k] = (d[k] || 0) + n; partes.push(": "); } else if (k === 'flechas' || k === 'emplastos') { d[k] = (d[k] || 0) + n; partes.push(",
  "Punta de piedra atada a un asta. Clic izquierdo golpea; clic derecho sostenido bloquea.": "A stone point lashed to a shaft. Left click strikes; hold right click to block.",
  "Tranquilo, que las empalizadas las voy emparchando yo. Vos ocupate de los bichos esos.": "Don't you worry, I'll keep patching the palisades. You deal with those critters.",
  "; const s = document.createElement('span'); if (r.reparar) s.textContent = e.costo ?": "; const s = document.createElement('span'); if (r.reparar) s.textContent = e.costo ?",
  "Los sacos de la espalda son lo único blando que tiene: pegale ahí y duele el doble": "The sacs on its back are the only soft thing on it: hit there and it hurts double",
  "Con el martillo en la mano reparás tocando la pieza dañada, aun en plena noche.": "With the hammer in hand you repair by touching the damaged piece, even in the dead of night.",
  "Tres piedras atadas: enredan las piernas del invasor y lo dejan quieto un rato.": "Three stones tied together: they tangle an invader's legs and leave it stuck a while.",
  "Resistí una noche abatiendo al menos 3 invasores, todos con la lanza de coihue.": "Survive a night downing at least 3 invaders, every one of them with the coihue spear.",
  "Empalizada → empalizada reforzada · pirca → muro almenado. Resisten mucho más.": "Palisade → reinforced palisade · dry-stone wall → battlemented wall. They hold far longer.",
  "El nido quedó marcado en el mapa. Buscalo de día: de noche no le entra nada.": "The nest is marked on the map. Go for it by day: at night nothing gets through it.",
  "Vi las luces desde el puesto. Si me dejás, te doy una mano con los arreglos": "I saw the lights from the outpost. If you'll have me, I'll lend a hand with the repairs",
  "Estás listo para la primera noche · +1 emplasto, +{0} tablas, +{1} piedras": "You're ready for the first night · +1 poultice, +{0} planks, +{1} stones",
  "El cerco se achica a {0} metros. ${faltan === 1 ? 'Falta una señal más' :": "The ring closes to {0} meters. ${faltan === 1 ? 'Falta una señal más' :",
  "Resistí tu primera noche de invasión y viste clarear sobre los coihues.": "Survive your first night of invasion and watch it grow light over the coihues.",
  "Cuesta un tronco o una piedra por cada 30% de resistencia recuperada.": "Costs one log or one stone for every 30% of strength restored.",
  "Tira piedras de tu reserva: poco daño, muy rápida y munición barata.": "Throws stones from your stock: light damage, very fast, cheap ammo.",
  "Esta noche baja un jefe de nido. Apuntale a los sacos de la espalda": "A nest warden comes down tonight. Aim for the sacs on its back",
  "); if (!nocheActual.dano) partes.push('sin un rasguño'); ctx.nota(": "); if (!nocheActual.dano) partes.push('sin un rasguño'); ctx.nota(",
  "Encontrá la pistola de plasma entre los restos de los invasores.": "Find the plasma pistol among the invaders' wreckage.",
  "Está cerca, con un paracaídas rojo. Pasá por encima para abrirla": "It's close by, under a red parachute. Walk over it to open it",
  ", true); else if (retomada) ctx.nota('Los invasores siguen acá',": ", true); else if (retomada) ctx.nota('Los invasores siguen acá',",
  "Destruí sus tres núcleos rojos: arco, honda, pistola o ballestas": "Destroy its three red cores: bow, sling, pistol or crossbows",
  "Una cúpula que absorbe la mitad del daño de las obras cercanas.": "A dome that soaks up half the damage done to nearby structures.",
  "Resistí una noche de 5 invasores o más sin perder ninguna obra.": "Survive a night of 5 invaders or more without losing a single structure.",
  "Las estacas se partieron: se puede volver a cavar (O → Defensa)": "The stakes snapped: you can dig it again (O → Defense)",
  "En una hora baja la nave. Cerrá el portón y prepará las armas": "The ship comes down in an hour. Shut the gate and ready your weapons",
  "Estaba en la cápsula. Trae doce cargas; los cristales dan más": "It was in the pod. Twelve charges in it; crystals give you more",
  "0 0 0 2px rgba(200,255,94,.75), 0 0 12px rgba(200,255,94,.45)": "0 0 0 2px rgba(200,255,94,.75), 0 0 12px rgba(200,255,94,.45)",
  "Pocos invasores y golpes suaves. Para aprender a defenderse.": "Few invaders and soft blows. For learning how to defend yourself.",
  "Tira flechas lejos. Se fabrica junto a un banco de trabajo.": "Shoots arrows a long way. Made beside a workbench.",
  "Resistí una noche silenciosa, cuando ni los pájaros avisan.": "Survive a silent night, when not even the birds give warning.",
  "La lanza pega 52 en lugar de 34 y llega un poco más lejos.": "The spear hits for 52 instead of 34 and reaches a little farther.",
  "Llegá al alba de la quinta noche en dificultad implacable.": "Reach dawn on the fifth night on relentless difficulty.",
  "Una torre que dispara plasma a los invasores a 30 metros.": "A tower that fires plasma at invaders 30 meters out.",
  "Tengo flechas para rato. Si ves que se me acercan, avisá.": "I've got arrows for a good while. If you see them closing on me, shout.",
  "Derribá la nave nodriza y devolvele el silencio al valle.": "Bring down the mothership and give the valley back its silence.",
  "{0} Ya se puede construir (O → Defensa). +3 cristales": "{0} You can build it now (O → Defense). +3 crystals",
  "La noche es peligrosa, pero con defensas se resiste.": "The night is dangerous, but with defenses you hold.",
  "Esta noche baja la nave nodriza. Preparate para todo": "The mothership comes down tonight. Be ready for anything",
  "Se terminó: de acá no sale nadie más. +{0} cristales": "It's over: nothing else comes out of there. +{0} crystals",
  "Resistí una noche entera sin recibir un solo golpe.": "Survive a whole night without taking a single hit.",
  "; else if (r.reforzar) s.textContent = e.refuerzo ?": "; else if (r.reforzar) s.textContent = e.refuerzo ?",
  "Traje el arco del guardaparque. Desde acá te cubro": "I brought the park ranger's bow. I'll cover you from here",
  "dice si ese punto sirve (tierra, pendiente suave);": "says whether that spot will do (soil, gentle slope);",
  "Fabricá cada una de las recetas al menos una vez.": "Craft every one of the recipes at least once.",
  "Un cristal de los invasores alimenta la pistola.": "One invader crystal feeds the pistol.",
  "Recuperá 3 planos de los restos de naves caídas.": "Recover 3 blueprints from the wrecks of downed ships.",
  "Cura 45 puntos de salud. Se usa desde la barra.": "Heals 45 points of health. Used from the belt.",
  "; } else if (esHoraDeAtaque(p.horas)) { texto =": "; } else if (esHoraDeAtaque(p.horas)) { texto =",
  "Tu perro abatió o ayudó a abatir 10 invasores.": "Your dog downed, or helped down, 10 invaders.",
  "Fabricá más con K, junto a un banco de trabajo": "Make more with K, beside a workbench",
  "Más invasores, más duros. Cada error se paga.": "More invaders, tougher ones. Every mistake costs you.",
  "Restos de una nave {0}. {1} (está en el mapa)": "A ship wreck lies {0}. {1} (it's on the map)",
  "No se oye ni un pájaro. Algo acecha de lejos": "Not a bird to be heard. Something is stalking from far off",
  "Hay invasores cerca: no es momento de dormir": "Invaders nearby: no time to sleep",
  "Cada generador necesita un cristal por noche": "Each generator needs one crystal a night",
  "Juntá piedra con el hacha en un pedrero (H)": "Gather stone with the axe at a scree (H)",
  "No queda ningún invasor. Ya podés descansar": "Not one invader left. You can rest now",
  "Se hacen con piedra y tabla (K → Munición)": "Made from stone and plank (K → Ammo)",
  ", true); else ctx.nota('Llegan refuerzos',": ", true); else ctx.nota('Llegan refuerzos',",
  "Noche {0} · ¡La nave nodriza! · {1} {2}{3}": "Night {0} · The mothership! · {1} {2}{3}",
  "]; if (nocheActual.perdidas) partes.push(": "]; if (nocheActual.perdidas) partes.push(",
  "Flechas más rápidas y con más daño (56).": "Faster arrows, more damage (56).",
  "Tené dos compañeros viviendo en la base.": "Have two companions living at the base.",
  "Tené 20 defensas en pie al mismo tiempo.": "Have 20 defenses standing at the same time.",
  "Nido cerrado · esperá a que salga el sol": "Nest sealed · wait for the sun to come up",
  "Un cristal de invasor da seis cargas (K)": "One invader crystal gives six charges (K)",
  "Astiles de tabla con punta de piedra.": "Plank shafts with stone points.",
  "Te cura mientras estés cerca de ella.": "It heals you while you stay near it.",
  "Algo que todavía no pasó en el valle.": "Something that hasn't happened in the valley yet.",
  "El zumbido de la nave viene más grave": "The ship's hum is coming in lower",
  "Cuando pare, prendelas de nuevo con F": "When it lets up, light them again with F",
  "Una sombra enorme tapa las estrellas": "A huge shadow blots out the stars",
  "Noche {0}{1} · ¡Invasión! {2} {3}{4}": "Night {0}{1} · Invasion! {2} {3}{4}",
  "Reparar la defensa más dañada cerca": "Repair the worst damaged defense nearby",
  "Resistí 5 noches seguidas sin caer.": "Survive 5 nights in a row without going down.",
  "Se hacen con fruta y una ramita (K)": "Made from fruit and a twig (K)",
  "El cielo del oeste se tiñe de rojo": "The western sky is turning red",
  "La nave todavía no bajó esta noche": "The ship hasn't come down yet tonight",
  "Acercate y prendela de nuevo con F": "Get close and light it again with F",
  "acercate a una empalizada o pirca": "get close to a palisade or dry-stone wall",
  "Encontraste una pistola de plasma": "You found a plasma pistol",
  "Está por bajar la nave. Preparate": "The ship is about to come down. Get ready",
  "La nave nodriza sigue ahí arriba": "The mothership is still up there",
  "Puede decirte dónde está el nido": "It can tell you where the nest is",
  "Reforzar la defensa más cercana": "Reinforce the nearest defense",
  "Guardalo para cuando haga falta": "Save it for when you need it",
  "Punta de cristal para la lanza": "Crystal point for the spear",
  "Resistí 10 noches de invasión.": "Survive 10 nights of invasion.",
  "Se ven luces raras en el cielo": "Strange lights in the sky",
  "Abatí 100 invasores en total.": "Down 100 invaders all told.",
  "Resistí una noche de eclipse.": "Survive a night of eclipse.",
  "Algo se estrelló en el bosque": "Something crashed in the forest",
  "La lluvia apagó las antorchas": "The rain put the torches out",
  "Pistola con disparo cargado": "Pistol with charged shot",
  "Condensador para la pistola": "Condenser for the pistol",
  "junto a un banco de trabajo": "beside a workbench",
  "Cae una caja de suministros": "A supply crate is dropping",
  "Puede haber tecnología útil": "There may be useful tech in it",
  "Un bruto apagó una antorcha": "A brute put out a torch",
  "Arco reforzado con cristal": "Crystal-reinforced bow",
  "· ¡viene el jefe del nido!": "· the nest warden is coming!",
  "La pistola está descargada": "The pistol is out of charge",
  "La noche quedó en silencio": "The night has gone quiet",
  "Compañero de cuatro patas": "Four-legged companion",
  "Sin material para reparar": "Nothing to repair it with",
  "¡Una nave baja desde {0}!": "A ship is coming down from {0}!",
  "Con esta lluvia no prende": "It won't light in this rain",
  "La luna se está apagando": "The moon is going out",
  "Los invasores siguen acá": "The invaders are still here",
  "no hay nada dañado cerca": "nothing damaged nearby",
  "Cámara de cría reventada": "Brood chamber blown open",
  "Resistí una noche roja.": "Survive a red night.",
  "No te quedan boleadoras": "No bolas left",
  "Acá me quedo, cuidando.": "I'm staying right here, keeping watch.",
  "Un escudo quedó apagado": "A shield went dark",
  "Te pusiste un emplasto": "You put on a poultice",
  "; else s.textContent =": "; else s.textContent =",
  "El foso quedó deshecho": "The ditch is wrecked",
  "Mejoras con cristales": "Crystal upgrades",
  "Seis cargas de plasma": "Six plasma charges",
  "Baja el jefe del nido": "The nest warden is coming down",
  "Cayó el jefe del nido": "The nest warden is down",
  "hace falta la pistola": "needs the pistol",
  "Baqueano de la noche": "Night guide",
  "Sombra sobre el lago": "Shadow on the lake",
  "No te quedan flechas": "No arrows left",
  "· ¡el jefe del nido!": "· the nest warden!",
  "Preparación completa": "Preparation complete",
  "Falta una señal más": "One more sign to go",
  "No alcanza la carga": "Not enough charge",
  "hace falta la lanza": "needs the spear",
  "Caja de suministros": "Supply crate",
  "Esperá a que afloje": "Wait for it to let up",
  "Rastro de chatarra": "Scrap trail",
  "No tenés emplastos": "You have no poultices",
  "hace falta el arco": "needs the bow",
  "¡Suena la campana!": "The bell is ringing!",
  "Pirca que no cede": "The wall that holds",
  "Manos de artesano": "Craftsman's hands",
  "Pueblo de troncos": "Town of logs",
  "frutas del bosque": "forest fruit",
  "Munición y curas": "Ammo and cures",
  "Fogón compartido": "Shared fire",
  "No tenés piedras": "You have no stones",
  "falta algo antes": "needs something else first",
  "Punta de piedra": "Stone point",
  "; const salud =": "; const salud =",
  "Luna de sangre": "Blood moon",
  "Raíz de ciprés": "Cypress root",
  "sin un rasguño": "without a scratch",
  ", con la clase": ", with the class",
  "Señal del nido": "Sign of the nest",
  "Piel de lenga": "Lenga hide",
  "jefe de nido": "nest warden",
  "Ni un chucao": "Not one chucao",
  "EL NIDO CAYÓ": "THE NEST IS DOWN",
  "Sin munición": "Out of ammo",
  "Estás entero": "You're in one piece",
  "Está entera": "It's in one piece",
  "; texto +=": "; texto +=",
  "cámaras": "chambers",
  "cámara": "chamber",
};
