// Tanda F: el modo Desafío.
// Invasores, taller, logros y nido. Las entradas que son fragmentos de código
// o de CSS (no textos de pantalla) quedan idénticas a propósito.
export const EN_F = {
  "; s.title = r.texto; const m = document.createElement('i'); m.textContent = e.ok ? 'se puede' : e.motivo; li.append(b, s, m); li.addEventListener('mousedown', (ev) => { ev.preventDefault(); ev.stopPropagation(); fabricar(i); }); ul.appendChild(li); }); const d = D(); document.getElementById('taller-intro').textContent =": "; s.title = r.texto; const m = document.createElement('i'); m.textContent = e.ok ? 'se puede' : e.motivo; li.append(b, s, m); li.addEventListener('mousedown', (ev) => { ev.preventDefault(); ev.stopPropagation(); fabricar(i); }); ul.appendChild(li); }); const d = D(); document.getElementById('taller-intro').textContent =",
  "); } else if (r.reforzar) { for (const [k, n] of Object.entries(e.refuerzo.pide)) ctx.gastar(k, n); const antes = e.obra.plano.nombre; obras.reemplazarPlano(e.obra, e.refuerzo.a); efectos.polvo({ x: e.obra.datos.x, y: e.obra.datos.y + 1, z: e.obra.datos.z }, 12); ctx.alGuardarObras?.(); ctx.nota(": "); } else if (r.reforzar) { for (const [k, n] of Object.entries(e.refuerzo.pide)) ctx.gastar(k, n); const antes = e.obra.plano.nombre; obras.reemplazarPlano(e.obra, e.refuerzo.a); efectos.polvo({ x: e.obra.datos.x, y: e.obra.datos.y + 1, z: e.obra.datos.z }, 12); ctx.alGuardarObras?.(); ctx.nota(",
  ")); bloque.appendChild(el('div', 'logro-records-texto', textoRecords(logros.records(d)))); contenedor.appendChild(bloque); const { hechos, total } = logros.progreso(); contenedor.appendChild(el('div', 'logro-progreso',": ")); bloque.appendChild(el('div', 'logro-records-texto', textoRecords(logros.records(d)))); contenedor.appendChild(bloque); const { hechos, total } = logros.progreso(); contenedor.appendChild(el('div', 'logro-progreso',",
  "; } else if (esHoraDeAtaque(p.horas) && !d.oleadaTerminada && d.oleadaNoche === claveNoche(p.dia, p.horas)) { const conJefe = jefeVivo() ? ' · ¡el jefe del nido!' : ''; texto = eventos.nodrizaActiva ?": "; } else if (esHoraDeAtaque(p.horas) && !d.oleadaTerminada && d.oleadaNoche === claveNoche(p.dia, p.horas)) { const conJefe = jefeVivo() ? ' · ¡el jefe del nido!' : ''; texto = eventos.nodrizaActiva ?",
  "; hud.classList.toggle('critica', d.salud < 30); } acumuladoHud += dt; if (acumuladoHud < 0.25) return; acumuladoHud = 0; const p = progreso(); const n = vivos(); let texto; const esp = d.especial ?": "; hud.classList.toggle('critica', d.salud < 30); } acumuladoHud += dt; if (acumuladoHud < 0.25) return; acumuladoHud = 0; const p = progreso(); const n = vivos(); let texto; const esp = d.especial ?",
  "; } // Con el segundo acto abierto, el día deja de ser sólo la pausa entre noches. const nido = d.victoria ? resumenNido(d.nido, p.horas) : null; if (nido && !nido.caido) texto +=": "; } // Con el segundo acto abierto, el día deja de ser sólo la pausa entre noches. const nido = d.victoria ? resumenNido(d.nido, p.horas) : null; if (nido && !nido.caido) texto +=",
  ", fraccion, buscando: true }; } const enteras = camarasEnteras(nido); const abierto = estaAbierto(horas); return { fraccion, abierto, enteras, texto: abierto ?": ", fraccion, buscando: true }; } const enteras = camarasEnteras(nido); const abierto = estaAbierto(horas); return { fraccion, abierto, enteras, texto: abierto ?",
  ": ''; if (!siguenLasNoches(d)) { // Con el nido abajo no hay noche que contar: va primero que todo lo demás. texto =": ": ''; if (!siguenLasNoches(d)) { // Con el nido abajo no hay noche que contar: va primero que todo lo demás. texto =",
  ": ''; const conJefe = tipos.includes('jefe') ? ' · ¡viene el jefe del nido!' : ''; if (nuevaNoche) ctx.nota(": ": ''; const conJefe = tipos.includes('jefe') ? ' · ¡viene el jefe del nido!' : ''; if (nuevaNoche) ctx.nota(",
  "Clic derecho: disparo cargado que atraviesa a todos los de la línea (150, gasta 3 cargas).": "Right click: a charged shot that punches through everyone in the line (150, uses 3 charges).",
  "); } else if (k === 'flechas' || k === 'emplastos') { d[k] = (d[k] || 0) + n; partes.push(": "); } else if (k === 'flechas' || k === 'emplastos') { d[k] = (d[k] || 0) + n; partes.push(",
  "Punta de piedra atada a un asta. Clic izquierdo golpea; clic derecho sostenido bloquea.": "A stone point lashed to a shaft. Left click strikes; hold right click to block.",
  "Tranquilo, que las empalizadas las voy emparchando yo. Vos ocupate de los bichos esos.": "Don't you worry, I'll keep patching the palisades. You deal with those critters.",
  "; const s = document.createElement('span'); if (r.reparar) s.textContent = e.costo ?": "; const s = document.createElement('span'); if (r.reparar) s.textContent = e.costo ?",
  "Con el martillo en la mano reparás tocando la pieza dañada, aun en plena noche.": "With the hammer in hand you repair by touching the damaged piece, even in the dead of night.",
  "Empalizada → empalizada reforzada · pirca → muro almenado. Resisten mucho más.": "Palisade → reinforced palisade · dry-stone wall → battlemented wall. They hold far longer.",
  "Vi las luces desde el puesto. Si me dejás, te doy una mano con los arreglos": "I saw the lights from the outpost. If you'll have me, I'll lend a hand with the repairs",
  "Estás listo para la primera noche · +1 emplasto, +{0} tablas, +{1} piedras": "You're ready for the first night · +1 poultice, +{0} planks, +{1} stones",
  "El cerco se achica a {0} metros. ${faltan === 1 ? 'Falta una señal más' :": "The ring closes to {0} meters. ${faltan === 1 ? 'Falta una señal más' :",
  "Cuesta un tronco o una piedra por cada 30% de resistencia recuperada.": "Costs one log or one stone for every 30% of strength restored.",
  "Tira piedras de tu reserva: poco daño, muy rápida y munición barata.": "Throws stones from your stock: light damage, very fast, cheap ammo.",
  "); if (!nocheActual.dano) partes.push('sin un rasguño'); ctx.nota(": "); if (!nocheActual.dano) partes.push('sin un rasguño'); ctx.nota(",
  "Está cerca, con un paracaídas rojo. Pasá por encima para abrirla": "It's close by, under a red parachute. Walk over it to open it",
  ", true); else if (retomada) ctx.nota('Los invasores siguen acá',": ", true); else if (retomada) ctx.nota('Los invasores siguen acá',",
  "Las estacas se partieron: se puede volver a cavar (O → Defensa)": "The stakes snapped: you can dig it again (O → Defense)",
  "0 0 0 2px rgba(200,255,94,.75), 0 0 12px rgba(200,255,94,.45)": "0 0 0 2px rgba(200,255,94,.75), 0 0 12px rgba(200,255,94,.45)",
  "Tira flechas lejos. Se fabrica junto a un banco de trabajo.": "Shoots arrows a long way. Made beside a workbench.",
  "Resistí una noche silenciosa, cuando ni los pájaros avisan.": "Survive a silent night, when not even the birds give warning.",
  "La lanza pega 52 en lugar de 34 y llega un poco más lejos.": "The spear hits for 52 instead of 34 and reaches a little farther.",
  "Llegá al alba de la quinta noche en dificultad implacable.": "Reach dawn on the fifth night on relentless difficulty.",
  "Tengo flechas para rato. Si ves que se me acercan, avisá.": "I've got arrows for a good while. If you see them closing on me, shout.",
  "La noche es peligrosa, pero con defensas se resiste.": "The night is dangerous, but with defenses you hold.",
  "Resistí una noche entera sin recibir un solo golpe.": "Survive a whole night without taking a single hit.",
  "; else if (r.reforzar) s.textContent = e.refuerzo ?": "; else if (r.reforzar) s.textContent = e.refuerzo ?",
  "Traje el arco del guardaparque. Desde acá te cubro": "I brought the park ranger's bow. I'll cover you from here",
  "dice si ese punto sirve (tierra, pendiente suave);": "says whether that spot will do (soil, gentle slope);",
  "Fabricá cada una de las recetas al menos una vez.": "Craft every one of the recipes at least once.",
  "Cura 45 puntos de salud. Se usa desde la barra.": "Heals 45 points of health. Used from the belt.",
  "; } else if (esHoraDeAtaque(p.horas)) { texto =": "; } else if (esHoraDeAtaque(p.horas)) { texto =",
  "Fabricá más con K, junto a un banco de trabajo": "Make more with K, beside a workbench",
  "Restos de una nave {0}. {1} (está en el mapa)": "A ship wreck lies {0}. {1} (it's on the map)",
  "No se oye ni un pájaro. Algo acecha de lejos": "Not a bird to be heard. Something is stalking from far off",
  "Juntá piedra con el hacha en un pedrero (H)": "Gather stone with the axe at a scree (H)",
  "Se hacen con piedra y tabla (K → Munición)": "Made from stone and plank (K → Ammo)",
  ", true); else ctx.nota('Llegan refuerzos',": ", true); else ctx.nota('Llegan refuerzos',",
  "]; if (nocheActual.perdidas) partes.push(": "]; if (nocheActual.perdidas) partes.push(",
  "Flechas más rápidas y con más daño (56).": "Faster arrows, more damage (56).",
  "Tené dos compañeros viviendo en la base.": "Have two companions living at the base.",
  "Tené 20 defensas en pie al mismo tiempo.": "Have 20 defenses standing at the same time.",
  "Astiles de tabla con punta de piedra.": "Plank shafts with stone points.",
  "Algo que todavía no pasó en el valle.": "Something that hasn't happened in the valley yet.",
  "Cuando pare, prendelas de nuevo con F": "When it lets up, light them again with F",
  "Reparar la defensa más dañada cerca": "Repair the worst damaged defense nearby",
  "Resistí 5 noches seguidas sin caer.": "Survive 5 nights in a row without going down.",
  "Se hacen con fruta y una ramita (K)": "Made from fruit and a twig (K)",
  "El cielo del oeste se tiñe de rojo": "The western sky is turning red",
  "Acercate y prendela de nuevo con F": "Get close and light it again with F",
  "acercate a una empalizada o pirca": "get close to a palisade or dry-stone wall",
  "Reforzar la defensa más cercana": "Reinforce the nearest defense",
  "Guardalo para cuando haga falta": "Save it for when you need it",
  "Resistí una noche de eclipse.": "Survive a night of eclipse.",
  "La lluvia apagó las antorchas": "The rain put the torches out",
  "Pistola con disparo cargado": "Pistol with charged shot",
  "junto a un banco de trabajo": "beside a workbench",
  "Cae una caja de suministros": "A supply crate is dropping",
  "Un bruto apagó una antorcha": "A brute put out a torch",
  "La pistola está descargada": "The pistol is out of charge",
  "La noche quedó en silencio": "The night has gone quiet",
  "Compañero de cuatro patas": "Four-legged companion",
  "Sin material para reparar": "Nothing to repair it with",
  "Con esta lluvia no prende": "It won't light in this rain",
  "La luna se está apagando": "The moon is going out",
  "no hay nada dañado cerca": "nothing damaged nearby",
  "Resistí una noche roja.": "Survive a red night.",
  "No te quedan boleadoras": "No bolas left",
  "Acá me quedo, cuidando.": "I'm staying right here, keeping watch.",
  "Te pusiste un emplasto": "You put on a poultice",
  "; else s.textContent =": "; else s.textContent =",
  "El foso quedó deshecho": "The ditch is wrecked",
  "hace falta la pistola": "needs the pistol",
  "Baqueano de la noche": "Night guide",
  "Sombra sobre el lago": "Shadow on the lake",
  "No te quedan flechas": "No arrows left",
  "Preparación completa": "Preparation complete",
  "No alcanza la carga": "Not enough charge",
  "hace falta la lanza": "needs the spear",
  "Caja de suministros": "Supply crate",
  "Esperá a que afloje": "Wait for it to let up",
  "No tenés emplastos": "You have no poultices",
  "hace falta el arco": "needs the bow",
  "¡Suena la campana!": "The bell is ringing!",
  "Pirca que no cede": "The wall that holds",
  "Manos de artesano": "Craftsman's hands",
  "Pueblo de troncos": "Town of logs",
  "frutas del bosque": "forest fruit",
  "Munición y curas": "Ammo and cures",
  "Fogón compartido": "Shared fire",
  "No tenés piedras": "You have no stones",
  "falta algo antes": "needs something else first",
  "Punta de piedra": "Stone point",
  "; const salud =": "; const salud =",
  "Luna de sangre": "Blood moon",
  "Raíz de ciprés": "Cypress root",
  "sin un rasguño": "without a scratch",
  ", con la clase": ", with the class",
  "Piel de lenga": "Lenga hide",
  "Ni un chucao": "Not one chucao",
  "Sin munición": "Out of ammo",
  "Estás entero": "You're in one piece",
  "Está entera": "It's in one piece",
  "; texto +=": "; texto +=",
  "cámaras": "chambers",
  "cámara": "chamber",
};
