// Tanda G: lo que se le había escapado al extractor en la primera pasada (frases cortas
// sin acentos, que el filtro confundía con código) y los títulos de sección que llegan
// de a pedazos. Se mantiene el vocabulario de las otras tandas.
export const EN_G = {
  // ---- etapas de obra y títulos de sección
  'Cimientos y pilotes': 'Footings and piles',
  'Piso y reparo': 'Floor and shelter',
  'Piso y fondo': 'Floor and back wall',
  'Entramado y cerramiento': 'Frame and walls',
  'Techo y terminaciones': 'Roof and finishing',
  'Plataforma y escalera': 'Platform and stairs',
  'Baranda y banco': 'Railing and bench',
  'Postes y dados': 'Posts and piers',
  'Basas y soleras': 'Footings and sill plates',
  'Lana y viento': 'Wool and wind',
  'Reparar y reforzar': 'Repair and reinforce',
  'Fuego y antorchas': 'Fire and torches',
  'Armas y defensas': 'Weapons and defenses',
  'Especies y lugares': 'Species and places',
  'La resistencia': 'Holding out',
  'El objetivo': 'The goal',
  'Lo primero': 'First things first',
  'El cuaderno': 'The field notebook',
  'La libreta': 'The ledger',
  'El acopio': 'The supply pile',
  'La gente': 'The people',
  'El valle': 'The valley',
  'El bosque': 'The forest',
  'La estepa': 'The steppe',
  'La cordillera': 'The cordillera',
  'La trochita': 'La trochita',   // es el nombre del tren, no una descripción
  'La nodriza': 'The mothership',
  'El nido': 'The nest',
  'El jefe': 'The warden',
  'El salto': 'The leap',
  'El panal': 'The nest comb',
  'El bramido': 'The bellow',
  'La veranada': 'The summer pasture',
  'Una chispa': 'A spark',
  'Una pieza': 'One piece',
  'Los nombres tallados': 'The carved names',   // 3.8.4
  'Al fuego': 'On the fire',
  'A dormir.': 'Time to sleep.',
  'de cabeza': 'head first',
  'un tronco': 'a log',
  '6 tablas': '6 planks',
  'los turcos': 'the peddlers',
  'la parada': 'the stop',
  'TODO EL RECORRIDO': 'WHOLE RUN',
  'El alero del arriero': "The Drover's Overhang",   // 3.8.4 (antes, la Cueva de las Manos)
  'Las Tres Marías': 'Las Tres Marías',
  'Puesto Alto': 'Puesto Alto',
  'Don Ramón': 'Don Ramón',
  'Mangangá': 'Mangangá',
  'Arrayán': 'Arrayán',
  'Coirón': 'Coirón',
  'Maitén': 'Maitén',
  'Mallín': 'Mallín',
  'Piñón': 'Piñón',
  'piñones': 'piñones',
  'pehuén': 'pehuén',
  'Pudú': 'Pudú',

  // ---- menús, ajustes y estados de la interfaz
  'Partidas guardadas': 'Saved games',
  'Teclas y mando': 'Keys and gamepad',
  'En pausa': 'Paused',
  'Autoguardado activo.': 'Autosave is on.',
  'Sin descubrir': 'Not found yet',
  'en curso': 'in progress',
  'En curso': 'In progress',
  'se puede': 'ready to build',
  'sin cubierta': 'no roof',
  'sin tecla': 'no key',
  'sin foto': 'no photo',
  'sin muestras': 'no samples',
  'Sin virado': 'No tint',
  'Con piano': 'With piano',
  '20 minutos': '20 minutes',
  '45 minutos': '45 minutes',
  'Buscando lugar...': 'Looking for a spot...',
  'Hecho con': 'Made with',
  'cuaderno y mapa': 'field notebook and map',
  'heap n/d': 'heap n/a',

  // ---- teclas
  'Shift der.': 'Right Shift',
  'Ctrl der.': 'Right Ctrl',
  'Alt gr.': 'Alt Gr',

  // ---- rumbos de la brújula
  'al norte': 'to the north',
  'al sur': 'to the south',
  'al este': 'to the east',
  'al oeste': 'to the west',
  'al noreste': 'to the northeast',
  'al noroeste': 'to the northwest',
  'al sureste': 'to the southeast',
  'al suroeste': 'to the southwest',
};
