// Tanda R (3.8.0): la noche de los duendes. El Desafío cuenta la historia de la aldea:
// duendes (goblins) en vez de invasores, lechuzas, nidos de hongos, madrigueras, la cueva,
// el Coihue Viejo (Old Coihue), el Rey Duende (Goblin King) y las semillas doradas.
// Se suma al final del diccionario: lo de acá manda.
export const EN_R = {
  ", el más cerca {0}": ", the closest {0}",
  "¡Cayó el Coihue Viejo!": "The Old Coihue has fallen!",
  "¡Cayó el Rey Duende!": "The Goblin King has fallen!",
  "¡Contraatacan {0}!": "They strike back at {0}!",
  "¡Salen duendes desde {0}!": "Goblins coming out from {0}!",
  "¡Se abrió la puertita del Coihue!": "The little door of the Coihue is open!",
  "¡Se le abrió la corteza!": "His bark has split open!",
  "· ¡el capataz!": "· the foreman!",
  "· ¡viene el capataz!": "· the foreman is coming!",
  "{0} · {1} duendes abatidos · dificultad {2}": "{0} · {1} goblins brought down · difficulty {2}",
  "{0} · en una hora salen los duendes": "{0} · in an hour the goblins come out",
  "{0} · la noche que viene llegan {1} menos y más flojos": "{0} · next night {1} fewer will come, and weaker",
  "{0} (libre)": "{0} (free)",
  "{0} {1} la raíz de {2}": "{0} {1} the root at {2}",
  "{0} duendes": "{0} goblins",
  "{0} duendes más desde {1}": "{0} more goblins from {1}",
  "{0} duendes más, desde el bosque": "{0} more goblins, from the forest",
  "{0} más, desde las madrigueras": "{0} more, from the burrows",
  "{0} raíces más": "{0} more roots",
  "{0} vuelven a salir desde {1}": "{0} come out again from {1}",
  "{0} Ya se puede construir (O → Defensa). +3 semillas doradas": "{0} It can be built now (O → Defense). +3 golden seeds",
  "{0}: asegurada": "{0}: secured",
  "{0}. Con las cuatro zonas libres, llegó más débil: le falta una piedra de ámbar": "{0}. With all four zones free, it came in weaker: it is missing an amber stone",
  "+1 semilla dorada · la madriguera se apaga": "+1 golden seed · the burrow goes dark",
  "Abatí 100 duendes en total.": "Bring down 100 goblins in all.",
  "Abatir duendes en el Desafío y leer rastros": "Bringing down goblins in the Challenge and reading tracks",
  "Abrí el mapa (M): el redondel a lápiz marca dónde puede estar. Cada tronco hueco lo achica": "Open the map (M): the pencilled ring shows where it might be. Every hollow log shrinks it",
  "Además de enredar, les dan un chispazo dorado a los que están alrededor.": "Besides tangling, they give a golden spark to the ones around.",
  "Adentro del Coihue": "Inside the Coihue",
  "Adentro del Coihue · {0}": "Inside the Coihue · {0}",
  "Algo se vino abajo en el bosque": "Something came down in the forest",
  "Algo sobrevivió a la cueva. {0} noches más: vienen cambiados": "Something survived the cave. {0} more nights: they come back changed",
  "Algunas noches el tren se queda sin presión lejos de la estación, con Elsa adentro. Avanza sólo si estás cerca: escoltalo hasta la Estación del Valle mientras los duendes van por él.": "Some nights the train runs out of steam far from the station, with Elsa aboard. It only moves when you are close: escort it to Valley Station while the goblins go after it.",
  "alguno": "some",
  "Alto para ser duende, con un farolito de ámbar en la mano que se enciende antes de tirar.": "Tall for a goblin, with a little amber lantern in its hand that lights up before it throws.",
  "Andá de día: con el sol arriba se le abre la boca y quedan a tiro las tres cunas. De noche está tapada": "Go by day: with the sun up its mouth opens and the three cradles come into range. At night it is plugged",
  "Apagaron el fogón de {0}": "They put out the campfire at {0}",
  "Aprenden de cómo te defendés: si todas las noches usás lo mismo, cada vez vienen más preparados contra eso.": "They learn from how you defend yourself: if you use the same thing every night, they come better prepared against it each time.",
  "Aprendieron de cómo te defendés: {0} de cada 10 traen costra de corteza. Cambiá de táctica: lo que no usás, lo olvidan": "They learned from how you defend yourself: {0} in 10 come with a bark crust. Change tactics: what you stop using, they forget",
  "Arco · flechas {0}": "Bow · {0} arrows",
  "Arco reforzado con semilla dorada": "Bow reinforced with a golden seed",
  "Arpón dorado": "Golden harpoon",
  "Arrancar la semilla dorada": "Pull out the golden seed",
  "Asedio · {0}/{1} zonas libres · corteza {2}": "Siege · {0}/{1} zones free · bark {2}",
  "Asedio · {0}/{1} zonas libres · la puertita del Coihue está abierta": "Siege · {0}/{1} zones free · the little door of the Coihue is open",
  "Asedio · defendé el fogón de {0} ({1}%)": "Siege · defend the campfire at {0} ({1}%)",
  "Boleadoras doradas": "Golden bolas",
  "Bolsa de esporas: juntá una ramita para quemarla, o rompela a golpes": "Spore sac: pick up a twig to burn it, or smash it",
  "Bolsa de esporas: mojada no prende, rompela a golpes": "Spore sac: wet, it will not catch; smash it",
  "Cada campana necesita una semilla dorada por noche": "Each bell needs a golden seed a night",
  "Cada capataz es otro: el de siempre, el que llama refuerzos, la sombra que sólo se ve con la linterna y el que tira piedras a las defensas desde lejos.": "Each foreman is different: the usual one, the one who calls for help, the shadow you only see with the flashlight, and the one who throws stones at your defenses from afar.",
  "Cada cinco noches sale uno solo, viejo, enorme y durísimo. Se da vuelta despacio: rodealo y pegale en los hongos de la espalda, que reciben el doble de daño. Al caer suelta muchas semillas doradas.": "Every fifth night a single one comes out, old, huge and very tough. It turns slowly: circle around and hit the mushrooms on its back, which take double damage. When it falls it drops a pile of golden seeds.",
  "Cada duende que veas de cerca queda anotado acá. Peleando se aprende cómo se mueve, y al tercero que abatís, dónde es débil.": "Every goblin you see up close gets written down here. Fighting teaches you how it moves, and by the third one you bring down, where it is weak.",
  "Cada flecha que entra suelta un rayo que salta a los dos duendes más cercanos. Para los grupos.": "Every arrow that hits lets loose a bolt that jumps to the two closest goblins. For groups.",
  "Cada noche salen los duendes del bosque. Levantá tu cabaña, rodeala de defensas, fabricá o encontrá armas y resistí hasta el amanecer.": "Every night the goblins come out of the forest. Put up your cabin, ring it with defenses, craft or find weapons and hold out until dawn.",
  "Cada noche, a las 20:30, salen los duendes del bosque. Resistí hasta el amanecer. Después de la noche 20 despierta el Coihue Viejo.": "Every night at 20:30 the goblins come out of the forest. Hold out until dawn. After night 20 the Old Coihue wakes.",
  "Cada tramo gasta una semilla dorada por noche": "Each stretch uses up a golden seed a night",
  "Caíste adentro y las raíces te sacaron al valle. La puertita sigue abierta: cuando estés listo, volvé a entrar (el Rey Duende se recompone)": "You fell inside and the roots threw you back out into the valley. The little door is still open: when you are ready, go back in (the Goblin King pulls himself together)",
  "Cambiá de táctica. Contra lo demás no tienen nada, y lo que dejás de usar lo olvidan en pocas noches.": "Change tactics. Against everything else they have nothing, and what you stop using they forget within a few nights.",
  "Campana de musgo": "Moss bell",
  "capataz": "foreman",
  "Capataz": "Foreman",
  "Cavaron una madriguera entre las raíces, {0}. Si la rompés de día, de ese lado vienen menos (queda en el mapa cuando la veas)": "They dug a burrow among the roots, {0}. If you wreck it by day, fewer come from that side (it goes on the map once you see it)",
  "Cayó el capataz": "The foreman is down",
  "Cayó el Coihue Viejo": "The Old Coihue has fallen",
  "Cayó el Rey Duende": "The Goblin King has fallen",
  "chispazo de ámbar": "amber spark",
  "chispazo dorado": "golden spark",
  "cofre de los duendes": "goblins' chest",
  "Cofre de los duendes": "Goblins' chest",
  "Coihue Viejo": "Old Coihue",
  "comunes": "plain",
  "Con el arco en la mano, clic derecho cambia de flecha: comunes, incendiarias o doradas.": "With the bow in hand, right click switches arrows: plain, fire or golden.",
  "Con el sol arriba se le abre la boca y quedan a tiro tres cunas de musgo, que se revientan de a una. Les pegan el arco, la honda, la pistola y las ballestas fijas, y también el hacha o la lanza de cerca. Con la cueva derrumbada no sale nadie más.": "With the sun up its mouth opens and three moss cradles come into range; you burst them one at a time. Bow, sling, pistol and mounted crossbows all hurt them, and so do the axe or the spear up close. With the cave caved in, nobody else comes out.",
  "Con la linterna (L), los ojos de los duendes devuelven la luz: dos puntos en la oscuridad. Los rastreadores y los saltadores acechan: si los mirás, se frenan o se esconden; si les das la espalda, cargan. El perro gruñe hacia lo que todavía no ves.": "With the flashlight (L), the goblins' eyes catch the light: two dots in the dark. Trackers and leapers stalk you: look at them and they stop or hide; turn your back and they charge. The dog growls toward what you cannot see yet.",
  "Con la pistola de luz, cada una da seis cargas (K).": "With the light pistol, each one gives six charges (K).",
  "Con tres zonas libres la corteza no alcanza a cerrar. Andá al pie del Coihue de día y entrá por la puertita (E)": "With three zones free the bark cannot close. Go to the foot of the Coihue by day and go in through the little door (E)",
  "Con tres zonas libres se abre la puertita: andá al pie del Coihue de día y apretá E. Se sube por adentro hasta su corazón, donde está el Rey Duende: piedras de ámbar, raíces y el corazón. Si caés, el Coihue te escupe al valle y podés volver a entrar.": "With three zones free the little door opens: go to the foot of the Coihue by day and press E. You climb up inside to its heart, where the Goblin King waits: amber stones, roots and the heart. If you fall, the Coihue spits you back out into the valley and you can go in again.",
  "Con tres zonas libres se puede entrar al Coihue: de día, andá a su pie, a la puertita de las raíces, y apretá E": "With three zones free you can go into the Coihue: by day, go to its foot, to the little door in the roots, and press E",
  "Cortá {0} de día (el mapa las marca) y se abre la puertita": "Cut {0} by day (the map marks them) and the little door opens",
  "Cortá las raíces de día (están en el mapa). De noche van a querer recuperar lo que les saques. Con tres zonas libres se abre la puertita del Coihue": "Cut the roots by day (they are on the map). At night they will try to win back what you take. With three zones free, the little door of the Coihue opens",
  "Cortaste la raíz y el Coihue perdió una capa de corteza (le quedan {0}). Prendiste un fogón: esta noche van a venir por él · +{1} semillas doradas": "You cut the root and the Coihue lost a layer of bark ({0} left). You lit a campfire: tonight they will come for it · +{1} golden seeds",
  "Cortaste la última raíz: el Coihue se quedó sin corteza · +{0} semillas doradas": "You cut the last root: the Coihue has no bark left · +{0} golden seeds",
  "Cortaste una raíz": "You cut a root",
  "Cosa de duendes: mientras estés a menos de 7 m te cura 4 puntos por segundo.": "Goblin craft: while you stay within 7 m it heals you 4 points a second.",
  "Cosa de duendes: tira luz dorada al duende más cercano a 30 m. Más daño que la ballesta.": "Goblin craft: it throws golden light at the nearest goblin within 30 m. More damage than the crossbow.",
  "Cosa de duendes: una campana de musgo de 9 m que absorbe la mitad del daño que reciben las obras de adentro. Consume una semilla dorada por noche.": "Goblin craft: a 9 m bell of moss that soaks up half the damage taken by the builds inside it. It uses up one golden seed a night.",
  "crujido del Coihue Viejo": "creak of the Old Coihue",
  "Cuando se derrumba la cueva, la pantalla final te deja elegir cinco noches más contra los duendes viejos: más duros, y se curan si los dejás respirar.": "When the cave caves in, the final screen lets you choose five more nights against the old goblins: tougher, and they heal if you let them catch their breath.",
  "Cuatro flechas doradas": "Four golden arrows",
  "Cuatro metros de duende viejo, con hongos verdes en la espalda.": "Four metres of old goblin, with green mushrooms on its back.",
  "Cueva abierta · {0} {1} en pie": "Cave open · {0} {1} still standing",
  "Cueva cerrada · esperá a que salga el sol": "Cave shut · wait for the sun to come up",
  "Cueva sin ubicar · cerco de {0} m": "Cave not found yet · ring of {0} m",
  "cuna": "cradle",
  "Cuna reventada": "Cradle burst",
  "cunas": "cradles",
  "Curtido": "Seasoned",
  "De día andá a una raíz (el mapa las marca), peleá con los que la cuidan y cortala. Esa noche vienen por el fogón que prendiste: si aguanta hasta el alba, la zona queda tuya.": "By day go to a root (the map marks them), fight whoever guards it and cut it. That night they come for the campfire you lit: if it holds until dawn, the zone is yours.",
  "De noche la puertita está cerrada": "At night the little door is shut",
  "Defendiste {0}: +{1} troncos, +{2} tablas, +{3} semillas doradas.{4}": "You defended {0}: +{1} logs, +{2} planks, +{3} golden seeds.{4}",
  "Dejó {0} semillas doradas desparramadas": "It left {0} golden seeds scattered around",
  "del este": "to the east",
  "del noreste": "to the northeast",
  "del noroeste": "to the northwest",
  "del norte": "to the north",
  "del oeste": "to the west",
  "del sur": "to the south",
  "del sureste": "to the southeast",
  "del suroeste": "to the southwest",
  "Desafío · {0} {1} · {2} duendes abatidos · mejor racha {3}": "Challenge · {0} {1} · {2} goblins brought down · best streak {3}",
  "Desde la noche 4, al amanecer quedan nidos de hongos y musgo en el bosque. De día se queman con E y una ramita, o se rompen a golpes (sale uno flojo). Los que queden se abren a la noche y suman duendes.": "From night 4 on, at dawn there are nests of mushrooms and moss left in the forest. By day you burn them with E and a twig, or smash them (a weak one comes out). The ones left open up at night and add goblins.",
  "Desde la noche 8, duendes montados en lechuzas. Vuelan alto y bajan en picada a apagar las antorchas; sin antorchas, vienen por vos. Arriba los alcanzan flechas, pistola y la ballesta al cielo (O → Defensa); cuando bajan, también la lanza.": "From night 8, goblins riding owls. They fly high and dive to put out the torches; with no torches left, they come for you. Up high, arrows, the pistol and the sky crossbow reach them (O → Defense); when they dive, the spear does too.",
  "Despierta el Coihue Viejo": "The Old Coihue wakes",
  "Día {0} · la cueva se derrumbó · no sale nadie más": "Day {0} · the cave has caved in · nobody else comes out",
  "Día {0} · los duendes salen en {1}": "Day {0} · the goblins come out in {1}",
  "doradas": "golden",
  "Dos granadas doradas": "Two golden grenades",
  "duende": "goblin",
  "duende abatido": "goblin down",
  "duende cuida": "goblin guards",
  "duendes": "goblins",
  "Duendes {0} de la base": "Goblins {0} of the base",
  "duendes abatidos": "goblins down",
  "Duendes abatidos": "Goblins brought down",
  "duendes cuidan": "goblins guard",
  "Duendes rastreadores, tiradores y brutos. Desde la noche 3 aparecen saltadores, que pasan la empalizada de un salto (la reforzada y el portón no). Desde la 6, escupidores de savia hirviendo que dañan las defensas de lejos.": "Tracker, shooter and brute goblins. From night 3 on there are leapers, which clear a palisade in one jump (not the reinforced one, not the gate). From night 6, boiling-sap spitters that chew up your defenses from a distance.",
  "El bosque cruje entero": "The whole forest is creaking",
  "El bosque de arrayanes": "The arrayán grove",
  "el capataz": "the foreman",
  "El capataz": "The foreman",
  "el capataz que llama": "the foreman who calls",
  "el capataz que tira piedras": "the stone-throwing foreman",
  "el capataz sombra": "the shadow foreman",
  "El cerco se achica a {0} metros. {1}.": "The ring closes in to {0} metres. {1}.",
  "el Coihue (puertita abierta)": "the Coihue (little door open)",
  "El Coihue cayó desde adentro": "The Coihue fell from the inside",
  "El Coihue se viene abajo. ¡Afuera, rápido!": "The Coihue is coming down. Out, quick!",
  "El Coihue te escupió": "The Coihue spat you out",
  "el Coihue Viejo": "the Old Coihue",
  "El Coihue Viejo": "The Old Coihue",
  "EL COIHUE VIEJO": "THE OLD COIHUE",
  "El Coihue Viejo cayó, pero la cueva sigue entera. Los troncos huecos te van a decir dónde está: se rompe de día, cuando se le abre la boca": "The Old Coihue is down, but the cave is still whole. The hollow logs will tell you where it is: it breaks by day, when its mouth opens",
  "El Coihue Viejo no se cayó": "The Old Coihue did not fall",
  "El Coihue Viejo se plantó y hundió raíces en el valle (el mapa las marca). Cortalas de día; de noche defendé el fogón de la última zona que recuperaste": "The Old Coihue has planted itself and sunk roots into the valley (the map marks them). Cut them by day; at night defend the campfire in the last zone you won back",
  "El Coihue Viejo sigue en pie": "The Old Coihue is still standing",
  "el corazón": "the heart",
  "El corazón de ámbar quedó al aire. Ahora viene todo más rápido": "The amber heart is bare. Now everything comes faster",
  "el este": "the east",
  "El fogón aguantó toda la noche. Esa zona ya no la recuperan": "The campfire held all night. They will not win that zone back",
  "el noreste": "the northeast",
  "el noroeste": "the northwest",
  "el norte": "the north",
  "el oeste": "the west",
  "El Rey Duende": "The Goblin King",
  "El Rey Duende · {0}": "The Goblin King · {0}",
  "el sur": "the south",
  "el sureste": "the southeast",
  "el suroeste": "the southwest",
  "El valle respira, pero siguen saliendo. Vienen de una cueva escondida en algún lado: los troncos huecos te van a decir dónde, y se rompe de día, cuando se le abre la boca.": "The valley breathes again, but they keep coming out. They come from a cave hidden somewhere: the hollow logs will tell you where, and it breaks by day, when its mouth opens.",
  "Elsa te agradece: +{0} semillas doradas, +{1} tablas, +{2} piedras": "Elsa thanks you: +{0} golden seeds, +{1} planks, +{2} stones",
  "Empalizadas, pircas, trampas y ballestas contra los duendes.": "Palisades, dry-stone walls, traps and crossbows against the goblins.",
  "En el cuaderno (J), la pestaña Bestiario anota cada duende que ves de cerca. Peleando se aprende cómo se mueve, y al tercero que abatís, su punto débil.": "In the notebook (J), the Bestiary tab records every goblin you see up close. Fighting teaches you how it moves, and by the third one you bring down, its weak spot.",
  "En el taller se hacen incendiarias y doradas (K → Munición)": "Fire and golden ones are made at the workshop (K → Ammo)",
  "En la hora antes del ataque no se puede entrar. Preparate para la noche": "In the hour before the attack you cannot go in. Get ready for the night",
  "En una hora salen los duendes. Cerrá el portón y prepará las armas": "In an hour the goblins come out. Shut the gate and get your weapons ready",
  "Encontrá la pistola de luz en el cofre de los duendes.": "Find the light pistol in the goblins' chest.",
  "Encontraste una madriguera de duendes": "You found a goblin burrow",
  "Encontraste una pistola de luz": "You found a light pistol",
  "Encontró dos semillas doradas en la vía.": "She found two golden seeds on the track.",
  "Engancha al duende y lo arrastra hacia vos (o hacia tus trampas). Vuelve solo.": "Hooks the goblin and drags it toward you (or toward your traps). Comes back on its own.",
  "Engancha y arrastra al duende hacia vos.": "Hooks the goblin and drags it toward you.",
  "Enredan al duende y lo dejan quieto unos segundos.": "They tangle the goblin and keep it still for a few seconds.",
  "Entrar al Coihue por la puertita": "Go into the Coihue through the little door",
  "Entraste por la puertita, subiste hasta el corazón, le reventaste el de ámbar al Rey Duende y saliste antes de que el Coihue tocara el suelo. El valle respira, pero siguen saliendo: vienen de una cueva escondida en algún lado. Los troncos huecos te van a decir dónde.": "You went in through the little door, climbed to the heart, burst the Goblin King's amber one and got out before the Coihue hit the ground. The valley breathes again, but they keep coming out: they come from a cave hidden somewhere. The hollow logs will tell you where.",
  "Escupe savia hirviendo en arco por encima de las defensas. La savia quema las obras donde cae.": "It spits boiling sap in an arc over the defenses. The sap burns whatever builds it lands on.",
  "Ese viene preparado": "That one came ready",
  "Esperá a los duendes con la lanza en la mano (clic izquierdo ataca)": "Wait for the goblins with the spear in hand (left click attacks)",
  "Esta noche despierta el Coihue Viejo. Preparate para todo": "Tonight the Old Coihue wakes. Be ready for anything",
  "Esta noche sale un capataz. Apuntale a los hongos de la espalda": "Tonight a foreman comes out. Aim for the mushrooms on its back",
  "Esta noche salen los duendes": "Tonight the goblins come out",
  "Está por caer la noche: la puertita se cerró hasta mañana": "Night is about to fall: the little door has shut until tomorrow",
  "Estaba en el cofre de los duendes. Trae doce cargas; las semillas doradas dan más": "It was in the goblins' chest. It comes with twelve charges; golden seeds give more",
  "Están por salir los duendes. Preparate": "The goblins are about to come out. Get ready",
  "falta liberar una zona": "one more zone to free",
  "Falta una pista más": "One more clue to go",
  "Faltan {0} pistas": "{0} more clues to go",
  "faltan liberar {0} zonas": "{0} more zones to free",
  "Faro de ámbar": "Amber beacon",
  "Farol de sanación": "Healing lantern",
  "Fase {0} · {1} ({2})": "Phase {0} · {1} ({2})",
  "Fase 3 · el corazón": "Phase 3 · the heart",
  "Flaco, encorvado, con gorro de corteza; corre en cuatro patas cuando te tiene en la mira.": "Skinny, hunched, with a bark cap; runs on all fours once it has you in its sights.",
  "Flechas {0}": "{0} arrows",
  "Flechas {0} · boleadoras {1} · cargas {2} · emplastos {3}{4} · semillas doradas {5} · piedras {6}": "Arrows {0} · bolas {1} · charges {2} · poultices {3}{4} · golden seeds {5} · stones {6}",
  "fogón · {0}": "campfire · {0}",
  "Forja dorada": "Golden forge",
  "Granadas doradas": "Golden grenades",
  "Hay duendes cerca": "There are goblins close by",
  "Hay duendes cerca: despejá la zona para entrar ({0}{1})": "There are goblins close by: clear the area to go in ({0}{1})",
  "Hay duendes cerca: no es momento de dormir": "There are goblins close by: this is no time to sleep",
  "Hilos tensados con polvo de semilla dorada: los duendes que la cruzan avanzan a un tercio de su velocidad.": "Strands strung tight and dusted with golden-seed powder: goblins crossing it move at a third of their speed.",
  "incendiarias": "fire",
  "Jinete de lechuza": "Owl rider",
  "Juntar las semillas doradas": "Gather the golden seeds",
  "La alimentan las cuatro raíces del borde. Saltá las ondas del piso y salí de donde brilla": "The four roots at the edge feed it. Jump the waves on the floor and get out of where it glows",
  "La base está entera. Buen momento para juntar material o salir a buscar semillas doradas.": "The base is in one piece. Good time to gather material or go looking for golden seeds.",
  "La corteza no deja entrar: {0}": "The bark will not let you in: {0}",
  "la cueva": "the cave",
  "La cueva": "The cave",
  "la cueva anda por acá": "the cave is around here",
  "La cueva está marcada": "The cave is marked",
  "La cueva quedó marcada en el mapa. Buscala de día: de noche no le entra nada.": "The cave is marked on the map. Look for it by day: at night nothing gets in.",
  "La madriguera {0} creció": "The burrow {0} grew",
  "La noche 20 despierta el Coihue Viejo, la casa de los duendes, y camina con sus raíces. Tiene tres nudos de ámbar. Cuando cae, ganaste... pero siguen saliendo: vienen de una cueva escondida en el valle.": "On night 20 the Old Coihue wakes, the goblins' home, and walks on its roots. It has three amber knots. When it falls, you have won... but they keep coming out: they come from a cave hidden in the valley.",
  "La orilla del lago": "The lake shore",
  "La puertita del Coihue está cerrada": "The little door of the Coihue is shut",
  "La puertita está abierta": "The little door is open",
  "La puertita está cerrada": "The little door is shut",
  "La puertita no se abre con {0} dando vueltas{1}. Despejá la zona": "The little door will not open with {0} prowling around{1}. Clear the area",
  "La puertita se cerró": "The little door has shut",
  "La puertita sigue abierta. Adentro, el Rey Duende se recompone": "The little door is still open. Inside, the Goblin King pulls himself together",
  "La raíz volvió a crecer. De día se puede volver a cortar": "The root grew back. By day it can be cut again",
  "Lanza (tronco + 2 piedras) para empezar; honda, arco, boleadoras y martillo después. La pistola de luz está en un cofre de los duendes, en el valle.": "Spear (log + 2 stones) to start; sling, bow, bolas and hammer later. The light pistol is in a goblins' chest out in the valley.",
  "Lanza con punta dorada": "Gold-tipped spear",
  "Las lechuzas": "The owls",
  "Las madrigueras crecieron": "The burrows grew",
  "Las madrigueras que rompiste ya no mandan a nadie: {0} menos, y más flojos": "The burrows you wrecked send nobody anymore: {0} fewer, and weaker",
  "Las madrigueras se secaron": "The burrows dried up",
  "las piedras de ámbar": "the amber stones",
  "Las placas doradas aguantaron el golpe": "The golden plates took the blow",
  "las raíces": "the roots",
  "Las sueltan los duendes al caer y aparecen en los troncos huecos. Sirven para las mejoras y las defensas doradas.": "Goblins drop them when they fall, and they turn up in the hollow logs. They go into upgrades and golden defenses.",
  "Le arrancaste la semilla dorada": "You pulled out its golden seed",
  "Le cayó a {0} {1} · quedan {2}": "It landed on {0} {1} · {2} left",
  "Le reventaste una piedra de ámbar": "You burst one of his amber stones",
  "Le sacaste la semilla dorada": "You took out the golden seed",
  "Lente de ámbar para la pistola": "Amber lens for the pistol",
  "Llevás {0} · sirven para cargar la pistola de luz": "You have {0} · they charge the light pistol",
  "lo dorado": "gold",
  "Lo que queda de la madriguera ya no tiene corteza": "What is left of the burrow has no bark anymore",
  "Los alrededores de tu base": "The grounds around your base",
  "Los capataces": "The foremen",
  "los duendes abatidos": "the goblins you bring down",
  "Los duendes la derribaron": "The goblins brought it down",
  "Los duendes siguen acá": "The goblins are still here",
  "Los duendes te dejaron fuera de combate": "The goblins knocked you out",
  "Los duendes todavía no salieron esta noche": "The goblins have not come out yet tonight",
  "Los hongos de la espalda son lo único blando que tiene: pegale ahí y duele el doble": "The mushrooms on its back are the only soft thing on it: hit there and it hurts twice as much",
  "Los hongos de la espalda: el golpe ahí duele el doble.": "The mushrooms on its back: a hit there hurts twice as much.",
  "Los nidos de hongos": "The mushroom nests",
  "Los troncos huecos": "The hollow logs",
  "Los troncos huecos de los duendes se recorren: un pasillo con hongos en el piso que largan esporas (pasalos cuando están cerrados), duendes dormidos (agachado no se despiertan) y el premio al fondo.": "You can walk through the goblins' hollow logs: a passage with mushrooms on the floor that puff spores (cross when they are closed), sleeping goblins (crouch and they will not wake) and the prize at the far end.",
  "Los viejos vieron cómo peleaste: la próxima vez van a venir {0}": "The old ones saw how you fought: next time they will come {0}",
  "madriguera de duendes": "goblin burrow",
  "Más duendes y más duros.": "More goblins, and tougher.",
  "Más duendes, más duros. Cada error se paga.": "More goblins, and tougher. Every mistake costs you.",
  "Mejoras doradas": "Golden upgrades",
  "Monte quieto": "Still woods",
  "Nadie las tocó: ahora mandan más, y tienen más guardia": "Nobody touched them: now they send more, and keep more guard",
  "Nido de hongos: juntá una ramita para quemarlo, o rompelo a golpes": "Mushroom nest: pick up a twig to burn it, or smash it",
  "Nido de hongos: mojado no prende, rompelo a golpes": "Mushroom nest: wet, it will not catch; smash it",
  "No había nadie abajo · quedan {0}": "Nobody was underneath · {0} left",
  "No queda ningún duende. Ya podés descansar": "Not a goblin left. You can rest now",
  "No queda ninguno · +1 semilla dorada": "None left · +1 golden seed",
  "Noche {0} · ¡El Coihue Viejo! · {1} {2}{3}": "Night {0} · The Old Coihue! · {1} {2}{3}",
  "Noche {0}{1} · ¡Salieron! {2} {3}{4}": "Night {0}{1} · They are out! {2} {3}{4}",
  "Noche {0}{1} · {2} duendes{3}": "Night {0}{1} · {2} goblins{3}",
  "Noche tranquila: ya no sale nadie": "A quiet night: nobody comes out anymore",
  "Nudo reventado": "Knot burst",
  "Otra vuelta: vuelve a empezar desde la primera noche, sin base ni materiales, pero con tus armas, las mejoras y los planos. Los duendes vienen {0}% más, aguantan {1}% más y pegan {2}% más fuerte. ¿Vamos?": "Another round: it starts again from the first night, with no base or materials, but with your weapons, upgrades and blueprints. The goblins come {0}% more, last {1}% longer and hit {2}% harder. Shall we?",
  "Palos afilados en ángulo. No cierran el paso: lastiman y frenan a cada duende que las cruza.": "Sharpened poles set at an angle. They do not close the way: they wound and slow every goblin that crosses them.",
  "Pasa por arriba de todo y va derecho a las antorchas prendidas: la lechuza baja en picada y las apaga. Si no queda ninguna, viene rasante por vos.": "It flies over everything and heads straight for lit torches: the owl dives and puts them out. If none are left, it comes skimming in for you.",
  "Perdés las semillas doradas y un 30% de los troncos, tablas y piedras, y amanecés en la base. La cabaña y las defensas se quedan.": "You lose your golden seeds and 30% of your logs, planks and stones, and you wake up at the base. The cabin and the defenses stay.",
  "Perdiste las semillas doradas y parte de los materiales": "You lost your golden seeds and some of your materials",
  "Pista de la cueva": "A clue to the cave",
  "Pistola de luz": "Light pistol",
  "Placas doradas": "Golden plates",
  "Plano recuperado: {0}": "Blueprint recovered: {0}",
  "Planos de los duendes": "Goblin blueprints",
  "Plataforma a 2,4 m con escalera. Desde arriba tus disparos llegan más lejos y pegan 25% más, y los duendes no te alcanzan con las manos.": "A platform 2.4 m up with a ladder. From up there your shots carry further and hit 25% harder, and goblins cannot reach you by hand.",
  "Pocos duendes y golpes suaves.": "Few goblins and soft blows.",
  "Pocos duendes y golpes suaves. Para aprender a defenderse.": "Few goblins and soft blows. For learning to defend yourself.",
  "Puede decirte dónde está la cueva": "It may tell you where the cave is",
  "Puede haber cosas de duende que sirvan": "There may be useful goblin things",
  "Punta con resina: el duende arde unos segundos. Clavadas cerca prenden la zanja y hacen estallar los barriles. Se eligen con el carcaj.": "Resin tips: the goblin burns for a few seconds. Stuck in nearby, they light the trench and blow up the barrels. Pick them with the quiver.",
  "Punta dorada para la lanza": "Golden tip for the spear",
  "Quedan {0} en el bosque · +1 semilla dorada": "{0} left in the forest · +1 golden seed",
  "Quedaron {0} nidos de hongos en el bosque": "{0} mushroom nests were left in the forest",
  "Quedó un nido de hongos en el bosque": "A mushroom nest was left in the forest",
  "Quemar el nido de hongos (1 ramita)": "Burn the mushroom nest (1 twig)",
  "Quemar la bolsa de esporas (1 ramita)": "Burn the spore sac (1 twig)",
  "Quemaste un nido de hongos": "You burned a mushroom nest",
  "Quiénes salen": "Who comes out",
  "raíz · {0}": "root · {0}",
  "Rastro de aserrín": "Sawdust trail",
  "Recuperá 3 planos de los troncos huecos de los duendes.": "Recover 3 blueprints from the goblins' hollow logs.",
  "Recuperaste {0}": "You won back {0}",
  "Resina de pehuén y leña apretada. Estalla cuando un duende se acerca a dos metros: mucho daño alrededor, y se consume.": "Pehuén resin and packed firewood. It goes off when a goblin comes within two meters: heavy damage all around, and it is spent.",
  "resistentes a lo dorado y al rayo": "proof against gold and lightning",
  "Resistí 10 noches de duendes.": "Hold out through 10 goblin nights.",
  "Resistí tu primera noche de duendes y viste clarear sobre los coihues.": "Hold out through your first goblin night and watch the light come up over the coihues.",
  "Resistí una noche abatiendo al menos 3 duendes, todos con la lanza de coihue.": "Hold out through a night bringing down at least 3 goblins, all with the coihue spear.",
  "Resistí una noche de 5 duendes o más sin perder ninguna obra.": "Hold out through a night of 5 or more goblins without losing a single build.",
  "Reventá sus tres nudos de ámbar: arco, honda, pistola o ballestas": "Burst its three amber knots: bow, sling, pistol or crossbows",
  "risita": "giggle",
  "Rompé el hongo alto, las bolsas de esporas y la semilla dorada (que abriga lo demás). Quedó en el mapa": "Wreck the tall mushroom, the spore sacs and the golden seed (which shields the rest). It is on the map now",
  "Romper la cueva": "Breaking the cave",
  "Rompiste el nido de hongos": "You smashed the mushroom nest",
  "Rompiste la madriguera {0}": "You wrecked the burrow {0}",
  "Sale {0}": "Here comes {0}",
  "Sale el capataz": "Here comes the foreman",
  "Sale un capataz": "A foreman comes out",
  "Salen de la madriguera {0}. Rompelas de día y no vienen": "They come out of the burrow {0}. Wreck them by day and they will not come",
  "Salen después de la cueva. Aguantan más, pegan más fuerte y se curan solos si los dejás respirar.": "They come out after the cave. They last longer, hit harder and heal on their own if you let them catch their breath.",
  "Salir por la puertita al valle": "Go out through the little door to the valley",
  "savia que chisporrotea": "sizzling sap",
  "Se abre de nuevo con la luz del día": "It opens again with daylight",
  "Se abrieron {0} nidos de hongos": "{0} mushroom nests burst open",
  "Se abrió un nido de hongos": "A mushroom nest burst open",
  "Se derrumbó la cueva": "The cave has caved in",
  "SE DERRUMBÓ LA CUEVA": "THE CAVE HAS CAVED IN",
  "Se encerró en su corteza": "He shut himself in his bark",
  "Se hacen con ramitas y una semilla dorada (K → Arrojadizas)": "Made with twigs and a golden seed (K → Throwables)",
  "Se hacen con una semilla dorada y una piedra (K → Arrojadizas)": "Made with a golden seed and a stone (K → Throwables)",
  "Se oye un silbido grave en el monte": "A deep whistle sounds in the woods",
  "Se planta a media distancia y te tira chispas de ámbar. No tira si hay una pared entre él y vos.": "It plants itself at middle distance and throws amber sparks at you. It will not throw if there is a wall between you.",
  "Se plantó en el valle, {0}. Hundió {1} raíces que le dan corteza": "It planted itself in the valley, {0}. It sank {1} roots that give it bark",
  "Se terminó: de acá no sale nadie más. +{0} semillas doradas": "It is over: nobody else comes out of here. +{0} golden seeds",
  "Se ve humo verde en el bosque": "There is green smoke in the forest",
  "Se ven lucecitas entre los árboles": "Little lights among the trees",
  "Segundo acto. Los troncos huecos que caen traen pistas y cada una achica el cerco que el mapa dibuja a lápiz; con la tercera queda marcada. La cueva se rompe DE DÍA: de noche le tapan la boca con raíces y no le entra nada.": "Second act. The hollow logs that come down carry clues, and each one tightens the ring your map pencils in; the third one pins it down. The cave breaks BY DAY: at night they plug its mouth with roots and nothing gets in.",
  "Seis cargas de luz": "Six light charges",
  "semilla dorada": "golden seed",
  "semillas doradas": "golden seeds",
  "Semillas doradas": "Golden seeds",
  "Si al alba de la noche 20 el Coihue Viejo sigue en pie, se planta en el valle y hunde raíces en cuatro zonas: tu base, la estación, el lago y el bosque. Cada raíz le da una capa de corteza.": "If at dawn after night 20 the Old Coihue is still standing, it plants itself in the valley and sinks roots into four zones: your base, the station, the lake and the forest. Each root gives it a layer of bark.",
  "Si no lo bajás rápido, llama a otros. Los hongos de la espalda siguen siendo su punto débil": "If you do not bring it down fast, it calls others. The mushrooms on its back are still its weak spot",
  "Siguen saliendo": "They keep coming out",
  "Sin brújula tampoco se ven el rumbo de tus chinches ni los duendes en el borde.": "Without the compass you also lose the bearing of your pins and the goblins at the edge.",
  "Sin la cueva, lo que quedaba en el bosque se deshizo": "Without the cave, what was left in the forest fell apart",
  "Sobreviviste a lo que quedó de la cueva. Ahora sí, el valle es tuyo": "You survived what was left of the cave. Now the valley really is yours",
  "Soplalo: los compañeros vienen a tu lado y los duendes cerca dudan un instante.": "Blow it: your companions come to your side and the goblins nearby hesitate for a moment.",
  "Suena sola cuando un duende se acerca a 30 metros de ella: te avisa aunque estés del otro lado de la base.": "It rings by itself when a goblin comes within 30 meters: it warns you even from the far side of the base.",
  "Te cura mientras estés cerca de él.": "It heals you while you stay close to it.",
  "Te salen al cruce": "They come out to meet you",
  "Tiene costra de corteza: {0}. Probá con otra cosa": "It has a bark crust: {0}. Try something else",
  "Todo entero. Con las semillas doradas que tenés podés reforzar un muro o sumar una defensa dorada.": "All in one piece. With the golden seeds you have you can reinforce a wall or add a golden defense.",
  "Tres piedras atadas: enredan las piernas del duende y lo dejan quieto un rato.": "Three stones tied together: they tangle the goblin's legs and keep it still for a while.",
  "Tres piedras de ámbar le brillan en el cuerpo: rodealo y reventáselas. Se da vuelta despacio": "Three amber stones glow on his body: circle him and burst them. He turns slowly",
  "tronco hueco": "hollow log",
  "Troncos afilados clavados en fila. Frena a los duendes hasta que la derriban. Los tramos se encadenan.": "Sharpened logs driven in a row. It holds goblins up until they bring it down. Sections chain together.",
  "Tu perro abatió o ayudó a abatir 10 duendes.": "Your dog brought down or helped bring down 10 goblins.",
  "un aleteo de lechuza": "an owl's wingbeat",
  "Un arco grande sobre un trípode. Dispara sola contra el duende más cercano a 26 metros.": "A big bow on a tripod. It shoots by itself at the nearest goblin within 26 meters.",
  "Un cerco dorado quedó sin carga": "A golden fence ran out of charge",
  "un duende": "a goblin",
  "Un duende flaco montado en una lechuza grande, de alas que no hacen ruido.": "A skinny goblin riding a big owl whose wings make no sound.",
  "Un duende más, desde el bosque": "One more goblin, from the forest",
  "un nido de hongos que revienta": "a mushroom nest bursting",
  "Un poste con fuego que alumbra el perímetro. A los duendes no les gusta la luz. La lluvia y los brutos la apagan; F la vuelve a prender.": "A post with fire on it that lights the perimeter. Goblins do not like the light. Rain and brutes put it out; F lights it again.",
  "Un pozo tapado con ramas: el duende que lo pisa queda atrapado unos segundos y se lastima. Tarda en rearmarse.": "A pit covered over with branches: the goblin who steps in is stuck for a few seconds and gets hurt. It takes a while to set again.",
  "Un tramo de empalizada con portón de tablas: se abre y se cierra con E. Cerrado, los duendes tienen que romperlo para pasar.": "A stretch of palisade with a plank gate: it opens and closes with E. Shut, goblins have to break it to get through.",
  "Un tronco hueco de los duendes {0}. {1}, al fondo del tronco: cuidado con los hongos del piso y con lo que duerme adentro (está en el mapa)": "A hollow goblin log {0}. {1}, at the far end of the log: mind the mushrooms on the floor and whatever is asleep inside (it is on the map)",
  "Un viejo enorme y lento, con barba de musgo y los ojos color brasa.": "A huge, slow old one, with a moss beard and ember-coloured eyes.",
  "Una ballesta montada en lo alto de un poste, que gira y apunta para arriba. Prefiere a las lechuzas: las alcanza a 34 metros aunque vayan alto. Si no hay ninguno, tira a los de tierra.": "A crossbow mounted high on a post that turns and aims upward. It prefers owls: it reaches them at 34 metres even when they fly high. If there are none, it shoots at the ones on the ground.",
  "Una campana de musgo que absorbe la mitad del daño de las obras cercanas.": "A bell of moss that soaks up half the damage to nearby builds.",
  "Una campana de musgo se apagó": "A moss bell went out",
  "Una lechuza apagó una antorcha": "An owl put out a torch",
  "una raíz más": "one more root",
  "Una semilla dorada da seis cargas (K)": "A golden seed gives six charges (K)",
  "Una semilla dorada de los duendes alimenta la pistola.": "A golden seed from the goblins feeds the pistol.",
  "Una torre que tira luz dorada a los duendes a 30 metros.": "A tower that throws golden light at goblins 30 metres out.",
  "Una zanja larga con estacas paradas en el fondo, tapada con ramas. Se pone a lo largo del paso: el que la cruza se clava, se frena y sigue lastimado. Aguanta doce duendes; después hay que volver a cavarla.": "A long trench with stakes standing in the bottom, covered over with branches. You lay it along the way through: whoever crosses gets spiked, slows down and keeps going hurt. It holds twelve goblins; after that you have to dig it out again.",
  "Uno de los de siempre, con costra de corteza encima, del color de lo que aprendió a aguantar.": "One of the usual ones, with a crust of bark on top, the colour of whatever it learned to take.",
  "Uno de los de siempre, pero viejo: barba de musgo y las venas encendidas de ámbar.": "One of the usual ones, but old: a moss beard and veins glowing amber.",
  "Uno más, desde una madriguera": "One more, from a burrow",
  "Veinte noches hasta el Coihue Viejo, y después la cueva.": "Twenty nights until the Old Coihue, and then the cave.",
  "Viejo": "Old one",
  "Vienen de una cueva escondida en el valle. Los troncos huecos traen pistas que te la van a ubicar": "They come from a cave hidden in the valley. The hollow logs carry clues that will help you find it",
  "Vienen menos": "Fewer are coming",
  "Vienen montados en lechuzas a buscar las llamas. F la vuelve a prender; la ballesta al cielo los baja": "They come riding owls after the flames. F lights it again; the sky crossbow brings them down",
  "Vienen por tu fogón, {0}. Si aguanta hasta el alba, la zona queda tuya": "They are coming for your campfire, {0}. If it holds until dawn, the zone is yours",
  "Volteá al Coihue Viejo y devolvele el silencio al valle.": "Bring down the Old Coihue and give the valley back its silence.",
  "Volviste al valle": "Back in the valley",
  "y de la madriguera": "and from the burrow",
  "Ya juntaste las semillas doradas: vuelven a asomar en": "You already gathered the golden seeds: they come up again in",
};
