// Tanda A: interfaz, menús, guía y paneles.
export const EN_A = {
  "; } // Para guardarlo o pegarlo en algún lado, en texto pelado. export function textoParte(resumen) { const lineas = [resumen.titulo.toUpperCase(), '='.repeat(Math.max(16, resumen.titulo.length))]; for (const b of resumen.bloques) { lineas.push('', b.titulo); for (const [k, v] of b.filas) lineas.push(": "; } // To keep it or paste it somewhere, in plain text. export function textoParte(resumen) { const lineas = [resumen.titulo.toUpperCase(), '='.repeat(Math.max(16, resumen.titulo.length))]; for (const b of resumen.bloques) { lineas.push('', b.titulo); for (const [k, v] of b.filas) lineas.push(",

  "}; if (!CODIGO_VALIDO.test(c)) return { ok: false, mapa: { ...base }, motivo: 'Esa tecla no sirve para el juego.' }; if (base[accion] === c) return { ok: true, mapa: { ...base }, motivo: '' }; if (esFija(accion)) { return { ok: false, mapa: { ...base }, motivo:": "}; if (!CODIGO_VALIDO.test(c)) return { ok: false, mapa: { ...base }, motivo: 'That key does not work in the game.' }; if (base[accion] === c) return { ok: true, mapa: { ...base }, motivo: '' }; if (esFija(accion)) { return { ok: false, mapa: { ...base }, motivo:",

  "Dieciséis lugares para descubrir, la trochita, pesca y kayak, construcción de refugios de varios niveles, un perro que te acompaña, fauna nativa que reacciona a tu presencia, verano, otoño e invierno, y clima cambiante. El recorrido se guarda solo.": "Sixteen places to find, the narrow-gauge train, fishing and kayaking, shelters you build up level by level, a dog that comes along, native wildlife that reacts to you, summer, autumn and winter, and weather that turns. Your journey saves itself.",

  "; } export function htmlPartidas(lista, modo, actual, ahora = Date.now()) { const nombreModo = modo === 'desafio' ? 'Desafío' : 'Relax'; const filas = lista.map((p) => { const esActual = p.ranura === actual; const vista = p.hay && p.vista ?": "; } export function htmlPartidas(lista, modo, actual, ahora = Date.now()) { const nombreModo = modo === 'desafio' ? 'Challenge' : 'Relax'; const filas = lista.map((p) => { const esActual = p.ranura === actual; const vista = p.hay && p.vista ?",

  "); return partes.join(' · '); } export function fechaCorta(ms, ahora = Date.now()) { if (!ms) return ''; const dias = Math.floor((ahora - ms) / 86400000); if (dias <= 0) return 'hoy'; if (dias === 1) return 'ayer'; if (dias < 30) return": "); return partes.join(' · '); } export function fechaCorta(ms, ahora = Date.now()) { if (!ms) return ''; const dias = Math.floor((ahora - ms) / 86400000); if (dias <= 0) return 'today'; if (dias === 1) return 'yesterday'; if (dias < 30) return",



  ": v.toFixed(2); } const esc = (t) => String(t).replace(/[&<>\"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;' }[c])); export function htmlPanelFoto(estado) { const filas = CONTROLES_FOTO.map((c) =>": ": v.toFixed(2); } const esc = (t) => String(t).replace(/[&<>\"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;' }[c])); export function htmlPanelFoto(estado) { const filas = CONTROLES_FOTO.map((c) =>",


  "Una experiencia de exploración en un bosque andino patagónico. El terreno, la vegetación, las estructuras, la fauna, el agua, el clima y buena parte del sonido se generan por código en tiempo real.": "An exploration game set in an Andean Patagonian forest. The terrain, the plants, the structures, the wildlife, the water, the weather and most of the sound are generated by code in real time.",

  "); lineas.push('-'.repeat(64)); for (const t of corrida.tramos) { lineas.push(relleno(t.nombre, 20) + relleno(numero(t.fps), 11) + relleno(numero(t.p1), 10) + relleno(numero(t.medioMs, 1), 10) +": "); lineas.push('-'.repeat(64)); for (const t of corrida.tramos) { lineas.push(relleno(t.nombre, 20) + relleno(numero(t.fps), 11) + relleno(numero(t.p1), 10) + relleno(numero(t.medioMs, 1), 10) +",

  "1–8 plano visible · [ ] cambia página · Tab cambia categoría · R o rueda gira · N snap · Y construye/confirma · Shift+Y mueve pieza · Supr cancela marca/edición · Shift+Supr desmonta · O cierra": "1–8 pick blueprint · [ ] change page · Tab changes category · R or wheel turns · N snap · Y builds/confirms · Shift+Y moves piece · Del cancels mark/edit · Shift+Del dismantles · O closes",

  "Con los planos abiertos: Retroceso deshace la última etapa y te devuelve la mitad, Shift+Supr desmonta una pieza entera, y X copia lo que tenés enfrente para repetirlo con la misma orientación.": "With the blueprints open: Backspace undoes the last stage and gives half of it back, Shift+Del dismantles a whole piece, and X copies what is in front of you to repeat it facing the same way.",


  "Arrimate a un coihue o una lenga con el hacha y apretá H tres veces: el árbol se viene abajo y te da 4 troncos. Un tronco suelto en el suelo da 3 de un golpe. El pehuén no se tala.": "Walk up to a coihue or a lenga with the axe and press H three times: the tree comes down and gives you 4 logs. A loose log on the ground gives 3 in one hit. Pehuén cannot be felled.",

  "Con el martillo en la mano reparás tocando la pieza. En el taller, la pestaña Base repara y refuerza la defensa más cercana: empalizada, pirca y portón tienen su versión reforzada.": "With the hammer in hand you repair by touching the piece. In the workshop, the Base tab repairs and reinforces the nearest defense: palisade, dry-stone wall and gate all have a reinforced version.",


  "; const grupos = CATEGORIAS_BASE.map((c) => { const filas = resumen.filas.filter((f) => f.cat === c.clave); if (!filas.length) return ''; const items = filas.map((f) =>": "; const grupos = CATEGORIAS_BASE.map((c) => { const filas = resumen.filas.filter((f) => f.cat === c.clave); if (!filas.length) return ''; const items = filas.map((f) =>",

  "Donde talaste queda un tocón que rebrota solo: a los pocos días hay un renoval y a los nueve, el árbol entero. Plantar un renoval al lado (B) apura el rebrote.": "Where you felled a tree a stump is left, and it comes back on its own: a few days later there is a sapling, and by day nine the whole tree. Planting a sapling beside it (B) hurries the regrowth.",

  "); } lineas.push('-'.repeat(64)); lineas.push(relleno('TODO EL RECORRIDO', 20) + relleno(numero(r.fps), 11) + relleno(numero(r.p1), 10) + relleno('', 10) +": "); } lineas.push('-'.repeat(64)); lineas.push(relleno('WHOLE RUN', 20) + relleno(numero(r.fps), 11) + relleno(numero(r.p1), 10) + relleno('', 10) +",

  "Fabricá armas, munición, emplastos y mejoras. Tab cambia de pestaña; los números eligen. El arco y las flechas piden estar junto a un banco de carpintero.": "Craft weapons, ammo, poultices and upgrades. Tab switches tabs; the numbers pick. The bow and arrows need you next to a workbench.",

  "Mapa completo del valle · tu posición se marca en rojo · clic para poner una chinche, clic encima para que la brújula te lleve, clic derecho para sacarla": "Full map of the valley · your position shows in red · click to drop a pin, click it again to have the compass lead you there, right click to take it out",

  "El foso con estacas se pone delante del paso: no frena a nadie, pero el que lo cruza se clava. Se gasta con el uso, así que cada tanto hay que rehacerlo.": "The spiked trench goes in front of the way through: it stops nobody, but whatever crosses it gets torn up. It wears down with use, so every so often you have to rebuild it.",

  "Una pila donde dejás lo que juntás (E al lado). Mientras estés cerca, lo que levantes se paga solo del acopio: se termina el ir y venir con todo encima.": "A pile where you drop what you gather (E beside it). While you are close, whatever you build pays itself out of the supply pile: no more walking back and forth loaded down.",

  "+ '<p class=\"sub-partidas\">Exportar deja un archivo que podés llevarte a otra computadora y volver a importar acá.</p>'; } export const CSS_PARTIDAS =": "+ '<p class=\"sub-partidas\">Exporting leaves a file you can carry to another computer and import back here.</p>'; } export const CSS_PARTIDAS =",

  "; return { titulo, texto }; } // Una línea para el panel de depuración (F3). export function textoFps(estado) { const r = resumenFps(estado); return": "; return { titulo, texto }; } // One line for the debug panel (F3). export function textoFps(estado) { const r = resumenFps(estado); return",


  "En los planos, la categoría Defensa: empalizada, portón (E abre y cierra), pirca, estacas, ballesta fija, antorchas (F las prende), torre vigía.": "In the blueprints, the Defense category: palisade, gate (E opens and closes), dry-stone wall, spikes, mounted crossbow, torches (F lights them), watchtower.",

  "Número o clic para fabricar · Tab cambia de categoría · K o Escape cierra · arco, flechas y arco reforzado se hacen junto a un banco de trabajo": "Number or click to craft · Tab changes category · K or Escape closes · bow, arrows and reinforced bow are made next to a workbench",

  "M abre el mapa: un clic pone una chinche donde quieras, otro clic encima hace que la brújula te lleve hasta ahí, y el clic derecho la saca.": "M opens the map: one click drops a pin wherever you like, another click on it sets the compass to lead you there, and right click takes it out.",

  "Con el hacha, Y aserra un tronco en cualquier lado: a mano rinde 2 tablas. En un banco de carpintero (o en el galpón de esquila) rinde 4.": "With the axe, Y saws a log anywhere: by hand it yields 2 planks. At a workbench (or in the shearing shed) it yields 4.",

  "; } export function nombreArchivoPartida(modo, progreso, fecha = new Date()) { const p = (n) => String(n).padStart(2, '0'); const sello =": "; } export function nombreArchivoPartida(modo, progreso, fecha = new Date()) { const p = (n) => String(n).padStart(2, '0'); const sello =",


  "Parado junto a la obra, Y levanta la etapa siguiente si llevás los materiales. Si falta algo, el panel te dice qué y de dónde sale.": "Standing at the site, Y raises the next stage if you are carrying the materials. If something is missing, the panel tells you what and where it comes from.",


  ", }; } export function htmlParte(resumen) { const bloques = resumen.bloques.map((b) => { const filas = b.filas.map(([k, v]) =>": ", }; } export function htmlParte(resumen) { const bloques = resumen.bloques.map((b) => { const filas = b.filas.map(([k, v]) =>",



  "1) Talá un árbol con H. 2) Fabricá la lanza con K. 3) Levantá dos tramos de empalizada y un portón. 4) Poné una antorcha.": "1) Fell a tree with H. 2) Craft the spear with K. 3) Raise two palisade sections and a gate. 4) Put up a torch.",

  "<p class=\"sub-partidas\">Tres partidas para el modo {0}. El otro modo tiene las suyas.</p><div class=\"partidas\">{1}</div>": "<p class=\"sub-partidas\">Three saves for {0} mode. The other mode has its own.</p><div class=\"partidas\">{1}</div>",

  "}; const duena = accionDeTecla(base, c); if (duena && duena !== accion) { return { ok: false, mapa: { ...base }, motivo:": "}; const duena = accionDeTecla(base, c); if (duena && duena !== accion) { return { ok: false, mapa: { ...base }, motivo:",

  "Todo entero. Te faltan trampas: un foso con estacas delante del portón hace mucho daño sin que tengas que estar ahí.": "All in one piece. You are short on traps: a spiked trench in front of the gate does a lot of damage without you standing there.",

  "N abre el estado de tus defensas: cuál está rota, a qué distancia y qué conviene hacer antes de que caiga la noche.": "N opens the state of your defenses: which one is broken, how far off it is, and what is worth doing before night falls.",

  "<p class=\"sub-partidas\">Exportar deja un archivo que podés llevarte a otra computadora y volver a importar acá.</p>": "<p class=\"sub-partidas\">Exporting leaves a file you can carry to another computer and import back here.</p>",

  "; } export function nombreArchivoFoto(fecha = new Date()) { const p = (n) => String(n).padStart(2, '0'); return": "; } export function nombreArchivoFoto(fecha = new Date()) { const p = (n) => String(n).padStart(2, '0'); return",

  "El juego no pudo continuar de forma segura. Cerrá esta versión y conservá el detalle de abajo para depuración.": "The game could not carry on safely. Close this version and keep the details below for debugging.",

  "; export const NOMBRE_DIFICULTAD = { tranquila: 'Tranquila', normal: 'Normal', implacable: 'Implacable' }; //": "; export const NOMBRE_DIFICULTAD = { tranquila: 'Calm', normal: 'Normal', implacable: 'Relentless' }; //",

  "); lineas.push(veredicto(r.fps, r.p1)); if (equipo.escena) lineas.push(''); if (equipo.escena) lineas.push(": "); lineas.push(veredicto(r.fps, r.p1)); if (equipo.escena) lineas.push(''); if (equipo.escena) lineas.push(",

  "Talá árboles, picá piedra, aserrá tablas, fabricá armas (K) y levantá defensas (O) alrededor de tu base.": "Fell trees, break stone, saw planks, craft weapons (K) and raise defenses (O) around your base.",

  "WASD para moverte, el mouse para mirar. Cuando algo se puede usar, abajo aparece la tecla que lo hace.": "WASD to move, mouse to look. When something can be used, the key for it shows up at the bottom.",

  "con los planos abiertos: deshacer la última etapa (devuelve la mitad) · repetir lo que tenés enfrente": "with the blueprints open: undo the last stage (gives half back) · repeat what is in front of you",

  "Juntá tres ramitas con E y apretá F en un lugar despejado. Junto al fuego podés cocinar (G) y dormir.": "Gather three twigs with E and press F in a clear spot. By the fire you can cook (G) and sleep.",

  "Todavía no levantaste ninguna defensa. Empezá por dos tramos de empalizada y un portón (O → Defensa).": "You have not raised a single defense yet. Start with two palisade sections and a gate (O → Defense).",

  "{0} está en {1}%: reparala con el martillo o desde el taller (K → Base) antes de que caiga la noche.": "{0} is at {1}%: repair it with the hammer or from the workshop (K → Base) before night falls.",

  "Plantas, aves y lugares se anotan con E al acercarte. El cuaderno (J) guarda todo y dice qué falta.": "Plants, birds and places get noted with E when you come close. The field notebook (J) keeps it all and says what is missing.",

  "si enchufás un joystick lo toma solo: sticks para caminar y mirar, A salta, X interactúa, R2 ataca": "plug in a gamepad and it picks it up on its own: sticks to walk and look, A jumps, X interacts, R2 attacks",

  "Es lo primero que conviene armar: sólo pide 4 troncos y 2 piedras, y aserrar ahí rinde el doble.": "The first thing worth building: it only asks for 4 logs and 2 stones, and sawing there yields double.",

  "Clic izquierdo ataca, clic derecho sostenido bloquea con la lanza. Doble toque de A o D esquiva.": "Left click attacks, hold right click to block with the spear. Double tap A or D to dodge.",


  "Bajé la calidad a {0}: es lo más liviano que tengo. Si igual va duro, probá achicar la ventana.": "Dropped quality to {0}: that is the lightest I have. If it still runs rough, try shrinking the window.",

  "1 a 8 para elegir · rueda del mouse para cambiar · clic derecho o U para usar · I para cerrar": "1 to 8 to pick · mouse wheel to switch · right click or U to use · I to close",

  "Three.js (licencia MIT) · tipografías Caveat y Spectral (SIL Open Font License) · Electron.": "Three.js (MIT license) · Caveat and Spectral typefaces (SIL Open Font License) · Electron.",

  "]] }); } return { titulo: final ? 'El nido cayó' : 'La nave nodriza cayó', bloques, linea:": "]] }); } return { titulo: final ? 'The nest fell' : 'The mothership fell', bloques, linea:",

  "La partida viene de una versión más nueva del juego. Actualizá Hojarasca y probá de nuevo.": "This save comes from a newer version of the game. Update Hojarasca and try again.",

  "Cada amanecer cae una caja con paracaídas rojo cerca tuyo: pasá por encima para abrirla.": "Every dawn a crate with a red parachute lands near you: walk over it to open it.",

  "}; } if (TECLAS_RESERVADAS.includes(c)) return { ok: false, mapa: { ...base }, motivo:": "}; } if (TECLAS_RESERVADAS.includes(c)) return { ok: false, mapa: { ...base }, motivo:",

  "Juntá troncos y piedra con el hacha (H), aserrá tablas (Y) y abrí los planos con O.": "Gather logs and stone with the axe (H), saw planks (Y) and open the blueprints with O.",

  "WASD vuela · Espacio y Shift suben y bajan · Shift corre · P saca la foto · F2 sale": "WASD flies · Space and Shift go up and down · Shift runs · P takes the photo · F2 exits",

  ": titulo || texto; return { hora, titulo, texto, importante: !!a.importante, linea:": ": titulo || texto; return { hora, titulo, texto, importante: !!a.importante, linea:",

  "Bajé la calidad a {0} para que vaya más fluido. Lo podés cambiar a mano en Ajustes.": "Dropped quality to {0} so it runs smoother. You can change it by hand in Settings.",

  "; } export function textoPartida(p) { if (!p.hay) return 'Vacía'; const partes = [": "; } export function textoPartida(p) { if (!p.hay) return 'Empty'; const partes = [",

  "{0}\\n\\nEsto pisa la partida {1} (día {2}), que no se puede recuperar. ¿Seguimos?": "{0}\\n\\nThis overwrites save {1} (day {2}), which cannot be brought back. Carry on?",

  "“Lo que traigas del bosque lo miramos.” · Trueques disponibles en el mostrador.": "“Whatever you bring out of the forest, we will take a look.” · Trades at the counter.",

  "R deja pasar el tiempo; junto al fuego o en un catre se duerme hasta la mañana.": "R lets time pass; by the fire or on a cot you sleep until morning.",

  "Las rocas grises del suelo (pedreros) se pican con H: cada una da 4 piedras.": "The grey rocks on the ground (rock beds) break with H: each one gives 4 stones.",

  "O abre los planos. Elegí uno, mirá lo que pide y marcá el lugar con el clic.": "O opens the blueprints. Pick one, look at what it asks for and mark the spot with a click.",

  "La trochita para en los apeaderos (E para subir). En la orilla hay un kayak.": "The narrow-gauge train stops at the wayside halts (E to get on). There is a kayak at the shore.",

  "Sólo en Relax: una lista corta con los primeros pasos, que se tilda sola.": "Relax only: a short list of first steps that ticks itself off.",


  "; const dia = Math.max(1, Math.floor(Number(progreso?.dia) || 1)); return": "; const dia = Math.max(1, Math.floor(Number(progreso?.dia) || 1)); return",

  "Están tiradas en todo el bosque: E para juntarlas. Sirven para el fuego.": "They lie all over the forest: E to pick them up. Good for the fire.",

  "Piñones, calafates y frutillas se juntan con E. Se comen o se cocinan.": "Piñones, calafate berries and strawberries are gathered with E. Eat them or cook them.",

  "WASD vuela · Espacio y Shift suben y bajan · P saca la foto · F2 sale": "WASD flies · Space and Shift go up and down · P takes the photo · F2 exits",

  "<p class=\"base-resumen\">{0} {1} · salud media {2}%${resumen.dañadas ?": "<p class=\"base-resumen\">{0} {1} · average health {2}%${resumen.dañadas ?",

  "Se juega, pero justo: conviene bajar un escalón o achicar la ventana.": "Playable, but barely: better to drop a step or shrink the window.",

  "Cambia el rojo y el verde del HUD por tonos que se distinguen mejor.": "Swaps the red and green in the HUD for tones that are easier to tell apart.",

  "{0}\\n\\nSe va a guardar en la partida {1}, que está vacía. ¿Seguimos?": "{0}\\n\\nThis will save to slot {1}, which is empty. Carry on?",

  "fabricar, mejorar armas, reparar y reforzar (Tab cambia de pestaña)": "craft, upgrade weapons, repair and reinforce (Tab changes tab)",

  "); const cabeza = partes.join(', ') + '.'; if (destino?.hay) return": "); const cabeza = partes.join(', ') + '.'; if (destino?.hay) return",

  "Emplasto: 2 frutas + 1 ramita en el taller. Se usa desde la barra.": "Poultice: 2 fruits + 1 twig at the workshop. Use it from the bar.",

  "E para hablar. Algunos te piden encargos y te dan cosas a cambio.": "E to talk. Some give you errands and give you things in return.",

  "Mide los cuadros por segundo y sube o baja un escalón, avisando.": "Measures frames per second and moves a step up or down, telling you.",

  "base-pieza${f.pct < 50 ? ' rota' : f.pct < 100 ? ' tocada' : ''}": "base-pieza${f.pct < 50 ? ' rota' : f.pct < 100 ? ' tocada' : ''}",

  "bloquear con la lanza · disparo cargado con la pistola mejorada": "block with the spear · charged shot with the upgraded pistol",

  "Todo lo necesario para recorrer Hojarasca sin volver al README.": "Everything you need to get around Hojarasca without going back to the README.",

  "Cómo están tus defensas y qué conviene hacer antes de la noche.": "How your defenses are holding and what is worth doing before night.",

  "Hay {0} {1}. Con el martillo en la mano se reparan tocándolas.": "There are {0} {1}. With the hammer in hand you repair them by touching them.",

  "; return { titulo, texto }; } const texto = hasta === 'alta' ?": "; return { titulo, texto }; } const texto = hasta === 'alta' ?",

  ", horaCorta(p.horas)]; if (p.modo === 'desafio') partes.push(": ", horaCorta(p.horas)]; if (p.modo === 'desafio') partes.push(",


  "levantar la etapa / aserrar tablas (a mano 2, en el banco 4)": "raise the stage / saw planks (2 by hand, 4 at the bench)",

  "Tocá una acción y apretá la tecla que quieras. Esc cancela.": "Tap an action and press the key you want. Esc cancels.",

  "Anotá dos cosas en el cuaderno: plantas, aves, lugares (E)": "Note two things in the field notebook: plants, birds, places (E)",

  "Poné una antorcha de guardia: de noche vas a necesitar luz": "Put up a torch on watch: you will want light at night",

  "caminando entre los árboles, que es donde hay más de todo": "walking among the trees, which is where there is most of everything",

  "Talá un árbol: H tres veces junto a un coihue o una lenga": "Fell a tree: H three times next to a coihue or a lenga",

  "Cuánto rinde tu equipo en el mismo recorrido de siempre.": "How your machine holds up on the same run as always.",

  "]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '": "]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '",

  "Qué hacer, de dónde sale cada cosa y cómo se construye.": "What to do, where everything comes from and how to build.",

  "Reduce balanceo al caminar y movimiento en tren/kayak.": "Cuts down head sway while walking and motion on train and kayak.",

  "Aserrá tablas: Y convierte un tronco en dos (juntá 10)": "Saw planks: Y turns one log into two (gather 10)",

  "El archivo llegó cortado o modificado: la firma no da.": "The file arrived cut short or altered: the signature does not match.",

  "estado de la base: qué defensa está dañada (Desafío)": "state of the base: which defense is damaged (Challenge)",

  ").join(''); const cuerpo = sel.items.map(([t, d]) =>": ").join(''); const cuerpo = sel.items.map(([t, d]) =>",

  "El archivo es demasiado grande para ser una partida.": "The file is too big to be a save.",

  "un bosque andino patagónico para recorrer despacio": "an Andean Patagonian forest to walk slowly",

  "Q saca la caña; clic para lanzar en un río o lago.": "Q brings out the rod; click to cast in a river or lake.",

  "Va holgado: se puede subir la calidad un escalón.": "Plenty of room: you can raise quality a step.",

  "); lineas.push(''); if (r.peorTramo) lineas.push(": "); lineas.push(''); if (r.peorTramo) lineas.push(",

  "anotar, juntar, sentarte, subir al kayak, dormir": "note, gather, sit, get in the kayak, sleep",

  "juntar, anotar, hablar, abrir puertas y portones": "gather, note, talk, open doors and gates",

  "Subí la calidad a {0}: tu máquina daba de sobra.": "Raised quality to {0}: your machine had room to spare.",

  "La cámara se mueve sola. Esc corta la medición.": "The camera moves on its own. Esc stops the measurement.",

  "Abrí los planos y marcá dónde va tu refugio (O)": "Open the blueprints and mark where your shelter goes (O)",

  "Sumá un portón para entrar y salir de tu fuerte": "Add a gate to get in and out of your fort",

  "Tiñe apenas la imagen al atardecer y de noche.": "Tints the image a little at dusk and at night.",

  "aserrar tablas / levantar la etapa de una obra": "saw planks / raise the stage of a build",

  "medio valle a la vista: lo más caro de dibujar": "half the valley in view: the most expensive to draw",

  "No llega: bajá la calidad o achicá la ventana.": "Not enough: drop the quality or shrink the window.",

  "talar un árbol (tres hachazos) o picar piedra": "fell a tree (three axe strokes) or break stone",

  "modo foto: cámara libre, hora, encuadre y luz": "photo mode: free camera, time, framing and light",

  "Levantá dos tramos de empalizada: O → Defensa": "Raise two palisade sections: O → Defense",

  "interactuar, juntar, sentarte, abrir puertas": "interact, gather, sit, open doors",

  "El archivo no tiene ninguna partida adentro.": "There is no save inside this file.",

  "Talá un árbol con el hacha: tres golpes (H)": "Fell a tree with the axe: three strokes (H)",

  "Ese archivo no es una partida de Hojarasca.": "That file is not a Hojarasca save.",

  "Subí la calidad a {0}: venía sobrando aire.": "Raised quality to {0}: there was air to spare.",

  "El piano cambia con la estación y la hora.": "The piano changes with the season and the hour.",

  "Más alto muestra más mundo a los costados.": "Higher shows more world out to the sides.",

  ").join(''); const guias = GUIAS.map((g) =>": ").join(''); const guias = GUIAS.map((g) =>",

  "dejar en el suelo lo que tenés en la mano": "put down what you are holding",

  "Elegí con 1, 2, 3 o 4 · Escape para salir": "Pick with 1, 2, 3 or 4 · Escape to leave",

  "caminar / remar / moverte dentro del tren": "walk / paddle / move around inside the train",

  "talar árboles o picar piedra con el hacha": "fell trees or break stone with the axe",

  "mochila · elegir lo que llevás en la mano": "pack · choose what you hold",

  "atacar con el arma en la mano (Desafío)": "attack with the weapon in hand (Challenge)",

  "esquivar hacia un costado (doble toque)": "dodge to one side (double tap)",

  "Hacé clic para volver a mirar alrededor": "Click to go back to looking around",

  "hojarasca-{0}-dia{1}-{2}.hojarasca.json": "hojarasca-{0}-day{1}-{2}.hojarasca.json",

  "); if (equipo.resolucion) lineas.push(": "); if (equipo.resolucion) lineas.push(",

  "caminar · correr · saltar · agacharte": "walk · run · jump · crouch",

  "); if (equipo.limiteFps) lineas.push(": "); if (equipo.limiteFps) lineas.push(",

  "Ercilia · Almacén de Ramos Generales": "Ercilia · General Store",

  "galpón, almacén y todo lo construido": "shed, store and everything built",

  "]; if (paquete.version) partes.push(": "]; if (paquete.version) partes.push(",

  "hacha: talar árboles y picar piedra": "axe: fell trees and break stone",

  "partida${esActual ? ' actual' : ''}": "partida${esActual ? ' actual' : ''}",

  "); if (equipo.cuando) lineas.push(": "); if (equipo.cuando) lineas.push(",

  "Encendé una fogata en un claro (F)": "Light a campfire in a clearing (F)",

  "descansar y dejar pasar el tiempo": "rest and let time pass",

  "Se aplica al volver a la portada.": "Takes effect back at the title screen.",

  "Recursos: de dónde sale cada cosa": "Resources: where everything comes from",

  "taller: armas, munición y mejoras": "workshop: weapons, ammo and upgrades",

  "hojarasca-{0}{1}{2}-{3}{4}{5}.png": "hojarasca-{0}{1}{2}-{3}{4}{5}.png",

  "Esa tecla no sirve para el juego.": "That key does not work in the game.",

  "caña de mosca (clic para lanzar)": "fly rod (click to cast)",

  "abrir los planos de construcción": "open the building blueprints",

  "Módulo cercano · todavía abierto": "Module nearby · still open",

  "luces, sombras y niebla de noche": "lights, shadows and fog at night",

  "Ventana {0}${equipo.pixelRatio ?": "Window {0}${equipo.pixelRatio ?",

  "Juntá tres ramitas del suelo (E)": "Gather three twigs off the ground (E)",

  "{0} está reservada por el juego.": "{0} is reserved by the game.",

  "agacharte y moverte en silencio": "crouch and move quietly",

  "Viento, agua, pájaros y lluvia.": "Wind, water, birds and rain.",

  "aserrar tablas / levantar etapa": "saw planks / raise stage",

  "terreno abierto con niebla baja": "open ground with low fog",

  "hablar con la gente del bosque": "talk to the people of the forest",

  "Pasos, hacha, golpes y avisos.": "Footsteps, axe, hits and alerts.",

  "Hojarasca encontró un problema": "Hojarasca ran into a problem",

  "Aserrá un tronco en tablas (Y)": "Saw a log into planks (Y)",

  "Límite de cuadros por segundo": "Frames per second cap",

  "Versión {0}": "Version {0}",

  "linterna · prismáticos · foto": "flashlight · binoculars · photo",

  "; if (resumen.dañadas) return": "; if (resumen.dañadas) return",

  "; }).join(''); const cabeza =": "; }).join(''); const cabeza =",

  "elegir qué llevás en la mano": "choose what you hold",

  "usar lo que tenés en la mano": "use what you are holding",

  "prender una antorcha apagada": "light an unlit torch",

  "HOJARASCA · BANCO DE PRUEBAS": "HOJARASCA · BENCHMARK",

  "Fabricá una lanza: K → Armas": "Craft a spear: K → Weapons",

  "hojarasca-banco-{0}-{1}.txt": "hojarasca-benchmark-{0}-{1}.txt",

  "Empezar un recorrido nuevo": "Start a new journey",

  "F3 muestra el rendimiento.": "F3 shows performance.",

  "WASD · Shift · Espacio · C": "WASD · Shift · Space · C",

  "Anotaciones en el cuaderno": "Notes in the field notebook",

  "No existe la acción \"{0}\".": "There is no action \"{0}\".",

  "armar o levantar la carpa": "set up or take down the tent",

  "usar el objeto en la mano": "use the item in hand",

  "fuego · prender antorchas": "fire · light torches",

  "agua, reflejos y sol bajo": "water, reflections and low sun",

  "No se llegó a medir nada.": "Nothing got measured.",

  "Va bien con esta calidad.": "Runs fine at this quality.",

  "Subtítulos de los avisos": "Subtitles for alerts",

  "dejar objeto en el suelo": "drop item on the ground",

  "Arrepentirse sale barato": "Changing your mind is cheap",

  ": '', ].join(''); return": ": '', ].join(''); return",

  "${estado.guias === g.id}": "${estado.guias === g.id}",

  "\"{0}\" va siempre en {1}.": "\"{0}\" always goes on {1}.",

  "Volver a las de fábrica": "Back to defaults",

  "Anotá lo que encuentres": "Note what you find",

  "El día es para preparar": "The day is for getting ready",

  "Juntar, anotar y hablar": "Gather, note and talk",

  "Aserrar / levantar obra": "Saw / raise build",

  "Partida de {0}, día {1}": "{0} save, day {1}",

  "clic derecho sostenido": "right click held",

  "Dificultad del Desafío": "Challenge difficulty",

  "Sensibilidad del mouse": "Mouse sensitivity",

  "planos de construcción": "building blueprints",

  "armar o levantar carpa": "set up or take down tent",


  "El banco de carpintero": "The workbench",

  "Primer día · preparate": "First day · get ready",

  "Planos de construcción": "Building blueprints",

  "El archivo está vacío.": "The file is empty.",

  "Abatidos por el perro": "Brought down by the dog",

  "; }).join(''); return": "; }).join(''); return",

  "Preparando el bosque": "Preparing the forest",

  "Movimiento de cámara": "Camera movement",

  "Mejor racha sin caer": "Best streak without falling",


  "); else partes.push(": "); else partes.push(",

  "; const acciones = [": "; const acciones = [",

  "${!estado.congelado}": "${!estado.congelado}",

  "Hacha: talar y picar": "Axe: fell and break",

  "Deuteranopía (verde)": "Deuteranopia (green)",

  "{0} ya la usa \"{1}\".": "{0} is already used by \"{1}\".",


  "cocinar en el fuego": "cook on the fire",

  "Hojarasca · Mega RC": "Hojarasca · Mega RC",

  "Volver a la portada": "Back to the title screen",

  "Guía del primer día": "First day guide",

  "Que se acomode sola": "Let it adjust itself",

  "El parte de la base": "The base report",

  "Brillo de las luces": "Light brightness",

  "${estado.congelado}": "${estado.congelado}",

  "Lo más pesado: {0}.": "Heaviest: {0}.",

  "plantar un renoval": "plant a sapling",

  "ver el rendimiento": "see performance",

  "Créditos y versión": "Credits and version",

  "Calidad automática": "Automatic quality",

  "Ganaste el Desafío": "You won the Challenge",

  "Levantá por etapas": "Build in stages",

  "Vivir en el bosque": "Living in the forest",


  "Vecinos en la base": "Neighbors at the base",

  "Puesto de troncos": "Log outpost",

  "Abrir el cuaderno": "Open the field notebook",

  "Estado de la base": "State of the base",

  "Tu primer refugio": "Your first shelter",

  "estado de la base": "state of the base",

  "Lo que levantaste": "What you have built",

  "Días en el bosque": "Days in the forest",

  "Ir a la izquierda": "Go left",

  "Protanopía (rojo)": "Protanopia (red)",

  "Tritanopía (azul)": "Tritanopia (blue)",

  "galpón de esquila": "shearing shed",

  "Entrar al bosque": "Into the forest",

  "Logros y récords": "Achievements and records",

  "Banco de pruebas": "Benchmark",

  "hacer una fogata": "make a campfire",

  "abrir la mochila": "open the pack",

  "Duración del día": "Day length",

  "Hora de tu reloj": "Your clock time",

  "El bosque vuelve": "The forest comes back",

  "Veces que caíste": "Times you fell",

  "Sendero y mallín": "Trail and wet meadow",

  "recién se apretó": "just pressed",

  "Calidad gráfica": "Graphics quality",

  "Guardar la foto": "Save the photo",

  "Salir del juego": "Quit the game",

  "Que pasen solas": "Let them turn",

  "Tamaño de letra": "Text size",

  "Campo de visión": "Field of view",

  "Virado de color": "Color tint",

  "Copiar el parte": "Copy the report",

  "Abrí los planos": "Open the blueprints",

  "El mapa es tuyo": "The map is yours",

  "cuaderno · mapa": "notebook · map",

  "Árboles talados": "Trees felled",

  "Lo que te queda": "What you have left",

  "--pct:${f.pct}%": "--pct:${f.pct}%",

  "${esc(p.vista)}": "${esc(p.vista)}",

  "${estado[c.id]}": "${estado[c.id]}",

  "Orilla del lago": "Lakeshore",

  "Ir a la derecha": "Go right",

  "Guía del juego": "Game guide",

  "guía del juego": "game guide",

  "clic derecho /": "right click /",

  "sacar una foto": "take a photo",

  "Sacar una foto": "Take a photo",

  "Solo el bosque": "Just the forest",

  "/ clic derecho": "/ right click",

  "fogata / fogón": "campfire / fire pit",



  "Modo de juego": "Game mode",

  "caña de mosca": "fly rod",

  "Caminá y mirá": "Walk and look",

  "Caja del alba": "Dawn crate",

  "El taller (K)": "The workshop (K)",

  "Quiénes bajan": "Who comes down",

  "Piezas en pie": "Pieces standing",

  "· todo entero": "· all in one piece",

  "Caminar atrás": "Walk backward",

  "caja del alba": "dawn crate",

  "está apretado": "held down",

  "Deuteranopía": "Deuteranopia",

  "La dejo fija": "Leave it fixed",

  "Construcción": "Building",


  "Hora del día": "Time of day",

  "prismáticos": "binoculars",

  "Ver el mapa": "See the map",

  "En el valle": "In the valley",

  "Empezar acá": "Start here",

  "Prismáticos": "Binoculars",

  "árbol joven": "young tree",

  "✓ Guardado": "✓ Saved",

  "Protanopía": "Protanopia",

  "Tritanopía": "Tritanopia",

  "Sin límite": "Unlimited",

  "fotografía": "photography",

  "Hacé fuego": "Make fire",

  "Seguir acá": "Continue here",

  "Exposición": "Exposure",

  "L · Z · P": "L · Z · P",

  "esta guía": "this guide",

  "anotación": "note",

  ", p.hay ?": ", p.hay ?",

  "Sin guías": "No guides",

  "Cruceta ↑": "D-pad ↑",

  "Cruceta ↓": "D-pad ↓",

  "Cruceta ←": "D-pad ←",

  "Cruceta →": "D-pad →",

  "Créditos": "Credits",

  "Estación": "Season",

  "· en uso": "· in use",

  "Desafío": "Challenge",

  "Si caés": "If you fall",

  "I · 1–8": "I · 1–8",

  "1% peor": "1% low",


  "Mínima": "Lowest",

  "Música": "Music",

  "Viñeta": "Vignette",

  "dórica": "Dorian",

  "Otoño": "Autumn",

  "J · M": "J · M",

  "Vacía": "Empty",

  "árbol": "tree",

  "tocón": "stump",

  "Guía": "Guide",

  "Menú": "Menu",
};
