// Tanda C: avisos y mensajes del juego.
// Lo que aparece en pantalla mientras jugás: avisos, pistas, títulos de notas,
// textos del HUD y mensajes cortos de src/main.js. Los huecos {0}, {1}… se
// conservan tal cual (pueden cambiar de orden si el inglés lo pide).
// De los fragmentos que el extractor pescó de más se traduce el castellano de
// adentro; el código, el MIME y el molde del nombre de archivo quedan igual.
export const EN_C = {
  ")); b2.appendChild(el('span', 'marca', p.estacion)); if (paginaActual === i) b2.setAttribute('aria-current', 'true'); b2.addEventListener('click', () => { paginaActual = i; dibujarCuaderno(); }); const li = el('li'); li.appendChild(b2); ul.appendChild(li); }); lista.appendChild(ul); const p = paginas[Math.min(paginaActual, paginas.length - 1)]; if (p) { ficha.appendChild(el('h2', '',": ")); b2.appendChild(el('span', 'marca', p.estacion)); if (paginaActual === i) b2.setAttribute('aria-current', 'true'); b2.addEventListener('click', () => { paginaActual = i; dibujarCuaderno(); }); const li = el('li'); li.appendChild(b2); ul.appendChild(li); }); lista.appendChild(ul); const p = paginas[Math.min(paginaActual, paginas.length - 1)]; if (p) { ficha.appendChild(el('h2', '',",
  ", 'La brújula te lleva. Clic encima para soltarla, clic derecho para sacarla'); } sonido.anotar?.(); guardar(); dibujarMapaSiAbierto(); } function sacarDelMapa(ev) { ev.preventDefault(); const p = puntoDelMapa(ev); const c = chincheCerca(chinches(), p.x, p.z); if (!c) return; if (chincheActiva === c) chincheActiva = null; progreso.chinches = sacarChinche(chinches(), c); nota(": ", 'The compass takes you there. Click it to let it go, right-click to pull it out'); } sonido.anotar?.(); guardar(); dibujarMapaSiAbierto(); } function sacarDelMapa(ev) { ev.preventDefault(); const p = puntoDelMapa(ev); const c = chincheCerca(chinches(), p.x, p.z); if (!c) return; if (chincheActiva === c) chincheActiva = null; progreso.chinches = sacarChinche(chinches(), c); nota(",
  "; else textoTren = ''; } else textoTren = ''; } const textoPesca = pesca.est.equipada ? pesca.texto() : ''; if (textoTren) { estado.textContent = textoTren; estado.classList.remove('oculto'); } else if (textoPesca) { estado.textContent = textoPesca; estado.classList.remove('oculto'); } else if (js.sentado) { estado.textContent =": "; else textoTren = ''; } else textoTren = ''; } const textoPesca = pesca.est.equipada ? pesca.texto() : ''; if (textoTren) { estado.textContent = textoTren; estado.classList.remove('oculto'); } else if (textoPesca) { estado.textContent = textoPesca; estado.classList.remove('oculto'); } else if (js.sentado) { estado.textContent =",
  ", 'Seguí dándole con H'); return; } golpesTala.delete(o.arbol); // cae para el lado contrario al tuyo: nunca encima const js2 = jugador.estado; veg.talar(o.arbol, { x: o.arbol.x - js2.pos.x, z: o.arbol.z - js2.pos.z }); sonido.arbolCae(dondeSuena); anotarTalado(o.arbol); sumarMaterial('tronco', TRONCOS_TALA); nota(": ", 'Keep at it with H'); return; } golpesTala.delete(o.arbol); // falls away from you: never on top of you const js2 = jugador.estado; veg.talar(o.arbol, { x: o.arbol.x - js2.pos.x, z: o.arbol.z - js2.pos.z }); sonido.arbolCae(dondeSuena); anotarTalado(o.arbol); sumarMaterial('tronco', TRONCOS_TALA); nota(",
  ", 'Elsa, la guarda'); } else if (!estadoTren.parado) cantada = false; const p = estadoTren.proxima; const donde = estadoTren.asiento && estadoTren.asiento.plataforma ? 'En la plataforma abierta' : 'En tu asiento'; const paradaActual = estadoTren.parado ? tren.paradaCerca(js) : null; textoTren = estadoTren.parado ?": ", 'Elsa, the conductor'); } else if (!estadoTren.parado) cantada = false; const p = estadoTren.proxima; const donde = estadoTren.asiento && estadoTren.asiento.plataforma ? 'On the open platform' : 'In your seat'; const paradaActual = estadoTren.parado ? tren.paradaCerca(js) : null; textoTren = estadoTren.parado ?",
  "); registrar('tronco-mat'); guardar(); return; } const cuanto = o.tipo === 'tronco' ? TRONCOS_MATA : PIEDRA_MATA; sumarMaterial(o.tipo, cuanto); if (o.mata) veg.despejar(o.mata.x, o.mata.z, 0.6, true); if (o.caido) veg.talar(o.arbol); sonido.paso(o.tipo === 'tronco' ? 'madera' : 'tierra', 1); nota(": "); registrar('tronco-mat'); guardar(); return; } const cuanto = o.tipo === 'tronco' ? TRONCOS_MATA : PIEDRA_MATA; sumarMaterial(o.tipo, cuanto); if (o.mata) veg.despejar(o.mata.x, o.mata.z, 0.6, true); if (o.caido) veg.talar(o.arbol); sonido.paso(o.tipo === 'tronco' ? 'madera' : 'tierra', 1); nota(",
  "}; const fuegoPropio = !aviso && !clima.fogata.activa ? cacheFuegoPropio : null; if (fuegoPropio) aviso = { tecla: 'F', texto: fuegoPropio?.plano?.fuegoContenido ? 'Encender la estufa' : 'Encender tu fogón' }; if (!aviso && cacheAcopio) aviso = { tecla: 'E', texto: totalEnMano() > 0 ?": "}; const fuegoPropio = !aviso && !clima.fogata.activa ? cacheFuegoPropio : null; if (fuegoPropio) aviso = { tecla: 'F', texto: fuegoPropio?.plano?.fuegoContenido ? 'Light the stove' : 'Light your fire pit' }; if (!aviso && cacheAcopio) aviso = { tecla: 'E', texto: totalEnMano() > 0 ?",
  ": ''; const calorTxt = habitat.calorActivo ? (habitat.calorPropagado ? ' · calor compartido' : ' · calor activo') : ''; const luzTxt = habitat.luz && noche > 0.35 ? (habitat.luzPropagada >= 0.48 && !habitat.luzLocal ? ' · luz compartida' : ' · luz interior') : ''; estado.textContent =": ": ''; const calorTxt = habitat.calorActivo ? (habitat.calorPropagado ? ' · shared heat' : ' · heat on') : ''; const luzTxt = habitat.luz && noche > 0.35 ? (habitat.luzPropagada >= 0.48 && !habitat.luzLocal ? ' · shared light' : ' · indoor light') : ''; estado.textContent =",
  ": 'La pieza fue retirada'); dibujarPanelObra(); } break; } const r = obras.cancelarMarcada(js.pos, 10, obras.plano?.id); if (!r.ok) nota('Nada que cancelar', r.motivo); else { progreso.obras = obras.obras.map((o) => o.datos); guardar(); sonido.juntar(); nota('Marca retirada',": ": 'The piece was taken away'); dibujarPanelObra(); } break; } const r = obras.cancelarMarcada(js.pos, 10, obras.plano?.id); if (!r.ok) nota('Nothing to cancel', r.motivo); else { progreso.obras = obras.obras.map((o) => o.datos); guardar(); sonido.juntar(); nota('Marker removed',",
  ": 'Rumbo cancelado', chincheActiva ? 'La brújula te la marca hasta que llegues' : 'La brújula vuelve a lo de siempre'); } else { const r = ponerChinche(chinches(), p.x, p.z, nombreLibre(chinches())); if (r.estado === 'llena') { nota('No entran más chinches',": ": 'Heading canceled', chincheActiva ? 'The compass points to it until you get there' : 'The compass goes back to normal'); } else { const r = ponerChinche(chinches(), p.x, p.z, nombreLibre(chinches())); if (r.estado === 'llena') { nota('No room for more pins',",
  ")); const img = el('img', 'polaroid'); img.src = hecho.img; img.alt = d.texto; ficha.appendChild(img); ficha.appendChild(el('p', 'texto', d.texto)); } else { ficha.appendChild(el('p', 'texto', d.texto)); ficha.appendChild(el('p', 'pista',": ")); const img = el('img', 'polaroid'); img.src = hecho.img; img.alt = d.texto; ficha.appendChild(img); ficha.appendChild(el('p', 'texto', d.texto)); } else { ficha.appendChild(el('p', 'texto', d.texto)); ficha.appendChild(el('p', 'pista',",
  "en -1 destraba la revisión: si no, el tocón no cambia de etapa // hasta el día siguiente y el aviso promete algo que no se ve. if (apurado) { apurado.esc = -1; diaRebrote = -1; revisarRebrote(); } nota('Plantaste un renoval', apurado ?": "at -1 unblocks the check: otherwise the stump does not change stage // until the next day and the notice promises something you cannot see. if (apurado) { apurado.esc = -1; diaRebrote = -1; revisarRebrote(); } nota('You planted a sapling', apurado ?",
  ").join('|'); if (firma === firmaBarra && !forzar) return; firmaBarra = firma; barraEl.innerHTML = ''; for (let i = 0; i < 8; i++) { const r = ranuras[i]; const d = document.createElement('div'); d.className =": ").join('|'); if (firma === firmaBarra && !forzar) return; firmaBarra = firma; barraEl.innerHTML = ''; for (let i = 0; i < 8; i++) { const r = ranuras[i]; const d = document.createElement('div'); d.className =",
  ": 'Está vacía. Juntá lo que encuentres por el bosque.'; cosas.forEach((c, i) => { const d = document.createElement('div'); const enLaBarra = progreso.barra ? progreso.barra.indexOf(c.id) : i; d.className =": ": 'It is empty. Pick up whatever you find around the forest.'; cosas.forEach((c, i) => { const d = document.createElement('div'); const enLaBarra = progreso.barra ? progreso.barra.indexOf(c.id) : i; d.className =",
  "); dibujarPanelObra(); } break; case 'KeyX': if (modoObra && obras) { const r = obras.copiarCerca(js.pos, 6); if (!r.ok) { nota('No hay nada para repetir', r.motivo); break; } nota(": "); dibujarPanelObra(); } break; case 'KeyX': if (modoObra && obras) { const r = obras.copiarCerca(js.pos, 6); if (!r.ok) { nota('Nothing to repeat', r.motivo); break; } nota(",
  "); } else if (totalAcopio() > 0) { const partes = []; for (const k of CLAVES_MATERIAL) { const n = a[k] || 0; if (!n) continue; m[k] = (m[k] || 0) + n; a[k] = 0; partes.push(": "); } else if (totalAcopio() > 0) { const partes = []; for (const k of CLAVES_MATERIAL) { const n = a[k] || 0; if (!n) continue; m[k] = (m[k] || 0) + n; a[k] = 0; partes.push(",
  ", pixelRatio: (renderer.getPixelRatio?.() || 1).toFixed(2), limiteFps: String(ajustes.limiteFps), gpu: tarjetaDeVideo(), cuando: new Date().toLocaleString(), escena:": ", pixelRatio: (renderer.getPixelRatio?.() || 1).toFixed(2), limiteFps: String(ajustes.limiteFps), gpu: tarjetaDeVideo(), cuando: new Date().toLocaleString(), escena:",
  "De acá no sale nadie más. Las noches vuelven a ser noches y el valle queda para vos: lo que levantaste sigue en pie y el bosque se va a encargar del resto.": "Nobody else is coming out of there. Nights are nights again and the valley is yours: what you raised is still standing and the forest will take care of the rest.",
  "; if (m.firstChild.nodeType !== 3) m.insertBefore(document.createTextNode(texto), m.firstChild); else m.firstChild.nodeValue = texto; m.style.left =": "; if (m.firstChild.nodeType !== 3) m.insertBefore(document.createTextNode(texto), m.firstChild); else m.firstChild.nodeValue = texto; m.style.left =",
  "; } else { const anden = tren.paradaCerca(js); if (anden) { const q = tren.proximoTrenA(anden); if (tren.parado() && q && q.metros < 12) textoTren =": "; } else { const anden = tren.paradaCerca(js); if (anden) { const q = tren.proximoTrenA(anden); if (tren.parado() && q && q.metros < 12) textoTren =",
  ", 'Lo guardaste en la mochila'); guardar(); } } const horaTexto = (h) => { const hh = Math.floor(h) % 24, mm = Math.floor((h % 1) * 60); return": ", 'Stowed in your pack'); guardar(); } } const horaTexto = (h) => { const hh = Math.floor(h) % 24, mm = Math.floor((h % 1) * 60); return",
  "Cada noche que dormís se escribe acá la página del día: el tiempo que hizo, dónde anduviste, qué anotaste y qué te contaron.": "Every night you sleep, the day's page gets written here: the weather, where you went, what you noted down and what people told you.",
  "Cada noche baja una nave. Levantá tu cabaña, rodeala de defensas, fabricá o encontrá armas y resistí hasta el amanecer.": "Every night a ship comes down. Raise your cabin, ring it with defenses, craft or find weapons and hold out until dawn.",
  "Esto borra la partida de Desafío y empieza desde la primera noche. Tu recorrido Relax no se toca. ¿Querés continuar?": "This erases the Challenge save and starts from the first night. Your Relax run is left untouched. Do you want to continue?",
  ": ' · snap activo') : ' · snap libre'; const edit = obras.editando ? ' · MOVIENDO PIEZA' : ''; const texto = r?.ok ?": ": ' · snap on') : ' · snap off'; const edit = obras.editando ? ' · MOVING PIECE' : ''; const texto = r?.ok ?",
  "Mando conectado: {0}. El stick izquierdo camina, el derecho mira; A salta, X interactúa, R2 ataca, L2 bloquea.": "Controller connected: {0}. Left stick walks, right stick looks; A jumps, X interacts, R2 attacks, L2 blocks.",
  "Andá de día: con el sol arriba se abre el caparazón y quedan a tiro las tres cámaras. De noche está cerrado": "Go by day: with the sun up the shell opens and the three chambers are within reach. At night it's shut",
  "; const marca = document.createElement('i'); marca.textContent = i < hechas ? 'hecha' : falta.length ?": "; const marca = document.createElement('i'); marca.textContent = i < hechas ? 'done' : falta.length ?",
  "Tu equipo no pudo iniciar los gráficos 3D. Probá actualizar los controladores de la placa de video.": "Your machine couldn't start 3D graphics. Try updating your video card drivers.",
  "Salen de un nido enterrado en el valle. Los restos de nave traen señales que te lo van a ubicar": "They come out of a nest buried in the valley. The ship wreckage carries signals that will place it for you",
  ")); else if (conocida && progreso.entradas[e.id].cantidad) b.appendChild(el('span', 'marca',": ")); else if (conocida && progreso.entradas[e.id].cantidad) b.appendChild(el('span', 'marca',",
  "Abrí el mapa (M): el redondel a lápiz marca dónde puede estar. Cada resto de nave lo achica": "Open the map (M): the pencil circle marks where it might be. Each piece of wreckage shrinks it",
  "F1 la abre en cualquier momento: qué hacer, de dónde sale cada recurso y cómo se construye": "F1 opens it any time: what to do, where each resource comes from and how to build",
  "Y aserra un tronco en dos tablas en cualquier lado; en un banco de carpintero rinde cuatro": "Y saws a log into two planks anywhere; at a workbench it yields four",
  "Acercate a plantas y aves y apretá E para anotarlas en el cuaderno; con Z mirás de lejos": "Get close to plants and birds and press E to note them in the field notebook; Z looks from afar",
  "Arrimate a un coihue o una lenga y apretá H tres veces: el árbol cae y da cuatro troncos": "Step up to a coihue or a lenga and press H three times: the tree falls and gives four logs",
  "Todavía no escribiste ninguna página. Se escribe sola cada vez que dormís de noche.": "You haven't written a page yet. It writes itself every time you sleep at night.",
  "El bosque de siempre: caminar, anotar, pescar y construir sin apuro. Nada te ataca.": "The same old forest: walking, noting, fishing and building at your own pace. Nothing attacks you.",
  "Para en cada apeadero unos segundos; se sube con E y se viaja hasta donde quieras": "It stops at every halt for a few seconds; board with E and ride as far as you like",
  "Con L prendés la linterna, y junto al fuego se puede dormir hasta la mañana": "L turns on the flashlight, and by the fire you can sleep until morning",
  "); return; } progreso.chinches = r.lista; chincheActiva = r.chinche; nota(": "); return; } progreso.chinches = r.lista; chincheActiva = r.chinche; nota(",
  "La brújula te lleva. Clic encima para soltarla, clic derecho para sacarla": "The compass takes you there. Click it to let it go, right-click to pull it out",
  "Esto borra el recorrido guardado y empieza desde cero. ¿Querés continuar?": "This erases the saved run and starts from scratch. Do you want to continue?",
  "Con tres alcanza para encender un fuego: apretá F en un lugar despejado": "Three is enough to light a fire: press F somewhere open",
  "No hay ningún mando conectado. Si enchufás uno, el juego lo toma solo.": "No controller connected. Plug one in and the game picks it up on its own.",
  "Esto borra la partida {0} del modo {1}. No se puede deshacer. ¿Seguro?": "This erases save {0} in {1} mode. It can't be undone. Are you sure?",
  "{0} cosas encima. Tocá una para ponerla en la casilla {1} de la barra.": "{0} things on you. Tap one to put it in slot {1} of the bar.",
  "Juntá troncos y piedra con el hacha (H) y armá defensas (O → Defensa)": "Gather logs and stone with the axe (H) and put up defenses (O → Defense)",
  "Primero una lanza. Algo cayó del cielo: buscá la columna de luz verde": "A spear first. Something fell out of the sky: look for the green column of light",
  ").join(' y '); const b = document.createElement('b'); b.textContent =": ").join(' and '); const b = document.createElement('b'); b.textContent =",
  ").join(', '); const b = document.createElement('b'); b.textContent =": ").join(', '); const b = document.createElement('b'); b.textContent =",
  "WASD para volar, Espacio y Shift para subir y bajar, F4 para salir": "WASD to fly, Space and Shift to go up and down, F4 to leave",
  "El bosque es tuyo: andá a donde quieras. +{0} ramitas, +{1} tablas": "The forest is yours: go wherever you like. +{0} twigs, +{1} planks",
  "; const span = document.createElement('span'); span.textContent =": "; const span = document.createElement('span'); span.textContent =",
  "Con J se abre; ahí está lo que anotaste y lo que falta encontrar": "J opens it; there's what you noted and what's still to find",
  "Módulo cercano · acercate a un piso modular para inspeccionarlo": "Module nearby · step onto a modular floor to inspect it",
  "Los peces pican mejor con lluvia, pero los animales se guardan": "Fish bite better in the rain, but the animals stay in",
  "Es un árbol sagrado y centenario: buscá un coihue o una lenga": "It's a sacred, hundred-year-old tree: look for a coihue or a lenga",
  "; const sp = document.createElement('span'); sp.textContent =": "; const sp = document.createElement('span'); sp.textContent =",
  "Un {0}. Además apura el rebrote del tocón de al lado {1} días": "A {0}. It also speeds up the stump next door by {1} days",
  "Despertás en tu base. Reforzá las defensas antes de la noche": "You wake up at your base. Shore up the defenses before nightfall",
  ", 'Amanece en el bosque'); else nota('Dormiste una siesta',": ", 'Dawn in the forest'); else nota('You had a nap',",
  "Llevás {0} tablas. En un banco de carpintero rinde el doble": "You're carrying {0} planks. At a workbench a log yields double",
  "Unos {0} minutos. No toques nada: la cámara se mueve sola": "About {0} minutes. Don't touch anything: the camera moves on its own",
  "Esta no se puede cambiar: es la que te saca de los menús": "This one can't be changed: it's the one that gets you out of menus",
  "Mirá el nuevo lugar · R gira · Y confirma · Supr cancela": "Look at the new spot · R rotates · Y confirms · Del cancels",
  ": ''; const habitat = Number.isFinite(estado.confort) ?": ": ''; const habitat = Number.isFinite(estado.confort) ?",
  "En los bosques de verdad, solo en lugares habilitados": "In real forests, only where it's allowed",
  "; const red = (estado.ambientesConectados || 0) > 1 ?": "; const red = (estado.ambientesConectados || 0) > 1 ?",
  "Clic para lanzar al agua; clic de nuevo cuando pique": "Click to cast into the water; click again when it bites",
  "); } sonido.juntar(); nota('Guardaste en el acopio',": "); } sonido.juntar(); nota('Stored in the supply pile',",
  "{0} de {1} anotaciones, {2} de {3} desafíos de fotos": "{0} of {1} entries, {2} of {3} photo challenges",
  "Está vacía. Juntá lo que encuentres por el bosque.": "It's empty. Pick up whatever you find around the forest.",
  "Puede que el navegador se haya quedado sin espacio": "The browser may have run out of space",
  "Las piezas compatibles se alinean automáticamente": "Matching pieces line up on their own",
  "El fantasma ya no será atraído por otros módulos": "The ghost won't be pulled toward other modules any more",
  "Perdiste los cristales y parte de los materiales": "You lost the crystals and some of the materials",
  "{0} el día {1} a las {2}${reg.cantidad && !pez ?": "{0} on day {1} at {2}${reg.cantidad && !pez ?",
  "Clic o Enter para ponerlo en la casilla elegida": "Click or Enter to put it in the chosen slot",
  "En el almacén se cambia por piñones y frutillas": "At the store you trade piñones and strawberries for it",
  ").join(', '); nota('Todavía no tenés con qué',": ").join(', '); nota('Nothing to make it with yet',",
  "{0}. Podés construir cerca sin cargarlo encima": "{0}. You can build nearby without hauling it around",
  "Bajo cubierta · protegido de la precipitación": "Under cover · sheltered from rain and snow",
  "Traé troncos, tablas o piedra y apretá E acá": "Bring logs, planks or stone and press E here",
  "Se usó la última copia segura del recorrido": "The last safe copy of the run was used",
  "El calor queda contenido dentro del refugio": "The heat stays inside the shelter",
  "Arrimate a un árbol, un tronco o un pedrero": "Step up to a tree, a log or a rock pile",
  "El bosque se recupera solo si le das tiempo": "The forest comes back on its own if you give it time",
  "Salí a caminar. El sendero rodea el lago.": "Go for a walk. The trail goes around the lake.",
  "Los invasores te dejaron fuera de combate": "The invaders knocked you out",
  "Ahora levantalo por etapas con la tecla Y": "Now raise it stage by stage with the Y key",
  "Aserrar en el banco (1 tronco → 4 tablas)": "Saw at the workbench (1 log → 4 planks)",
  "Descansando, {0}. Movete para levantarte.": "Resting, {0}. Move to get up.",
  "La brújula te la marca hasta que llegues": "The compass points to it until you get there",
  "Peligrosa, pero con defensas se resiste.": "Dangerous, but with defenses you hold.",
  "Desafíos cumplidos, ya están en el álbum": "Challenges done, they're in the album now",
  ")); ficha.appendChild(el('p', 'anotado',": ")); ficha.appendChild(el('p', 'anotado',",
  "Un {0}. Va a tardar {1} días en levantar": "A {0}. It'll take {1} days to come up",
  "No se pudo guardar la partida importada": "Couldn't save the imported game",
  "Levantala antes de armarla en otro lado": "Take it down before pitching it somewhere else",
  "Llevás {0}. Con Y los aserrás en tablas": "You're carrying {0}. Y saws them into planks",
  "Quedó elegido con la misma orientación": "Picked with the same orientation",
  "La pieza volvió exactamente a su lugar": "The piece went back exactly where it was",
  "Aserrado a mano: un tronco, dos tablas": "Sawn by hand: one log, two planks",
  "El fogón del refugio o una fogata tuya": "The shelter's fire pit or a campfire of your own",
  "Plantando el bosque andino-patagónico": "Planting the Andean-Patagonian forest",
  "Desafío cumplido, ya está en el álbum": "Challenge done, it's in the album now",
  "Seleccioná el texto y copialo a mano": "Select the text and copy it by hand",
  "Dos kilómetros de anillo sin bajarte": "Two kilometers of loop without getting off",
  "Aserrar a mano (1 tronco → 2 tablas)": "Saw by hand (1 log → 2 planks)",
  "El informe quedó en el portapapeles": "The report is on the clipboard",
  "Se baja en la estación, cuando pare": "You get off at the station, when it stops",
  "Sentate en un tronco para descansar": "Sit on a log to rest",
  "Talá un árbol con H (tres hachazos)": "Fell a tree with H (three axe blows)",
  "Se elige con los números o la rueda": "Pick it with the number keys or the wheel",
  "Bajate cuando pare en una estación": "Get off when it stops at a station",
  "W y S para remar, A y D para girar": "W and S to paddle, A and D to turn",
  "Con tres ya podés hacer una fogata": "With three you can make a campfire",
  "Juntá piñones o frutos de calafate": "Gather piñones or calafate berries",
  "Tendiendo las vías de la trochita": "Laying the trochita's track",
  "Escondiendo un panal en un tronco": "Tucking a hive into a log",
  "La brújula vuelve a lo de siempre": "The compass goes back to normal",
  "El parte quedó en el portapapeles": "The summary is on the clipboard",
  "Bajate cuando pare en la estación": "Get off when it stops at the station",
  "Clavando los tablones del muelle": "Nailing down the dock planks",
  "Avisándole a la gente del puesto": "Letting the folks at the outpost know",
  "Pocos invasores y golpes suaves.": "Few invaders and soft hits.",
  "Hace falta un lugar llano y seco": "You need somewhere flat and dry",
  "Despertando la fauna patagónica": "Waking the Patagonian wildlife",
  "Afinando los sonidos del bosque": "Tuning the sounds of the forest",
  "Historia anotada en el cuaderno": "Story noted in the field notebook",
  "La devolvés al agua con cuidado": "You slip it back into the water",
  "Puede que no haya espacio libre": "There may be no room left",
  "Sacale una foto con P, entonces": "Take a photo of it with P, then",
  "Acercate a la costa o al muelle": "Get close to the shore or the dock",
  "Probá en un lugar más despejado": "Try somewhere more open",
  "Escondiendo frutillas y plumas": "Hiding strawberries and feathers",
  "Tu mejor pieza. Vuelve al agua": "Your best catch. Back into the water",
  "Esta noche bajan los invasores": "The invaders come down tonight",
  "Solo lo que juntaste del suelo": "Only what you picked up off the ground",
  "Volviendo al bosque tranquilo": "Back to the quiet forest",
  "Probá copiarlo a otra carpeta": "Try copying it to another folder",
  "De noche podés dormir adentro": "At night you can sleep inside",
  "No se pudo guardar la partida": "Couldn't save the game",
  "Esa partida es del otro modo": "That save is from the other mode",
  "Sin materiales para devolver": "No materials to give back",
  "Necesitás un fuego encendido": "You need a fire going",
  "Los invasores la derribaron": "The invaders brought it down",
  "Juntá al menos tres ramitas": "Gather at least three twigs",
  "Hay muchas bajo los árboles": "There are plenty under the trees",
  "· calor desde otro ambiente": "· heat from another room",
  "Se puede armar en otro lado": "You can pitch it somewhere else",
  "Leer la bitácora del farero": "Read the lighthouse keeper's log",
  "Pedir algo en la casa de té": "Order something at the tea house",
  "No se pudo armar el bosque:": "Couldn't put the forest together:",
  "¡Árbol talado! +{0} troncos": "Tree down! +{0} logs",
  "Soltando cisnes en el lago": "Letting swans out on the lake",
  "Lo guardaste en la mochila": "Stowed in your pack",
  "No se pudo guardar la foto": "Couldn't save the photo",
  "Una marca menos en el mapa": "One less mark on the map",
  "Más invasores y más duros.": "More invaders, and tougher.",
  "Preparando el modo Desafío": "Getting Challenge mode ready",
  "No se pudo leer el archivo": "Couldn't read the file",
  "La pieza volvió a su lugar": "The piece went back where it was",
  "Acá no hay nada que cortar": "Nothing to cut here",
  "Un árbol volvió a levantar": "A tree is standing again",
  "E o Escape para despedirte": "E or Escape to say goodbye",
  "En tu carpeta de descargas": "In your downloads folder",
  "Llegaste a un lugar nuevo": "You reached a new place",
  "No hay nada para exportar": "There's nothing to export",
  "Otra vuelta en la galería": "Another round on the veranda",
  "Lo comés mirando el fuego": "You eat it watching the fire",
  "Ver qué hay en el almacén": "See what the store has",
  "El perro marca algo cerca": "The dog is marking something nearby",
  "; else if (q) textoTren =": "; else if (q) textoTren =",
  "Cumplido: falta contarlo": "Done: still to be told",
  "No hay nada para repetir": "Nothing to repeat",
  "Buscá suelo firme y seco": "Find firm, dry ground",
  "Lo pusiste en la casilla": "Put in slot",
  "Un tronco, cuatro tablas": "One log, four planks",
  "Quedó marcado en el mapa": "Marked on the map",
  "Ya tenés la carpa armada": "Your tent is already pitched",
  "Todavía no tenés con qué": "Nothing to make it with yet",
  "E para seguir escuchando": "E to keep listening",
  "Un regalo por el encargo": "A gift for the errand",
  "Diste la vuelta completa": "You made it all the way around",
  "Cocinar algo en el fuego": "Cook something on the fire",
  "En la plataforma abierta": "On the open platform",
  "Empezar un Desafío nuevo": "Start a new Challenge",
  "Dejando crecer el pasto": "Letting the grass grow",
  "Pescado por primera vez": "Caught for the first time",
  "Primer día en el bosque": "First day in the forest",
  "Esa tecla ya está usada": "That key is already taken",
  "El fogón está encendido": "The fire pit is lit",
  "Se guarda en la mochila": "It goes in your pack",
  "Se cambia en el almacén": "You trade for it at the store",
  "Sacaste todo del acopio": "You took everything from the supply pile",
  "Se construye de una vez": "Built in one go",
  "Nueva posición guardada": "New position saved",
  "No entran más chinches": "No room for more pins",
  "Esa partida está vacía": "That save is empty",
  ".json,application/json": ".json,application/json",
  "Volvió todo como venía": "Everything's back the way it came",
  "un té con torta galesa": "a tea with Welsh cake",
  "Se desconectó el mando": "Controller disconnected",
  "Guardaste en el acopio": "Stored in the supply pile",
  "Levantando los cerros": "Raising the hills",
  "No podés dormir ahora": "You can't sleep right now",
  "Se terminó el Desafío": "The Challenge is over",
  "Subiste a la trochita": "You got on the trochita",
  "· quedó sólo la marca": "· only the mark is left",
  "La pieza fue retirada": "The piece was taken away",
  "un chocolate caliente": "a hot chocolate",
  "¿Cómo le vas a poner?": "What are you going to call it?",
  "una semilla de coihue": "a coihue seed",
  "frutillas al rescoldo": "strawberries in the embers",
  "Dormir junto al fuego": "Sleep by the fire",
  ", caidas.length > 1 ?": ", caidas.length > 1 ?",
  ": totalAcopio() > 0 ?": ": totalAcopio() > 0 ?",
  "Nuevo en el cuaderno": "New in the field notebook",
  "Amanece en el bosque": "Dawn in the forest",
  "Quedarme en el valle": "Stay in the valley",
  "El tren está andando": "The train is moving",
  "Encendiste la estufa": "You lit the stove",
  "Se te va con el agua": "The water will carry it off",
  "El nido está marcado": "The nest is marked",
  "El pehuén no se tala": "You don't fell a pehuén",
  "El acopio está vacío": "The supply pile is empty",
  "Página siguiente (])": "Next page (])",
  "No tenés qué plantar": "Nothing to plant",
  "Plantaste un renoval": "You planted a sapling",
  "(F para hacer fuego)": "(F to make a fire)",
  ").join(' · '); nota(": ").join(' · '); nota(",
  "Dormiste una siesta": "You had a nap",
  "Fabricá armas con K": "Craft weapons with K",
  "No se pudo importar": "Couldn't import",
  "No hay orilla cerca": "No shore nearby",
  "Encendiste tu fogón": "You lit your fire pit",
  "Seguí dándole con H": "Keep at it with H",
  "Página anterior ([)": "Previous page ([)",
  "Levantaste la carpa": "You took down the tent",
  "Subir a la trochita": "Board the trochita",
  "Dormir en tu puesto": "Sleep at your outpost",
  "; const aberturas =": "; const aberturas =",
  "frutos de calafate": "calafate berries",
  "Asentando el suelo": "Settling the ground",
  "Cápsula estrellada": "Crashed capsule",
  "Ya sabés lo básico": "You know the basics now",
  "no se pudo guardar": "couldn't save",
  "Nada que desmontar": "Nothing to dismantle",
  "Dura toda la noche": "It lasts all night",
  "Hiciste una fogata": "You made a campfire",
  "El cerco se achica": "The circle is closing in",
  "Volviste al cuerpo": "Back in your body",
  "Todavía no fundado": "Not started yet",
  "Encender la estufa": "Light the stove",
  "Dormir en tu catre": "Sleep in your cot",
  "Dormir en la carpa": "Sleep in the tent",
  "· calor compartido": "· shared heat",
  "Empezar el Desafío": "Start the Challenge",
  "Día {0}, {1} · {2}": "Day {0}, {1} · {2}",
  "Pintando el cielo": "Painting the sky",
  "Cuaderno de campo": "Field notebook",
  "No se pudo copiar": "Couldn't copy",
  "apretá una tecla…": "press a key…",
  "Teclas de fábrica": "Default keys",
  "Nada que deshacer": "Nothing to undo",
  "Nada que cancelar": "Nothing to cancel",
  "La guía del juego": "The game's guide",
  "Se largó a llover": "It started raining",
  "Te falta el hacha": "You need an axe",
  "Volvés al teclado": "Back to the keyboard",
  "· fuente de calor": "· heat source",
  "Marcaste el lugar": "You marked the spot",
  "Te falta la manta": "You need the blanket",
  "yerba del almacén": "yerba from the store",
  "dulce de calafate": "calafate jam",
  "Encender tu fogón": "Light your fire pit",
  "Levantar la carpa": "Take down the tent",
  "Encender el fogón": "Light the fire pit",
  "Caña de mosca (Q)": "Fly rod (Q)",
  "${r.dataset.foto}": "${r.dataset.foto}",
  "hojarasca-{0}.png": "hojarasca-{0}.png",
  "Llenando el lago": "Filling the lake",
  "tocón rebrotando": "stump growing back",
  "Subiste al kayak": "You got in the kayak",
  "Para hacer fuego": "For making a fire",
  "Colocación libre": "Free placement",
  "Eso no se suelta": "You can't drop that",
  "No se pudo dejar": "Couldn't leave it",
  "No tenés troncos": "You have no logs",
  "Ya tenés ramitas": "You've got twigs",
  "Se hizo de noche": "Night has fallen",
  "· luz compartida": "· shared light",
  "· MOVIENDO PIEZA": "· MOVING PIECE",
  "piñones tostados": "toasted piñones",
  "Pedile otra cosa": "Ask for something else",
  "Todavía te falta": "You're still short",
  "Fin del invierno": "Late winter",
  "Amanece otra vez": "Dawn again",
  "la última etapa": "the last stage",
  "Acá no se puede": "Can't do it here",
  "Te dejaron algo": "They left you something",
  "Eso ya lo tenés": "You already have that",
  "Bajar del kayak": "Get out of the kayak",
  "Elsa, la guarda": "Elsa, the conductor",
  "Álbum de fotos": "Photo album",
  "Te la contaron": "Told to you",
  "Probá de nuevo": "Try again",
  "Nada que mover": "Nothing to move",
  "Mirá alrededor": "Look around",
  "Talar el árbol": "Fell the tree",
  "· calor activo": "· heat on",
  "· luz interior": "· indoor light",
  "Fin del verano": "Late summer",
  "Subir al kayak": "Get in the kayak",
  "Armar la carpa": "Pitch the tent",
  "Bajar del tren": "Get off the train",
  ").join(' y ')}": ").join(' and ')}",
  "Caña de mosca": "Fly rod",
  "Cámara normal": "Normal camera",
  "· snap activo": "· snap on",
  "En tu asiento": "In your seat",
  "Cámara libre": "Free camera",
  "· snap libre": "· snap off",
  "Acá no crece": "It won't grow here",
  "Acopio vacío": "Supply pile empty",
  "Importar acá": "Import here",
  ", devuelto ?": ", devuelto ?",
  "en el álbum": "in the album",
  "ya lo tenés": "already yours",
  "{0}, {1} cm": "{0}, {1} cm",
  "Todavía no": "Not yet",
  ", r.snap ?": ", r.snap ?",
  "Don Ramón": "Don Ramón",
  "un piñón": "a piñón",
  "piñones": "piñones",
  "Versión": "Version",
  "· catre": "· cot",
  "Ahí no": "Not there",
  "Acá no": "Not here",
  "pehuén": "pehuén",
  "lógica": "logic",
};
