// Tanda I: las etiquetas de una sola palabra (botones, pestañas, categorías y ajustes)
// y un par de textos que viven dentro de plantillas con HTML. El extractor los perdía:
// una palabra sola sin acentos le parecía un identificador de código.
// Lo que NO está acá es a propósito: nombres de especies y de personas, nombres de
// constelaciones, tipografías y códigos de tecla (KeyW, Digit1, ShiftLeft…).
export const EN_I = {
  // ---- botones y navegación
  'Volver': 'Back',
  'Seguir': 'Continue',
  'Cerrar': 'Close',
  'Abrir': 'Open',
  'Salir': 'Quit',
  'Cargar': 'Load',
  'Borrar': 'Delete',
  'Copiar': 'Copy',
  'Copiado': 'Copied',
  'Exportar': 'Export',
  'Reintentar': 'Retry',
  'Ver': 'View',
  'Controles': 'Controls',
  'Ajustes': 'Settings',
  'Teclas': 'Keys',
  'Mando': 'Gamepad',
  'Pausa': 'Pause',

  // ---- pestañas de la guía y secciones del cuaderno
  'Primeros pasos': 'First steps',
  'Especies': 'Species',
  'Lugares': 'Places',
  'Historias': 'Stories',
  'Encargos': 'Errands',
  'Trueque': 'Trading',
  'Diario': 'Journal',
  'Logros': 'Achievements',
  'Combate': 'Combat',
  'Curarte': 'Healing',
  'Trampas': 'Traps',
  'Defensas': 'Defenses',
  'Murallas': 'Walls',
  'Armas': 'Weapons',
  'Estructuras': 'Structures',
  'Fabricar': 'Craft',
  'Taller': 'Workshop',
  'Mochila': 'Pack',
  'Cuaderno': 'Notebook',
  'Mapa': 'Map',
  'Base': 'Base',
  'Apoyo': 'Support',
  'Fauna': 'Wildlife',
  'Cielo': 'Sky',
  'Pescar': 'Fishing',
  'Descansar': 'Rest',
  'Linterna': 'Flashlight',
  'Kayak': 'Kayak',
  'Tramo': 'Section',

  // ---- categorías de construcción
  'Refugios': 'Shelters',
  'Trabajo': 'Work',
  'Exterior': 'Outdoors',
  'Mobiliario': 'Furniture',
  'Defensa': 'Defense',
  'Madera': 'Wood',
  'Entablonado': 'Planking',
  'Horcones': 'Forked posts',
  'Tendal': 'Drying rack',
  'Armarlo': 'Build it',

  // ---- materiales y objetos
  'Troncos': 'Logs',
  'Tablas': 'Planks',
  'Piedra': 'Stone',
  'Piedras': 'Stones',
  'Ramitas': 'Twigs',
  'Frutas': 'Berries',
  'Frutillas': 'Wild strawberries',
  'Cristales': 'Crystals',
  'Boleadoras': 'Bolas',
  'Chinche': 'Pin',
  'Plumas': 'Feathers',
  'Yerba': 'Yerba mate',

  // ---- ajustes
  'Normal': 'Normal',
  'Normales': 'Normal',
  'Tranquila': 'Easy',
  'Implacable': 'Relentless',
  'Dificultad': 'Difficulty',
  'Clima': 'Weather',
  'Cambiante': 'Changing',
  'Lluvioso': 'Rainy',
  'Verano': 'Summer',
  'Invierno': 'Winter',
  'Solas': 'On their own',
  'Baja': 'Low',
  'Media': 'Medium',
  'Alta': 'High',
  'Suave': 'Soft',
  'Reducido': 'Reduced',
  'Invertida': 'Inverted',
  'Grande': 'Large',
  'Enorme': 'Huge',
  'Colores': 'Colors',
  'Efectos': 'Effects',
  'Grano': 'Grain',
  'Guías': 'Guides',
  'Tercios': 'Thirds',
  'Centro': 'Center',
  'Congelado': 'Frozen',
  'En movimiento': 'Running',
  'El mundo': 'The world',
  'Mostrarla': 'Show it',
  'Mostrarlos': 'Show them',
  'Noche': 'Night',
  'Conseguidos': 'Unlocked',
  'Preparando…': 'Getting ready…',

  // ---- teclas con nombre propio en la interfaz
  'Espacio': 'Space',
  'Retroceso': 'Backspace',
  'Saltar': 'Jump',
  'Correr': 'Run',
  'Agacharse': 'Crouch',

  // La lagartija es la única del cuaderno con nombre común en inglés; el resto de las
  // especies (Coihue, Lenga, Chucao, Huemul…) se quedan en castellano a propósito.
  'Lagartija': 'Lizard',

  // ---- marcas del cuaderno
  'Visto': 'Seen',
  'Anotado': 'Noted',
  'Encontrado': 'Found',
  'Escuchado': 'Heard',
  'Llegaste': 'Reached',
  'Cocinado': 'Cooked',
  'Nadando': 'Swimming',

  // ---- textos que estaban dentro de plantillas con HTML
  'Tres partidas para el modo {0}. El otro modo tiene las suyas.': 'Three saves for {0} mode. The other mode has its own.',
  'Exportar deja un archivo que podés llevarte a otra computadora y volver a importar acá.':
    'Export leaves a file you can take to another computer and import back here.',
  'Partida {2}{3}': 'Save {2}{3}',
};
