// 3.6: las voces de la vecindad. Todo lo que dicen los vecinos cuando les regalás algo, los
// invitás, les das una mano, les preguntás cómo andan o te cuentan su historia. Las reglas
// están en vecindad.js; acá sólo hay texto (y es lo que el jugador lee: cada uno con su voz).
//
// Marcas que vecindad.js reemplaza: {cosa} (lo regalado, con artículo: "un frasco de miel"),
// {lacosa} ("la miel"), {nombre} (el nombre del jugador, o el trato cariñoso de cada uno si el
// juego no lo sabe), {lugar} (un edificio o "tu mesa"), {unbicho} ("un huemul"), {pista},
// {amigo}, {quien}, {oficio}, {hechas}, {total}, {hora}, {pronostico}, {cm}, {especie},
// {capitulo}, {obra}, {que}.
//
// Sin nada religioso (pedido del usuario) y sin economía (rechazada): nadie cobra ni vende.
//
// Módulo puro: sólo datos.

// ---------------------------------------------------------------- cada vecino
// encanta: lo que dice al recibir cada una de las tres cosas que le encantan. gusta/noGusta: una
// línea para el resto. ocupado: por qué no puede ir a tomar algo ahora. noToma: si alguna de las
// dos bebidas no le va. acepta: cuando dice que sí. animo: cómo anda (bien, cansado, inquieto,
// con ganas de charlar). historia: tres partes (la 2ª con amigo, la 3ª con compadre).
// sobremesa: lo que charla sentado a la mesa. visita: cuando te visita en el refugio.
// saludoAmigo/saludoCompadre: cómo te saluda cuando ya hay confianza. fauna: cómo cuenta un
// avistaje. regalo: lo que dice la nota del regalo de amistad. pronostico: cómo cuenta el tiempo
// de mañana (si no tiene, usa el genérico).
export const VOCES = {
  jefe: {
    encanta: {
      yerba: '¡Yerba! Con esto el mate del andén aguanta hasta el tren de la tarde. Gracias, de verdad.',
      'pan-casero': 'Pan casero… Con el mate de las seis, antes del primer tren, no hay nada mejor en el mundo.',
      'trucha-ahumada': 'Trucha ahumada. Mi viejo la hacía en un tambor, al lado de la vía. Me trajiste el olor de cuando era chico.',
    },
    gusta: 'Mirá vos, {cosa}. Muy amable. En la estación todo se aprovecha.',
    noGusta: 'Te lo agradezco, pero los hongos no los como ni que me lo pidan por favor. Llevaselos a Herminia, que ella sabe qué hacer.',
    ocupado: 'Ahora no puedo dejar el andén: el tren puede asomar en cualquier momento. Después de las ocho, si querés.',
    acepta: 'Vamos, que la boletería se cuida sola un rato. A {lugar}, entonces.',
    animo: {
      bien: 'Bien, bien. El tren pasó en hora y la campana suena como nueva.',
      cansado: 'Cansado. Me levanté a las cinco a barrer la escarcha del andén.',
      inquieto: 'Con ganas de estirar las piernas. Uno pasa el día mirando la vía y se olvida del resto.',
      charla: 'Con ganas de charlar, la verdad. El andén es lindo, pero las vías no contestan.',
    },
    historia: { titulo: 'La campana del andén', partes: [
      'Mi abuelo fue peón de la vía cuando la trajeron hasta acá. Clavaba durmientes de sol a sol y dormía en una carpa al lado del terraplén.',
      'Yo entré al ferrocarril de cambista, a los diecisiete. Pasé por once estaciones antes de esta, y en todas dejé un mate y un amigo.',
      'La campana del andén es de la primera estación donde trabajé. Cuando la cerraron, la pedí y me la traje en el furgón. Cada vez que la toco me acuerdo de que las estaciones se cierran, pero la gente sigue.',
    ] },
    sobremesa: [
      '¿Sabés cuál es el secreto de un buen jefe de estación? Saber que el tren viene tarde antes que el maquinista.',
      'A la noche, cuando apago el farol del andén, me quedo un rato escuchando. El arroyo, el viento en los álamos y, a veces, un chucao.',
      'Una vez paró el tren por una vaca echada en la vía. Cuarenta minutos. Los pasajeros terminaron sacándole fotos.',
    ],
    visita: [
      'Cerré la boletería un rato y me vine caminando por la vía. Quería ver tu casa de cerca.',
      'Te dejo algo para el mate. Y la próxima venís vos a la estación, que tengo la pava siempre puesta.',
    ],
    saludoAmigo: '¡{nombre}! Justo estaba por tocar la campana. Para vos la toco igual.',
    saludoCompadre: '¡Pero mirá quién llegó! {nombre}, pasá que el andén es tuyo.',
    fauna: 'Desde el andén se ve de todo. Hace poco cruzó {unbicho} cerca de la vía.',
    pronostico: 'El maquinista me avisó por el telégrafo {pronostico}.',
    regalo: 'Ernesto, el jefe de estación, te dejó yerba para el mate',
  },
  nelida: {
    encanta: {
      'frasco-frutilla': '¡Dulce de frutilla! No le digas a Ercilia, que este frasco no va al estante: va a mi alacena.',
      'calafate-seco': 'Calafates secos… Los como de a uno, mientras sumo las libretas. Me endulzan las cuentas.',
      miel: 'Miel de acá, se nota en el color. Esta noche, té con miel y los pies cerca de la estufa. Gracias, corazón.',
    },
    gusta: '{cosa}, qué detalle. Lo guardo abajo del mostrador, que ahí no lo ve nadie.',
    noGusta: '¿Un canto rodado? Ay, no sé qué hacer con una piedra. ¿Para trabar la puerta del depósito, será?',
    ocupado: 'Ahora estoy en el almacén, y si me voy, Ercilia me desconoce. Más tarde, ¿dale?',
    acepta: '¡Me encanta la idea! Me saco el delantal y vamos a {lugar}.',
    animo: {
      bien: 'Bien, contenta. Hoy cuadró todo el inventario a la primera.',
      cansado: 'Molida. Bajé veinte bolsas de harina del tren y todavía me duelen los brazos.',
      inquieto: 'Con ganas de salir un poco. El almacén huele rico, pero una no es una bolsa de yerba.',
      charla: 'Con ganas de charlar, ¡como siempre! Contame algo, que acá adentro no pasa nada.',
    },
    historia: { titulo: 'La que sabe sumar', partes: [
      'Nací en Ñorquinco, un pueblito de la línea donde el tren paraba dos veces por semana. Mi madre tenía una pensión para los ferroviarios.',
      'A los quince ya llevaba los números de la pensión en un cuaderno. Cuando Ercilia decidió mudar el almacén a la aldea, le escribió a mi madre: «Mandame a la nena, que sabe sumar».',
      'Lo que nadie sabe es que guardo un cuaderno con todo lo que se pidió en el almacén desde que llegué. Cuando lo leo, parece la historia del pueblo contada en kilos de yerba y metros de lana.',
    ] },
    sobremesa: [
      'Ercilia dice que yo hablo mucho. Yo digo que ella escucha poco. Nos llevamos bárbaro.',
      'El jueves llega el tren de los encargos. Es mi día preferido: es como abrir regalos que no son míos.',
      'Cuando era chica quería ser telegrafista. Me gustaba el ruidito. Ahora me conformo con la campanita de la puerta.',
    ],
    visita: [
      '¡Qué lindo lugar te armaste! Ercilia me dio la tarde libre y dije: voy a ver dónde vive el que tanto pasa por el almacén.',
      'Te traje un poquito de harina. No le digas a nadie, que después todos quieren visita.',
    ],
    saludoAmigo: '¡{nombre}! Pasá, que te estaba esperando para contarte un chisme.',
    saludoCompadre: '¡{nombre}, por fin! Sentate en la bolsa de papas, que es la más cómoda.',
    fauna: 'Barriendo la vereda vi pasar {unbicho}. ¡Casi me caigo de la sorpresa!',
    regalo: 'Nélida te dejó harina, de la que guarda abajo del mostrador',
  },
  abuela: {
    encanta: {
      calafate: 'Calafate… Con esto hago el dulce que me enseñó mi madre. Y ya sabés lo que dicen: el que come calafate, vuelve.',
      'calafate-seco': 'Calafates secos, como los que colgaba mi abuela en el alero. Para el invierno, para el mate, para acordarse.',
      'frasco-frutilla': 'Un frasco de dulce… Me lo como a cucharaditas, despacio, que a mi edad lo rico se estira.',
    },
    gusta: 'Gracias, tesoro. {Cosa} siempre viene bien en esta casa.',
    noGusta: 'Ay, no, la trucha cruda no. El olor a pescado me queda en la casa una semana. Llevásela a Aurelio, que la sabe tratar.',
    ocupado: 'Ahora no, tesoro, que estoy con lo mío y prometí no faltar. Después, con gusto.',
    acepta: 'Bueno, pero vamos despacio, que estas rodillas ya caminaron mucho. A {lugar}.',
    animo: {
      bien: 'Bien, tesoro. Dormí de un tirón y soñé con mi madre haciendo dulce.',
      cansado: 'Cansada. A mi edad, el día es más largo que las piernas.',
      inquieto: 'Con ganas de salir al sol un rato. Las paredes de casa ya me saben de memoria.',
      charla: 'Con ganas de que alguien me escuche. Tengo un cuento nuevo… bueno, viejo, pero nuevo para vos.',
    },
    historia: { titulo: 'Los cuentos que no se pierden', partes: [
      'Yo nací en este valle cuando todavía no había vía. Mi padre era baqueano: llevaba gente y mulas al otro lado de la cordillera.',
      'Me casé con Isidro, un peón de la cuadrilla del ferrocarril. Criamos cuatro hijos en una casa de dos piezas. Hoy viven lejos y me escriben por el tren.',
      'La leyenda de los duendes me la contó mi abuela, y a ella la suya. Yo la cuento los domingos para que no se pierda. Un pueblo sin cuentos es como una casa sin estufa: se puede vivir, pero no dan ganas.',
    ] },
    sobremesa: [
      'Antes, cuando nevaba fuerte, nos juntábamos todos en la casa más grande. Se contaban cuentos hasta que se acababa la leña.',
      'Mi madre decía que el mate cebado por otro es más rico. Tenía razón: este está mejor que el mío.',
      'Los duendes, si existen, deben estar contentos con este pueblo. Hay humo en las chimeneas y chicos en la plaza.',
    ],
    visita: [
      'Me trajo Mario en el carro hasta la mitad del camino, y el resto lo hice a pie. Quería conocer tu casa antes de que se me acaben las ganas de caminar.',
      'Te dejé unos calafates secos. Comelos despacio, mirando el fuego, y pensá en alguien que quieras.',
    ],
    saludoAmigo: '{nombre}, vení, sentate. Te estaba guardando el lugar.',
    saludoCompadre: '¡Ay, {nombre}! Vos sos como de la familia ya. Dame un abrazo.',
    fauna: 'El otro día, desde la ventana, vi {unbicho}. A mi edad uno aprende a mirar quieto.',
    pronostico: 'Me duele la rodilla izquierda: eso quiere decir {pronostico}. Nunca falla.',
    regalo: 'La abuela Herminia te dejó calafates secos de su alero',
  },
  padre: {
    encanta: {
      'trucha-ahumada': '¡Trucha ahumada! Esto con pan y un poco de sal, sentado en el tronco del patio, es mi idea de un domingo.',
      empanadas: 'Empanadas… Me las llevo al monte mañana. Al mediodía, con el hacha apoyada y el sol de frente, son un banquete.',
      yerba: 'Yerba, de la buena. El mate del hachero no se negocia: es lo primero y lo último del día. Gracias, compañero.',
    },
    gusta: 'Gracias. {Cosa} en casa de los Jones siempre tiene destino.',
    noGusta: '¿Un tronco? Te lo agradezco, pero leña me sobra: la corto yo todo el día. Llevásela a Herminia, que ella no puede hachar.',
    ocupado: 'Ahora estoy con la leña y si paro se me enfría el brazo. A la tardecita, ¿dale?',
    acepta: 'Dale. Dejo el hacha clavada en el tronco y vamos a {lugar}.',
    animo: {
      bien: 'Bien, firme. Salieron dos carradas de leña hoy.',
      cansado: 'Medio rendido. El quebracho no, pero la lenga verde es dura de partir.',
      inquieto: 'Con ganas de hacer algo distinto. Siempre el mismo tronco cansa.',
      charla: 'Con ganas de charlar con alguien que no sea un árbol. Ellos no contestan.',
    },
    historia: { titulo: 'El hacha y los chicos', partes: [
      'Aprendí a hachar con mi viejo, en un obraje del lago. A los doce ya sabía dónde iba a caer un árbol antes de que cayera.',
      'A la Gladys la conocí en un baile de la estación, en las fiestas de la nieve. Bailaba mejor que yo, y eso que yo practicaba con el hacha.',
      'Mi sueño es que Nahuel y Lucía estudien. Que el hacha la agarren si quieren, no porque no les quede otra. Por eso le pongo tantas ganas a cada obra: quiero que tengan escuela.',
    ] },
    sobremesa: [
      'Las chapas se clavan con el viento a favor. Te lo digo de nuevo porque es lo único que sé de memoria.',
      'Nahuel quiere ser maquinista. Yo le digo que primero aprenda a hachar, por las dudas. Él me mira como si le hablara en galés.',
      'La mejor leña es la que se corta en otoño y se quema en invierno. Ni antes ni después.',
    ],
    visita: [
      'Pasaba con el carro y vi el humo de tu chimenea. Me dije: este también trabaja de sol a sol.',
      'Te dejé unos troncos secos al lado de la puerta. Ya están partidos, para que no te gastes el brazo.',
    ],
    saludoAmigo: '¡Eh, {nombre}! ¿Vamos a levantar algo hoy o qué?',
    saludoCompadre: '¡{nombre}, compañero! Si necesitás una mano, ya sabés: acá hay dos.',
    fauna: 'Hachando en el borde del bosque vi {unbicho}. Me quedé quieto hasta que se fue.',
    regalo: 'Mario Jones te dejó troncos partidos al lado de la puerta',
  },
  madre: {
    encanta: {
      frutilla: '¡Frutillas! Con estas hago un frasco para los chicos y otro para vos. No me digas que no.',
      calafate: 'Calafate… Mi abuela de Cushamen lo juntaba en la meseta. Esta noche hago dulce y la casa va a oler a ella.',
      miel: 'Miel de verdad. Con esto le endulzo el té a Lucía cuando tose. Gracias, de corazón.',
    },
    gusta: '{cosa}, qué bien. En casa con dos chicos nada sobra.',
    noGusta: '¿Una pluma? Ay, gracias, pero en esta casa las plumas terminan en la sopa o en el pelo de Nahuel. Dásela a Lucía, que las colecciona.',
    ocupado: 'Ahora estoy con el dulce en el fuego y si lo dejo se me quema. Más tarde, ¿sí?',
    acepta: 'Bueno, un ratito. Le aviso a Mario que mire a los chicos y vamos a {lugar}.',
    animo: {
      bien: 'Bien, contenta. Los chicos se portaron bien todo el día… casi todo.',
      cansado: 'Cansada. Dos chicos, una casa y una olla de dulce no dan respiro.',
      inquieto: 'Con ganas de salir a juntar frutos. Me encierro con las ollas y extraño el campo.',
      charla: 'Con ganas de hablar con un grande, la verdad. Todo el día escucho de duendes y trenes.',
    },
    historia: { titulo: 'El verano en un frasco', partes: [
      'Mi familia es de Cushamen, de la meseta. Allá no hay árboles como acá: hay viento, coirón y un cielo enorme.',
      'Mi abuela me enseñó a hacer dulce con lo que diera el campo: calafate, rosa mosqueta, frutillas silvestres. Decía que el dulce es el verano guardado en un frasco.',
      'Cuando llegué a la cordillera lloré una semana: los árboles me tapaban el cielo. Ahora no podría vivir sin ellos. Pero cada tanto subo al andén nomás para ver lejos.',
    ] },
    sobremesa: [
      'Lucía lee todo lo que encuentra. Ayer me leyó la etiqueta del kerosene en voz alta, con entonación y todo.',
      'El secreto del dulce es no apurarse. Fuego bajo y cuchara de madera. Lo demás es paciencia.',
      'A veces extraño la meseta. Allá el viento te habla; acá el viento se pierde entre los árboles.',
    ],
    visita: [
      'Dejé a los chicos con Mario y me vine sola. ¡Qué silencio hay en tu casa! Lo disfruto un rato.',
      'Te traje un frasco de dulce. Es de frutilla, lo hice la semana pasada.',
    ],
    saludoAmigo: '¡Hola, {nombre}! ¿Querés probar lo que tengo en la olla?',
    saludoCompadre: '{nombre}, qué alegría. Los chicos preguntan por vos todos los días.',
    fauna: 'Juntando rosa mosqueta al costado de la vía vi {unbicho}. Los chicos no me creyeron.',
    regalo: 'Gladys te dejó un frasco de dulce de frutilla',
  },
  nene: {
    encanta: {
      frutilla: '¡Frutillas! ¿Son todas para mí? Bueno, le doy una a Lucía. La más chiquita.',
      miel: '¡Miel! La voy a comer con el dedo cuando mamá no mire. No le digas, eh.',
      canto: '¡Un canto rodado! Es re redondo. Lo voy a poner en mi caja de tesoros, al lado de la piedra que parece un duende.',
    },
    gusta: '¡Gracias! {Cosa}… ¡qué bueno!',
    noGusta: '¿Habas? ¡No! Las habas son lo peor del mundo. Dáselas a papá, que se come todo.',
    ocupado: 'No puedo, estoy en la escuela… bueno, tengo que estar. ¡Después sí!',
    noToma: { mate: '¿Mate? Mamá dice que el mate es para grandes. ¡Pero té con leche sí!' },
    acepta: '¡Sí! ¿Puedo pedir torta? ¡Vamos a {lugar}!',
    animo: {
      bien: '¡Bien! Hoy encontré un escarabajo verde brillante.',
      cansado: 'Cansado… Corrí toda la tarde atrás de la liebre y no la alcancé.',
      inquieto: '¡Quiero salir! ¿Vamos a buscar duendes?',
      charla: '¿Querés saber algo? ¡Sé todos los nombres de las locomotoras!',
    },
    historia: { titulo: 'La caja de tesoros', partes: [
      'Me llamo Nahuel, que quiere decir tigre. ¡Pero acá no hay tigres! Hay pumas, dice papá, pero nunca los vi.',
      'Tengo una caja de lata con mis tesoros: cantos rodados, una pluma de cachaña, un tornillo del tren y una piedra que parece un duende. No se la muestro a cualquiera.',
      'Una vez me perdí en el bosque, cerca del arroyo. No lloré… bueno, un poquito. Seguí el ruido del agua, llegué a la vía y la vía me trajo a casa. Desde ese día sé que el agua y la vía siempre te llevan a algún lado.',
    ] },
    sobremesa: [
      '¿Sabías que la trochita es la más angosta del mundo? Bueno, de acá seguro.',
      'Lucía dice que los duendes no existen. Pero entonces, ¿quién se come la galleta que deja el jefe en el andén?',
      'Cuando sea grande voy a manejar el tren y te voy a dejar tocar el silbato. Una vez sola, eh.',
    ],
    visita: [
      '¡Vine caminando por la vía con papá! ¿Esta es tu casa? ¡Es enorme! ¿Tenés duendes?',
      'Te traje dos cantos rodados de los más redondos. Son de mi colección, así que cuidalos.',
    ],
    saludoAmigo: '¡{nombre}! ¡{nombre}! ¿Viste lo que encontré?',
    saludoCompadre: '¡{nombre}! Sos mi mejor amigo grande. Bueno, después del maquinista.',
    fauna: '¡Vi {unbicho}! ¡De verdad! Lucía dice que miento, pero yo lo vi.',
    regalo: 'Nahuel te dejó dos cantos rodados de su caja de tesoros',
  },
  nena: {
    encanta: {
      frutilla: '¡Frutillas! Mi fruta preferida en todo el universo. Gracias, gracias, gracias.',
      miel: '¡Miel! ¿Sabías que una abeja hace una cucharadita en toda su vida? Lo leí en la biblioteca. Entonces esto es de un montón de abejas.',
      pluma: '¡Una pluma de cachaña! La voy a pegar en mi cuaderno, al lado del dibujo del pájaro. Va a quedar perfecto.',
    },
    gusta: '¡Gracias! {Cosa} me gusta mucho.',
    noGusta: '¿Papas? Pero… ¿una papa es un regalo? Bueno, gracias igual. Se la doy a mamá.',
    ocupado: 'Ahora no puedo, estoy en clase. ¡Delia dice que la puntualidad es importante!',
    noToma: { mate: 'Yo no tomo mate todavía, me quema la lengua. ¿No podemos ir a tomar té?' },
    acepta: '¡Sí! Llevo mi cuaderno, por si vemos algo para anotar. Vamos a {lugar}.',
    animo: {
      bien: '¡Bien! Terminé de leer un libro entero. Con capítulos y todo.',
      cansado: 'Cansada. Me quedé leyendo con el farol hasta tarde. No le digas a mamá.',
      inquieto: '¡Quiero salir a buscar cosas para mi cuaderno!',
      charla: '¿Querés que te lea algo? Leo bastante rápido, ya vas a ver.',
    },
    historia: { titulo: 'La primera palabra larga', partes: [
      'Aprendí a leer sola, con los carteles del tren: «Prohibido asomarse». Fue mi primera palabra larga.',
      'Leo todo lo que hay en la biblioteca. Bueno, todo no: los libros de hojas finitas son de grandes. Pero igual los miro.',
      'Cuando sea grande quiero ser maestra, o escribir un libro con todas las leyendas de la abuela Herminia. Así nadie se las olvida nunca.',
    ] },
    sobremesa: [
      '¿Sabías que el huemul está en el escudo de Chile? Lo leí. Y que acá quedan muy poquitos.',
      'Nahuel dice que vio un duende. Era un hongo colorado. Pero no le digas que te conté.',
      'La abuela dice que las puertitas en las raíces no se abren: se golpea. Yo golpeé una vez. No contestó nadie, pero tampoco me animé a abrir.',
    ],
    visita: [
      '¡Hola! Vine a anotar tu casa en mi cuaderno. Sección «lugares». ¿Me dejás dibujarla?',
      'Te traje una pluma de cachaña. Tengo dos, así que esta es para vos.',
    ],
    saludoAmigo: '¡Hola, {nombre}! ¿Qué anotaste hoy?',
    saludoCompadre: '¡{nombre}! Te escribí una página entera en mi cuaderno. ¿Querés leerla?',
    fauna: 'Anoté {unbicho} en mi cuaderno. ¡Lo vi yo sola!',
    regalo: 'Lucía te dejó una pluma de cachaña para tu cuaderno',
  },
  galesa: {
    encanta: {
      miel: 'Miel… Diolch yn fawr! Muchas gracias. Con esto el bara brith sale como el de mi nain, mi abuela.',
      'frasco-frutilla': 'Dulce de frutilla para los scones de la tarde. Los clientes de la galería te lo van a agradecer sin saberlo.',
      harina: 'Harina, y de la buena. La torta negra pide harina y paciencia: la paciencia la pongo yo.',
    },
    gusta: 'Qué amable. {Cosa} siempre tiene lugar en la cocina de la casa de té.',
    noGusta: 'Ay, la yerba… Te agradezco, cariad, pero en esta casa se toma té. El mate se lo dejo a Ercilia.',
    ocupado: 'Estoy atendiendo la galería, cariad. Las teteras no se sirven solas.',
    noToma: { mate: 'El mate no me cae bien, perdoname. Si es té, voy encantada… aunque en mi casa sirvo yo.' },
    acepta: 'Qué lindo que te acuerdes de mí. Vamos a {lugar}.',
    animo: {
      bien: 'Bien, cariad. La torta negra salió perfecta y la galería estuvo llena.',
      cansado: 'Cansada. Amasé desde las seis y todavía tengo harina hasta en las cejas.',
      inquieto: 'Con ganas de salir a caminar. La cocina es calentita, pero una extraña el viento.',
      charla: 'Con ganas de charlar. En la galería todos hablan, pero nadie me pregunta a mí.',
    },
    historia: { titulo: 'La tetera del Mimosa', partes: [
      'Mi tatarabuela bajó del Mimosa en Puerto Madryn con un baúl, una tetera y la receta de la torta negra. La tetera todavía la uso.',
      'Crecí en Trevelin, entre chacras de trigo y molinos. En casa se hablaba galés en la mesa y castellano en la calle, y yo mezclaba los dos sin darme cuenta.',
      'Abrí la casa de té porque extrañaba las tardes de mi nain: la mesa larga, la torta, la gente que llegaba sin avisar. Cuando alguien entra empapado y se sienta junto a la estufa, siento que ella está ahí, en la cocina, contenta.',
    ] },
    sobremesa: [
      'La torta negra mejora con los días. Como los amigos, dice mi madre.',
      'En Trevelin, cuando nevaba, la casa de té era el único lugar con luz. Venía todo el pueblo, y nadie se iba hasta que paraba.',
      'Marta, la enfermera, también es Williams de las de Gales. Somos primas lejanas, creo. Allá todos somos primos lejanos.',
    ],
    visita: [
      'Cerré la galería un rato y vine a conocer tu casa. ¡Qué bien huele! ¿Es leña de lenga?',
      'Te traje pan de la casa de té. Comelo con manteca, que así lo comía mi nain.',
    ],
    saludoAmigo: 'Prynhawn da, {nombre}! ¿Ves? Ya te saludo en galés.',
    saludoCompadre: '¡{nombre}, cariad! Te guardé la mesa de la ventana.',
    fauna: 'Desde la galería vi {unbicho}, ahí, a la vista de todos. Los clientes dejaron de comer.',
    regalo: 'Ceinwen te dejó pan de la casa de té',
  },
  ercilia: {
    encanta: {
      'frasco-frutilla': 'Dulce de frutilla… Este no va al estante, va a mi mesa. Gracias, querido.',
      miel: 'Miel de la buena. Mi abuela decía que la miel no se vence nunca. Esta no va a durar tanto, te aviso.',
      empanadas: '¡Empanadas! Hoy no cocino. Gracias, que me salvaste la cena.',
    },
    gusta: '{cosa}, qué atento. En el almacén nada se desperdicia.',
    noGusta: '¿Un tronco? Ay, querido, leña me trae Mario todas las semanas. Guardalo para tu estufa.',
    ocupado: 'Ahora estoy con el almacén abierto y Nélida sola no da abasto. Después, ¿sí?',
    acepta: 'Vamos, que Nélida se las arregla. A {lugar}, entonces.',
    animo: {
      bien: 'Bien, bien. Llegó el tren con todo lo encargado y no faltó nada.',
      cansado: 'Cansada. Cuarenta años de mostrador se sienten en la espalda.',
      inquieto: 'Con ganas de salir un rato. Una se olvida de que afuera hay cordillera.',
      charla: 'Con ganas de charlar. Contame cómo anda el valle, que desde acá no se ve.',
    },
    historia: { titulo: 'Tres generaciones de mostrador', partes: [
      'Atiendo el almacén desde los diecinueve. Lo heredé de mi tía, que lo había heredado de su madre. Somos tres generaciones de mostrador.',
      'Cuando decidimos mudar el almacén a la aldea, lloré cargando el último cajón al tren. Cuarenta años en el mismo lugar no se despegan fácil.',
      'Pero a la primera semana ya tenía caras nuevas, a Nélida conmigo y a Ceinwen enfrente con la pava. Aprendí que un almacén no es un edificio: es la gente que entra a charlar.',
    ] },
    sobremesa: [
      'Antes el almacén estaba solo en el medio del valle. Ahora tengo vecinos a los dos lados. Me costó acostumbrarme al ruido.',
      'Nélida habla más que la radio. Pero suma rápido, y eso vale oro.',
      'Mi abuela le fiaba a todo el valle con una libreta. Yo todavía la tengo guardada, con todos los apellidos que quedan por acá.',
    ],
    visita: [
      'Cerré un rato el almacén. Si alguien necesita algo, que espere: también una tiene derecho a visitar.',
      'Te traje harina. Con un huevo y un fuego, torta frita. No hay nada más fácil.',
    ],
    saludoAmigo: '¡{nombre}! Pasá, que te guardé lo último que llegó en el tren.',
    saludoCompadre: '{nombre}, vos ya sos de la casa. Servite el mate vos mismo.',
    fauna: 'Uno que vino a hacer los mandados me contó que anda {unbicho} cerca del arroyo.',
    regalo: 'Ercilia te dejó harina del almacén',
  },
  carpintero: {
    encanta: {
      yerba: 'Yerba. Con un mate al lado del banco, la madera se deja trabajar mejor. No me preguntes por qué.',
      empanadas: 'Empanadas, ¡qué lujo! Las caliento en la estufa del taller, arriba de una tabla de lenga.',
      'pan-casero': 'Pan casero… Me lo como con la viruta todavía pegada en las manos. Gracias, vecino.',
    },
    gusta: '{cosa}. Gracias, no me lo esperaba.',
    noGusta: '¿Piedras? Mirá, las piedras y los formones no se llevan. Dáselas a Anselmo, que él sí las aprovecha.',
    ocupado: 'Tengo una tabla a medio cepillar. Si la dejo, se tuerce. Después de las seis estoy libre.',
    acepta: 'Dale. Me sacudo el aserrín y vamos a {lugar}.',
    animo: {
      bien: 'Bien. La lenga de hoy salió derechita, sin un nudo.',
      cansado: 'Cansado. Todo el día con el serrucho, tengo el brazo de madera.',
      inquieto: 'Con ganas de caminar un poco. El taller huele rico, pero encierra.',
      charla: 'Con ganas de charlar, para variar. Las tablas son buenas compañeras, pero calladas.',
    },
    historia: { titulo: 'El formón de mi viejo', partes: [
      'Mi viejo era carpintero de ribera en Viedma: hacía botes. Yo aprendí con él a medir dos veces y cortar una.',
      'Me vine a la cordillera por la madera. Allá abajo no hay lenga ni ciprés; acá hay de sobra, si se la sabe cuidar.',
      'Tengo guardado un formón de mi viejo, con el mango gastado por su mano. Lo uso sólo para los trabajos lindos. Cuando lo agarro, siento que la mano es de los dos.',
    ] },
    sobremesa: [
      'La madera tiene memoria: si la secás apurada, después se acuerda y se tuerce.',
      'Mario hacha, yo corto y Anselmo clava. Entre los tres levantamos cualquier cosa.',
      'Un buen banco de carpintero dura más que el carpintero. El mío era de mi abuelo.',
    ],
    visita: [
      'Vine a mirar cómo te quedaron las uniones de la casa. Perdoná la costumbre: no puedo entrar a un lugar sin mirar las vigas.',
      'Te dejé unas tablas cepilladas al lado de la puerta. Me sobraban, de verdad.',
    ],
    saludoAmigo: '¡{nombre}! Pasá, que justo tengo la pava en la estufa.',
    saludoCompadre: '{nombre}, compadre. Para vos el banco siempre está libre.',
    fauna: 'Buscando madera caída vi {unbicho}. Me quedé quieto como un poste.',
    regalo: 'Tito, el carpintero, te dejó tablas cepilladas',
  },
  panadera: {
    encanta: {
      harina: 'Harina… Esto para mí es como darle agua al que tiene sed. Mañana a las siete hay pan con tu nombre.',
      huevo: 'Huevos frescos. Con esto la masa de las tortas fritas sube como debe. Gracias, m\'hijo.',
      miel: 'Miel. Le pongo una cucharada a la masa dulce y la panadería huele a verano. Gracias.',
    },
    gusta: '{cosa}. Te lo agradezco, de verdad.',
    noGusta: '¿Pan? ¿A la panadera? Ay, gracias, pero pan me sobra hasta en los sueños. Comételo vos, que te hace falta.',
    ocupado: 'Tengo la tanda en el horno. Si me voy, se quema y mañana no hay pan. Más tarde, sí.',
    acepta: 'Bueno, que la masa leve sola un rato. Vamos a {lugar}.',
    animo: {
      bien: 'Bien. La masa madre está contenta, y si ella está contenta, yo también.',
      cansado: 'Cansada. Me levanto a las cuatro todos los días y hoy se nota.',
      inquieto: 'Con ganas de salir un rato. Una se pasa el día mirando el horno.',
      charla: 'Con ganas de charlar. Contame algo, que acá la masa no habla.',
    },
    historia: { titulo: 'La masa madre', partes: [
      'Soy de Chos Malal. Mi abuela tenía un horno de barro en el patio y los domingos cocinaba para medio barrio.',
      'La masa madre que traje tiene más de treinta años. La alimento todos los días, como a una mascota. Si se muere, me muero yo un poquito.',
      'Lo que más me gusta no es hacer pan: es ver la cara de la gente que entra a las siete, todavía de noche. Esa cara de «ah, qué olor». Por eso me levanto a las cuatro.',
    ] },
    sobremesa: [
      'Con lluvia el pan sale distinto. Más pesado, como la gente.',
      'Gladys me trae dulce y yo le doy pan. Así funciona un pueblo, ¿no?',
      'Ceinwen me quiere enseñar a hacer bara brith. Yo le quiero enseñar a hacer tortas fritas. Vamos a terminar las dos gordas.',
    ],
    visita: [
      'Cerré la panadería después de la tanda de la tarde y me vine. Huele rico tu casa, pero le falta pan.',
      'Te dejé pan casero de la última tanda. Todavía está tibio.',
    ],
    saludoAmigo: '¡{nombre}! Justo sale una tanda. Llevate uno, que está calentito.',
    saludoCompadre: '{nombre}, vos sos de los que entran por la puerta de atrás. Pasá.',
    fauna: 'A las cuatro de la mañana, prendiendo el horno, vi {unbicho} en el patio. A esa hora el pueblo es de los animales.',
    regalo: 'Rosa, la panadera, te dejó pan casero de la última tanda',
  },
  herrero: {
    encanta: {
      'trucha-ahumada': 'Trucha ahumada. Esto es lo único que me hace dejar el yunque. Gracias, en serio.',
      empanadas: 'Empanadas. Las caliento en la fragua, sobre una chapa. Quedan como las de mi madre, pero con olor a carbón.',
      yerba: 'Yerba. El mate de la fragua es el más caliente del pueblo, te lo garantizo.',
    },
    gusta: '{cosa}. Te lo agradezco.',
    noGusta: '¿Frutillas? No, lo dulce no es lo mío. Llevaselas a los chicos de Jones, que te van a querer más que yo.',
    ocupado: 'Tengo el hierro al rojo. Si lo dejo, se enfría y hay que empezar de nuevo. Más tarde.',
    acepta: 'Bueno. Tapo la fragua y vamos a {lugar}.',
    animo: {
      bien: 'Bien. El hierro se dejó trabajar.',
      cansado: 'Cansado. Diez horas de martillo se sienten en el hombro.',
      inquieto: 'Con ganas de aire. La fragua calienta hasta las ideas.',
      charla: 'Con ganas de charlar, aunque no parezca. Soy callado, pero escucho.',
    },
    historia: { titulo: 'El eco del yunque', partes: [
      'Mi abuelo herraba caballos en las estancias de la línea sur. Yo, de chico, le tiraba del fuelle.',
      'Trabajé años en los talleres del ferrocarril, en Jacobacci. Arreglaba bielas, ejes, lo que viniera. Una locomotora es un animal grande, pero también se compone.',
      'Me vine porque me cansé del ruido del taller. Acá golpeo el yunque y el valle me contesta con el eco. Es como trabajar acompañado.',
    ] },
    sobremesa: [
      'El acero tiene que sufrir para servir: fuego, golpe, agua. Como uno.',
      'Tito dice que la madera es más noble que el hierro. Yo le digo que sin mis clavos, su madera no se sostiene. Discutimos todos los días.',
      'Una herradura vieja colgada en la puerta. Mi abuelo decía que trae suerte. Yo digo que trae recuerdos, que es parecido.',
    ],
    visita: [
      'Vine a ver cómo cuidás el hacha. Mostrámela… Bien. Se nota que la limpiás.',
      'Te dejé unas piedras de las buenas, para el cimiento de lo que levantes.',
    ],
    saludoAmigo: '{nombre}. Pasá, que el fuego está lindo.',
    saludoCompadre: '{nombre}. Para vos, la fragua siempre está prendida.',
    fauna: 'Saliendo a buscar carbón vi {unbicho}. Hacía tiempo que no veía uno.',
    regalo: 'Anselmo, el herrero, te dejó piedras para tus cimientos',
  },
  pescador: {
    encanta: {
      'pan-casero': 'Pan casero. En el bote, al amanecer, con el agua quieta… Es lo único que me falta allá arriba.',
      yerba: 'Yerba. Me la llevo al bote: el mate en el lago sabe distinto.',
      papa: 'Papas. Con trucha al rescoldo, papas. Sin papas, la trucha está sola.',
    },
    gusta: '{cosa}. Gracias, vecino.',
    noGusta: '¿Truchas? ¡Pero si las saco yo! Te lo agradezco, pero es como regalarle agua al lago.',
    ocupado: 'Ahora estoy con las redes, que se enredan si las dejo. Al atardecer, ¿te parece?',
    noToma: { te: '¿Té? No, vecino, yo soy de mate. El té es para cuando uno está enfermo.' },
    acepta: 'Dale, vamos. Las redes esperan. A {lugar}.',
    animo: {
      bien: 'Bien. El lago estuvo bueno hoy.',
      cansado: 'Cansado. Salí a las cinco y el viento me hizo remar el doble.',
      inquieto: 'Con ganas de estar en el agua. En tierra me siento raro.',
      charla: 'Con ganas de charlar. En el bote uno habla solo, y ya me conozco todas mis historias.',
    },
    historia: { titulo: 'La deuda con el lago', partes: [
      'Me crié a orillas del Nahuel Huapi, en un ranchito de chapa. Mi padre pescaba con red y mi madre ahumaba.',
      'Nicanor y yo pescamos juntos de jóvenes. Él se quedó en el valle y yo me fui al sur, al Futalaufquen. Nos escribíamos por el tren.',
      'La noche que se me dio vuelta el bote en el Futalaufquen, nadé hasta la costa con la red enganchada en la pierna. Desde entonces devuelvo una de cada tres que saco. Le debo esa al lago.',
    ] },
    sobremesa: [
      'Las marrones grandes son viejas y desconfiadas. Hay que ser más paciente que ellas.',
      'Con Nicanor nos juntamos los domingos a mirar el agua. A veces no hablamos en toda la mañana, y es la mejor charla de la semana.',
      'El lago de mañana temprano y el de la tarde no son el mismo lago. Uno aprende a conocerlos a los dos.',
    ],
    visita: [
      'Vine por el sendero de la costa. Desde el agua se ve tu humo: ya sos parte del paisaje.',
      'Te dejé dos truchas frescas. Ahumalas o comelas hoy, pero no las dejes al sol.',
    ],
    saludoAmigo: '{nombre}. El lago estuvo bueno hoy. ¿Y vos?',
    saludoCompadre: '¡{nombre}! Mañana temprano salimos juntos, si querés. El bote tiene lugar.',
    fauna: 'Desde el bote vi {unbicho} en la orilla. El agua deja ver cosas que la tierra esconde.',
    pronostico: 'El lago me lo dijo esta tarde, por cómo se rizaba: {pronostico}.',
    regalo: 'Aurelio, el pescador, te dejó dos truchas frescas',
  },
  maestra: {
    encanta: {
      pluma: 'Una pluma de cachaña. Mañana la llevo a la escuela: con esto les explico cómo vuela un loro mejor que con cualquier libro.',
      miel: 'Miel. Para el té de la tarde, mientras corrijo. Gracias, me endulzaste las correcciones.',
      'calafate-seco': 'Calafates secos. Los voy a repartir en el recreo y les voy a contar la leyenda. Así se aprende de verdad.',
    },
    gusta: '{cosa}. Qué amable, gracias.',
    noGusta: '¿Un tronco? Te lo agradezco, pero la estufa de la escuela la cargan los chicos, que así aprenden. Llevaselo a quien le haga falta.',
    ocupado: 'Estoy dando clase. Después de la una, encantada.',
    acepta: 'Me parece muy bien. Llevo el cuaderno de notas, por las dudas. Vamos a {lugar}.',
    animo: {
      bien: 'Bien. Hoy Lucía leyó en voz alta sin trabarse ni una vez.',
      cansado: 'Cansada. Ocho chicos, cuatro grados y una sola maestra.',
      inquieto: 'Con ganas de salir al bosque. Mañana hacemos clase afuera, ya lo decidí.',
      charla: 'Con ganas de charlar con un grande. ¿Qué anotaste últimamente?',
    },
    historia: { titulo: 'Una carta de cada alumno', partes: [
      'Soy de Córdoba, de las sierras. Me recibí de maestra en la normal y pedí destino rural: quería un lugar donde hiciera falta.',
      'Mi primera escuela tenía siete alumnos que llegaban a caballo. En invierno prendíamos la estufa entre todos y la clase empezaba cuando se calentaban las manos.',
      'Guardo una carta de cada alumno que tuve. Algunos ya son abuelos. Cuando me desanimo, leo una al azar, y siempre es la que necesitaba.',
    ] },
    sobremesa: [
      'Los chicos de acá saben más del bosque que yo. Yo les enseño a escribirlo.',
      'Herminia cuenta las leyendas mejor que cualquier libro. Le pedí que venga una vez por semana a la escuela.',
      'Un cuaderno es una conversación con el que vas a ser después. Por eso hay que escribir con buena letra.',
    ],
    visita: [
      'Vine a conocer el lugar del que tanto hablan los chicos. Lucía lo dibujó en su cuaderno, y le salió bastante parecido.',
      'Te dejé un poco de yerba. Para el mate de la tarde, mientras anotás.',
    ],
    saludoAmigo: 'Buen día, {nombre}. ¿Trajiste el cuaderno?',
    saludoCompadre: '¡{nombre}! Mi alumno preferido, aunque no venga a clase.',
    fauna: 'En la clase de afuera vimos {unbicho}. Los chicos casi se mueren de la emoción.',
    regalo: 'Delia, la maestra, te dejó yerba para el mate de la tarde',
  },
  enfermera: {
    encanta: {
      miel: 'Miel. Para el té de canelo de los resfriados: es el mejor remedio que conozco. Gracias.',
      harina: 'Harina. Ceinwen y yo hacemos bara brith los sábados, como en las casas de Trevelin. Ahora me toca a mí poner la harina.',
      'frasco-frutilla': 'Dulce de frutilla. Me lo como a escondidas, entre paciente y paciente. Secreto profesional.',
    },
    gusta: '{cosa}. Qué atención, gracias.',
    noGusta: 'Ay, la yerba… Perdoname, pero soy de té, como buena Williams. Llevásela a Ernesto, que la va a disfrutar.',
    ocupado: 'Ahora estoy atendiendo. Después de las seis, si no hay ninguna urgencia.',
    noToma: { mate: 'El mate no, gracias, que me deja despierta toda la noche. Si es té, voy.' },
    acepta: 'Me hace bien salir un rato. Vamos a {lugar}.',
    animo: {
      bien: 'Bien. Nadie se lastimó hoy, y eso ya es un buen día.',
      cansado: 'Cansada. Me llamaron dos veces anoche por un tobillo torcido.',
      inquieto: 'Con ganas de caminar. Me paso el día en el puesto y me olvido de que tengo piernas.',
      charla: 'Con ganas de charlar de algo que no sea la presión.',
    },
    historia: { titulo: 'Cuidar antes', partes: [
      'Mi apellido es galés, como el de Ceinwen. Mi bisabuelo llegó al Chubut con los primeros colonos.',
      'Pasé quince años en el hospital de Esquel: guardias de noche, partos, nevadas que cortaban la ruta. Aprendí que lo más importante no está en los libros: es saber escuchar.',
      'Pedí el pase a un puesto rural después de un invierno muy duro. Quería conocer a la gente antes de que se enferme, no después. Acá, cuando me tomo un té con alguien, ya estoy cuidando.',
    ] },
    sobremesa: [
      'Abrigate los pies. Lo digo en serio: el frío entra por los pies y sale por la nariz.',
      'Herminia tiene las rodillas de una de cuarenta y el humor de una de veinte. Ojalá llegue así.',
      'Lo que más curo acá son cortes de hacha y espaldas de hachero. Mario es mi paciente más fiel.',
    ],
    visita: [
      'Vine a ver cómo vivís. Es deformación profesional: me fijo si hay leña, si hay abrigo y si hay comida. Aprobado.',
      'Te dejé un frasco de miel. Una cucharada con té caliente antes de dormir, y no hay resfrío que aguante.',
    ],
    saludoAmigo: 'Hola, {nombre}. ¿Cómo andamos de salud? Bien, ya veo.',
    saludoCompadre: '¡{nombre}! Vos sos de los que vienen a visitar, no a curarse. Así me gusta.',
    fauna: 'Volviendo de un puesto lejos vi {unbicho}. Casi me olvido de que iba apurada.',
    regalo: 'Marta, la enfermera, te dejó un frasco de miel para los resfríos',
  },
  telegrafista: {
    encanta: {
      yerba: 'Yerba. Con el mate al lado del aparato, las noches de guardia se pasan volando. Raya, punto: gracias.',
      empanadas: 'Empanadas. Esto es lo que se come en una estafeta: algo que se agarre con una mano mientras la otra telegrafía.',
      'trucha-ahumada': 'Trucha ahumada. En Jacobacci la comíamos los domingos. Me trajiste un domingo entero.',
    },
    gusta: '{cosa}. Mensaje recibido, y agradecido.',
    noGusta: '¿Miel? Te lo agradezco, pero la última vez se me pegó en las teclas del Morse y mandé un telegrama que decía «hjjjjj». Mejor no.',
    ocupado: 'Estoy esperando un telegrama de Bariloche. Si me voy, se pierde. Después de las ocho, sí.',
    acepta: 'Dale. Dejo un cartelito: «Vuelvo enseguida». A {lugar}.',
    animo: {
      bien: 'Bien. La línea anda sin cortes, y eso en la cordillera es una fiesta.',
      cansado: 'Cansado. Anoche estuve de guardia hasta las tres por un temporal en la meseta.',
      inquieto: 'Con ganas de salir. Me paso el día con los auriculares y el mundo entero en un cable.',
      charla: 'Con ganas de charlar en persona. Por telégrafo no se puede reír.',
    },
    historia: { titulo: 'El telegrama enmarcado', partes: [
      'Aprendí Morse a los catorce, con un aparato que mi tío había rescatado de una estación cerrada. Practicaba golpeando la mesa con la cuchara, y mi madre me echaba de la cocina.',
      'Pasé por veinte estafetas de la línea. En cada una conocí a la gente por lo que mandaba: nacimientos, cumpleaños, pedidos de harina. El telégrafo sabe todo de todos, y no dice nada.',
      'Una noche de temporal llegó un mensaje de un puesto aislado pidiendo un médico. Lo pasé letra por letra con los dedos helados. A la mañana me avisaron que habían llegado a tiempo. Ese telegrama lo tengo enmarcado en la estafeta.',
    ] },
    sobremesa: [
      'En Morse, «hola» y «chau» son casi iguales. Por eso los telegrafistas nunca nos despedimos del todo.',
      'Ernesto y yo somos los únicos del pueblo que sabemos a qué hora llega cada tren. Él por la vía, yo por el cable.',
      'Una vez me llegó un telegrama que decía sólo «Llegué». Nunca supe de quién. Pero me alegré igual.',
    ],
    visita: [
      'Vine a ver si tenías algo para despachar. Mentira: vine a conocer tu casa.',
      'Te dejé un poco de yerba. Y una noticia: de Bariloche pasan que el invierno viene largo. Abrigate.',
    ],
    saludoAmigo: 'Raya, punto, raya: ¡hola, {nombre}!',
    saludoCompadre: '¡{nombre}! Si fueras un telegrama, serías de los urgentes.',
    fauna: 'Me pasaron por el telégrafo, desde la seccional, que anda {unbicho} por la zona.',
    pronostico: 'De Bariloche pasan {pronostico}. Y el telégrafo no miente.',
    regalo: 'Benigno, el telegrafista, te dejó yerba',
  },
  tejedora: {
    encanta: {
      lana: 'Un vellón… Mirá qué fibra, larga y limpia. Con esto sale la trama de un poncho entero. Gracias.',
      calafate: 'Calafate. ¿Sabías que con el fruto se tiñe la lana de morado? Mi abuela teñía así. Gracias, de verdad.',
      yerba: 'Yerba. El mate al lado del witral, mientras el peine sube y baja. Así se teje bien.',
    },
    gusta: '{cosa}. Gracias, me hace bien.',
    noGusta: '¿Un canto rodado? Es lindo, pero no le encuentro uso. ¿Será para que no se vuele el vellón?',
    ocupado: 'Tengo la urdimbre tensada. Si la suelto, se pierde la trama. Más tarde, ¿sí?',
    acepta: 'Bueno, un rato. Tapo el witral y vamos a {lugar}.',
    animo: {
      bien: 'Bien, tranquila. El poncho va creciendo de a poquito.',
      cansado: 'Cansada. Cuatro horas de peine y tengo los dedos dormidos.',
      inquieto: 'Con ganas de salir a juntar raíces para teñir.',
      charla: 'Con ganas de charlar. El telar es buena compañía, pero repite siempre lo mismo.',
    },
    historia: { titulo: 'El poncho del baúl', partes: [
      'Mi abuela tejía en el witral, bajo el alero del rancho, mirando la cordillera. Yo me sentaba a su lado a separar los colores de la lana.',
      'Los dibujos del poncho no son adorno: cada uno dice algo. El escalonado es la montaña; la greca, el camino. Mi abuela decía que un poncho se lee.',
      'El primer poncho que tejí sola se lo regalé a mi padre. Lo usó treinta años. Cuando nos dejó, me lo devolvieron doblado. Lo tengo en el baúl y cada tanto lo abro, para que respire.',
    ] },
    sobremesa: [
      'Un buen poncho no deja pasar el agua ni el viento. Uno malo, ni siquiera abriga la vergüenza.',
      'Don Ramón tiene un poncho que le hizo su madre. Le dije que se lo arreglo cuando quiera, pero no me lo presta ni un día.',
      'La lana de acá es dura, como el clima. Hay que lavarla tres veces y quererla mucho.',
    ],
    visita: [
      'Vine a ver si tenías algún tejido que arreglar. Siempre hay algo deshilachado en una casa.',
      'Te dejé dos vellones lavados. Para tu telar, o para lo que quieras.',
    ],
    saludoAmigo: 'Hola, {nombre}. Mirá este punto: es nuevo.',
    saludoCompadre: '{nombre}, tengo algo para mostrarte en el telar. Vení.',
    fauna: 'Juntando raíces para teñir vi {unbicho}. Me quedé con la mano en la tierra, sin moverme.',
    regalo: 'Elvira, la tejedora, te dejó dos vellones lavados',
  },
  apicultor: {
    encanta: {
      'frasco-frutilla': 'Dulce de frutilla, como el de El Hoyo. Me hiciste extrañar la chacra de mi nonno, en el buen sentido.',
      frutilla: 'Frutillas frescas. Las abejas las polinizan y yo me las como. Me parece un buen trato.',
      harina: 'Harina. Esta noche hago tagliatelle como mi nonna. Te guardo un plato, prometido.',
    },
    gusta: '{cosa}. Grazie, gracias.',
    noGusta: '¿Miel? Ay, gracias, pero es como regalarle agua al lago. ¡Tengo seis cajones llenos!',
    ocupado: 'Estoy con los cajones abiertos. Si me voy, las abejas se ponen nerviosas. Después, ¿sí?',
    acepta: 'Bene, vamos. Me saco el sombrero de red y vamos a {lugar}.',
    animo: {
      bien: 'Bien. Las abejas están tranquilas, y cuando ellas están tranquilas, yo también.',
      cansado: 'Cansado. Hoy cosechamos tres cajones y tengo las manos pegajosas hasta el codo.',
      inquieto: 'Con ganas de caminar por el bosque buscando flores nuevas.',
      charla: 'Con ganas de charlar. Las abejas zumban, pero no conversan.',
    },
    historia: { titulo: 'El enjambre que volvió', partes: [
      'Mi nonno vino de Italia, del Piamonte, y terminó en El Hoyo plantando frambuesas. Las abejas vinieron después, para polinizar.',
      'Con las abejas aprendí a no apurarme. Si te ponés nervioso, lo saben. Hay que moverse despacio y hablarles bajito.',
      'Un verano se me escapó un enjambre entero. Lo seguí tres kilómetros por el bosque hasta un coihue hueco. Me senté a esperar y a la tarde bajaron solas a la caja. Desde ese día creo que ellas también me eligieron.',
    ] },
    sobremesa: [
      'El notro, el chilco, la rosa mosqueta: cada flor le da a la miel un gusto distinto. La de acá sabe a cordillera.',
      'Gladys me pide miel para el dulce y yo le pido dulce para el pan. Somos un pequeño comercio de cariño.',
      'Las abejas se comunican bailando. Yo no sé bailar, así que les hablo.',
    ],
    visita: [
      'Vine siguiendo una abeja y terminé en tu casa. Es broma: vine a conocerla.',
      'Te dejé dos frascos de miel. Es de esta semana, de notro.',
    ],
    saludoAmigo: 'Ciao, {nombre}. Despacito, que las abejas te conocen.',
    saludoCompadre: '¡{nombre}! Las abejas ya te reconocen. Yo también, caro.',
    fauna: 'Buscando flores nuevas vi {unbicho}. Las abejas me llevan a lugares que no conocía.',
    regalo: 'Guido, el apicultor, te dejó dos frascos de miel',
  },
  guardaparque: {
    encanta: {
      yerba: 'Yerba. En la recorrida, el mate es lo que me mantiene despierta al amanecer. Gracias.',
      'calafate-seco': 'Calafates secos. Los llevo en el bolsillo de la campera, para el camino. Gracias, de verdad.',
      pinon: 'Piñones. Mi abuelo los juntaba en marzo, en la veranada. Los voy a tostar esta noche, como él.',
    },
    gusta: '{cosa}. Gracias, me viene bien para la recorrida.',
    noGusta: 'Te lo agradezco, pero el llao llao prefiero verlo en el árbol. Ahí es donde lo anotamos.',
    ocupado: 'Estoy en plena recorrida. Si dejo el registro a medias, mañana no sé dónde quedé. Más tarde.',
    acepta: 'Dale. Cierro la seccional y vamos a {lugar}.',
    animo: {
      bien: 'Bien. Hoy anoté tres especies en el registro.',
      cansado: 'Cansada. Caminé quince kilómetros siguiendo un rastro que no llevaba a ningún lado.',
      inquieto: 'Con ganas de salir al monte. Si estoy adentro, siento que me pierdo algo.',
      charla: 'Con ganas de charlar con alguien que mire el bosque como yo.',
    },
    historia: { titulo: 'Tres días sin respirar', partes: [
      'Me crié en una comunidad cerca del Lanín. Mi abuelo conocía cada huella del monte y me llevaba a leerlas como quien lee un diario.',
      'Fui la primera mujer guardaparque de mi promoción. Los primeros meses me tocaba cortar leña para demostrar que podía. Después ya no hizo falta.',
      'Una vez estuve tres días siguiendo a una hembra de huemul con su cría para el censo. No las toqué ni me vieron. Cuando por fin las anoté, me di cuenta de que había estado conteniendo la respiración los tres días.',
    ] },
    sobremesa: [
      'El bosque te habla si sabés escuchar. Un silencio de golpe quiere decir que algo grande anda cerca.',
      'Ema y yo nos pasamos los registros. Entre las dos tenemos medio valle anotado.',
      'Los chicos de la aldea me traen cada cosa… Nahuel me trajo una piedra «con forma de huella de puma». Era una piedra.',
    ],
    visita: [
      'Pasaba por la recorrida y dije: paso a saludar. Tenés buena vista desde acá.',
      'Te dejé unos piñones del pehuén viejo. Tostalos al fuego, como se hacía antes.',
    ],
    saludoAmigo: 'Buen día, {nombre}. ¿Algún avistaje para el registro?',
    saludoCompadre: '¡{nombre}! Vos ya sos guardaparque honoraria… u honorario. Lo que prefieras.',
    fauna: 'En la recorrida de esta mañana vi {unbicho}. Ya está en el registro.',
    pronostico: 'Por cómo están los cóndores, te diría {pronostico}.',
    regalo: 'Julia, la guardaparque, te dejó piñones del pehuén viejo',
  },
  musico: {
    encanta: {
      empanadas: '¡Empanadas! Esto es lo que se come en un baile, entre chamamé y chamamé. Gracias, hermano.',
      yerba: 'Yerba. El mate y la guitarra son el mismo instrumento: los dos se pasan de mano en mano.',
      'pan-casero': 'Pan casero. Con un poco de dulce, después de tocar toda la noche, es lo mejor que existe.',
    },
    gusta: '{cosa}. ¡Gracias! Te debo una canción.',
    noGusta: '¿Habas? Ay, no. Me caen pesadas y después no puedo cantar. Perdoname.',
    ocupado: 'Estoy ensayando para el sábado. Si paro, se me olvida el arreglo. Más tarde, ¿dale?',
    acepta: '¡Vamos! Llevo la guitarra, por si se arma algo. A {lugar}.',
    animo: {
      bien: 'Bien. Me salió un arreglo nuevo para una cueca vieja.',
      cansado: 'Cansado. Toqué hasta las tres de la mañana y todavía me zumban los oídos.',
      inquieto: 'Con ganas de salir a buscar música. Los pájaros de acá tienen cada melodía…',
      charla: 'Con ganas de charlar. Un músico sin público es un loro en una jaula.',
    },
    historia: { titulo: 'Las canciones de mi viejo', partes: [
      'Nací en Corrientes, en un rancho donde siempre había una verdulera sonando. Me subí al tren hacia el sur a los veinte, con la guitarra y nada más.',
      'Toqué en bailes de galpón, en fiestas de esquila, en casamientos donde no conocía a nadie. Al final de la noche ya era de la familia.',
      'Mi viejo era músico y nunca grabó un disco. Las canciones que sé son de él, y yo se las enseño a quien quiera. Mientras alguien las toque, él sigue tocando.',
    ] },
    sobremesa: [
      'El chamamé se baila apretado; la cueca, con pañuelo y distancia. Herminia dice que la cueca es más elegante. Tiene razón.',
      'Una vez toqué tanto en una fiesta de esquila que las ovejas se acercaron al galpón. Es verdad, preguntale a Don Ramón.',
      'Tito me está haciendo una guitarra de lenga. Dice que va a sonar a bosque. Ya veremos.',
    ],
    visita: [
      'Vine a tocarte una canción. Bueno, a tomar mate, pero si sale una canción, sale.',
      'Te dejé unas empanadas. Me sobraron del baile, pero están buenas.',
    ],
    saludoAmigo: '¡{nombre}! Justo estaba afinando. ¿Qué querés escuchar?',
    saludoCompadre: '¡{nombre}, hermano! Esta te la toco a vos.',
    fauna: 'Afinando en la plaza a la mañana, escuché y vi {unbicho}. Me tiró una nota que no conocía.',
    regalo: 'Cholo, el músico, te dejó empanadas del baile',
  },
  ramon: {
    encanta: {
      yerba: 'Yerba. Esto no se rechaza nunca, m\'hijo. Gracias.',
      calafate: 'Calafate. El que come calafate, vuelve. Vos ya volviste unas cuantas veces, así que debe ser cierto.',
      'trucha-ahumada': 'Trucha ahumada. Con un pedazo de pan y el fuego del puesto, es lo mejor que se puede pedir.',
    },
    gusta: '{cosa}. Gracias, m\'hijo.',
    noGusta: '¿Habas? No, que me caen pesadas. Dáselas a alguno de los de abajo.',
    ocupado: 'Ahora estoy con la majada. Los animales no esperan. A la tardecita, si querés.',
    noToma: { te: '¿Té? Yo soy de mate, toda la vida. Si es mate, voy.' },
    acepta: 'Bueno, bajo un rato. A {lugar}.',
    animo: {
      bien: 'Bien. El campo está tranquilo y los animales comen.',
      cansado: 'Cansado. Cuarenta inviernos acá se sienten en los huesos.',
      inquieto: 'Con ganas de subir al cerro. Hace mucho que no veo el valle de arriba.',
      charla: 'Con ganas de charlar, para variar. Acá arriba hablo con los perros.',
    },
    historia: { titulo: 'El monte que vi crecer', partes: [
      'Nací en un puesto como este, más al norte. Mi madre me hizo el primer poncho y mi padre el primer lazo, el mismo año.',
      'Tuve un perro, el Chocolate, que entendía las señas mejor que muchos peones. Arreaba solo. Cuando se fue, no quise tener otro por años.',
      'Si tengo un orgullo es haber cuidado este monte cuarenta años sin sacarle más de lo que daba. No tengo hijos, pero el bosque de la ladera lo vi crecer. Ese es mi hijo, si querés.',
    ] },
    sobremesa: [
      'El viento del oeste trae lluvia; el del este, frío. El que no viene de ningún lado, ese es el que hay que mirar.',
      'Antes se subía la majada en diciembre. Ahora quedamos pocos haciéndolo, pero mientras haya pasto arriba, alguien va a subir.',
      'La tejedora de la aldea me quiere arreglar el poncho. Le dije que el poncho está bien así: los agujeros también son míos.',
    ],
    visita: [
      'Pasaba con la majada y vi la mesa puesta. Uno ve una mesa con bancos y ya sabe que ahí se puede parar.',
      'Te traje yerba, que la de uno siempre se acaba el día que menos pensás.',
    ],
    saludoAmigo: '¿Qué hacés, {nombre}? Sentate, que el mate está caliente.',
    saludoCompadre: '{nombre}. Vos ya sos de acá, aunque no hayas nacido acá.',
    fauna: 'Bajando con la majada vi {unbicho}. Los perros lo vieron primero.',
    pronostico: 'Por cómo se pone el cerro, te diría {pronostico}.',
    regalo: 'Don Ramón te dejó un kilo de yerba',
  },
  nicanor: {
    encanta: {
      yerba: 'Yerba. Para el mate del bote. Gracias, vecino.',
      'pan-casero': 'Pan casero. Me lo llevo al agua mañana temprano. Con el lago quieto, es un manjar.',
      empanadas: 'Empanadas. A la orilla, con el fuego chico y mirando el agua. No necesito más.',
    },
    gusta: '{cosa}. Gracias, vecino.',
    noGusta: '¿Una trucha? Te lo agradezco, pero ya tengo más de las que puedo comer. Devolvela al lago, que ahí está mejor.',
    ocupado: 'Estoy en plena picada. Si me voy ahora, pierdo la mejor hora. Al mediodía, ¿te parece?',
    noToma: { te: '¿Té? No, gracias. El mate, sí.' },
    acepta: 'Dale. Ato el bote y vamos a {lugar}.',
    animo: {
      bien: 'Bien. El lago estuvo de vidrio esta mañana.',
      cansado: 'Cansado. El viento de la tarde me hizo remar de vuelta como si fuera cuesta arriba.',
      inquieto: 'Con ganas de estar en el agua. En tierra no sé qué hacer con las manos.',
      charla: 'Con ganas de charlar. En el agua uno piensa mucho y no tiene a quién contárselo.',
    },
    historia: { titulo: 'La corriente da vueltas', partes: [
      'Mi padre llegó al lago cuando sembraron las truchas. Lo contrataron para cuidar los criaderos y se quedó para siempre.',
      'Aprendí a remar antes que a caminar, decía mi madre. A los diez ya cruzaba la bahía solo, con una lata para achicar el agua.',
      'Aurelio y yo éramos inseparables. Cuando se fue al sur pensé que no lo iba a ver más. Ahora vive en la aldea y pescamos juntos los domingos. La vida da vueltas, como la corriente.',
    ] },
    sobremesa: [
      'El lago tiene humores, como la gente. Hay que saber cuándo hablarle y cuándo dejarlo tranquilo.',
      'Una vez saqué una marrón tan grande que me dio lástima. La devolví y me quedé mirando cómo se iba. Fue la mejor pesca de mi vida.',
      'Cuando el viento sopla del oeste, no salgas. El lago se pone bravo en un rato.',
    ],
    visita: [
      'Hoy el lago estaba de vidrio y no picaba nada. Me dije: voy a ver cómo le va al vecino.',
      'Te dejé unos troncos secos de la orilla. Para la estufa, que las noches se ponen bravas.',
    ],
    saludoAmigo: '{nombre}. Justo estaba mirando el agua. ¿Sacaste algo hoy?',
    saludoCompadre: '¡{nombre}! Mañana salimos juntos, si querés. El bote tiene lugar.',
    fauna: 'Desde el bote vi {unbicho} en la orilla. Me quedé quieto con el remo en el aire.',
    pronostico: 'Por cómo están las nubes sobre el lago, {pronostico}.',
    regalo: 'Nicanor te dejó troncos secos de la orilla',
  },
  ema: {
    encanta: {
      frutilla: 'Frutillas silvestres. Me las como en la recorrida, una por kilómetro. Gracias.',
      'calafate-seco': 'Calafates secos. Los llevo en el bolsillo para el camino. ¡Gracias!',
      yerba: 'Yerba. El mate del amanecer, en el mirador, es lo que me hace levantar a las cinco.',
    },
    gusta: '{cosa}. Gracias, ¡qué lindo detalle!',
    noGusta: 'Una pluma… Te lo agradezco, pero las plumas se quedan en el bosque, para el registro. La próxima, dejala donde la encontraste.',
    ocupado: 'Estoy en plena recorrida. Si me desvío, no llego a la cascada antes del atardecer. Más tarde.',
    acepta: 'Dale, vamos. Me merezco un descanso. A {lugar}.',
    animo: {
      bien: 'Bien. Hoy vi un pato de los torrentes con cría. Me alegró el día.',
      cansado: 'Cansada. Hice la vuelta larga del sendero, ida y vuelta.',
      inquieto: 'Con ganas de salir al monte. Siempre hay algo nuevo para anotar.',
      charla: 'Con ganas de charlar con alguien que anote cosas como yo.',
    },
    historia: { titulo: 'El cuaderno de atrás para adelante', partes: [
      'Estudié biología en Bariloche. Me anoté de guardaparque por un verano y me quedé quince años.',
      'Lo que más me gusta del trabajo es lo que nadie ve: contar pájaros a las cinco de la mañana, medir el arroyo, anotar las flores del primer día de primavera.',
      'Tengo un cuaderno como el tuyo, lleno desde hace años. A veces lo leo de atrás para adelante y veo cómo cambió el bosque. Si se incendiara la casa, es lo único que me llevaría.',
    ] },
    sobremesa: [
      'El chucao canta fuerte y nunca lo ves. Es el pájaro más tímido y más ruidoso del bosque.',
      'Julia, la de la seccional de la aldea, me pasa sus registros. Entre las dos tenemos medio valle anotado.',
      'Lo más lindo de este trabajo es cuando alguien empieza a anotar sin que se lo pidas. Como vos.',
    ],
    visita: [
      'Estaba haciendo el recorrido y dije: paso a saludar. ¡Qué linda te quedó la casa!',
      'Te traje semillas de habas del vivero del parque. Se dan bien en esta tierra.',
    ],
    saludoAmigo: 'Buenas, {nombre}. ¿Todo bien en el bosque?',
    saludoCompadre: '¡{nombre}! Te estaba por ir a buscar: tengo algo para mostrarte.',
    fauna: 'En la recorrida de esta mañana vi {unbicho}. Me quedé un rato largo mirándolo.',
    pronostico: 'Por cómo se cerró el cerro esta tarde, {pronostico}.',
    regalo: 'Ema te dejó semillas de habas del vivero del parque',
  },
  guarda: {
    encanta: {
      yerba: 'Yerba. El mate del furgón es el mejor de la línea, y ahora más. Gracias.',
      empanadas: '¡Empanadas! La cuadrilla de la vía se va a poner contenta. Bueno, si les dejo alguna.',
      'calafate-seco': 'Calafates secos. Para los chicos que viajan solos: uno en cada estación. Gracias.',
    },
    gusta: '{cosa}. ¡Qué amable! Lo llevo en el furgón.',
    noGusta: '¿Piedras? Ay, piedras hay de sobra en el balasto. Pero gracias por la intención.',
    ocupado: 'Estoy de servicio. El tren no espera, y yo tampoco puedo. Cuando termine el recorrido, sí.',
    acepta: '¡Vamos! Me saco la gorra y vamos a {lugar}.',
    animo: {
      bien: 'Bien. El tren anduvo en hora y nadie perdió nada.',
      cansado: 'Cansada. Tres recorridos completos y una vaca en la vía.',
      inquieto: 'Con ganas de bajarme un rato. Paso el día viendo el paisaje desde la ventanilla.',
      charla: 'Con ganas de charlar sin el ruido de la máquina.',
    },
    historia: { titulo: 'Un pueblo sobre rieles', partes: [
      'Mi abuelo fue maquinista de la trochita y mi madre, boletera. Yo nací prácticamente en un coche de segunda.',
      'Soy guarda desde hace veinticinco años. Conozco cada curva, cada puente y cada perro que sale a ladrarle al tren.',
      'Un invierno quedamos varados dos días en la nieve. Hicimos guiso en la salamandra con lo que tenía cada pasajero. Cuando llegó la cuadrilla con las palas, nadie se quería bajar. Esa es la trochita: un pueblo que anda sobre rieles.',
    ] },
    sobremesa: [
      'El silbato tiene tres tonos: uno para el cruce, uno para la estación y uno para los amigos que saludan desde la tranquera.',
      'Ernesto, el jefe de la aldea, es el jefe de estación más puntual de la línea. Bueno, más o menos.',
      'Si alguna vez viajás de noche, mirá para arriba. Desde el tren, las estrellas se ven pasar.',
    ],
    visita: [
      'Me bajé en la parada más cercana y vine caminando. Tenía ganas de pisar tierra.',
      'Te dejé pan de la cuadrilla. Lo hacen ellos mismos en la salamandra del galpón.',
    ],
    saludoAmigo: '¡{nombre}! Bienvenido a bordo, como siempre.',
    saludoCompadre: '¡{nombre}! Para vos, el asiento de la ventanilla está reservado.',
    fauna: 'Desde la ventanilla vi {unbicho} cerca de la vía. Los pasajeros se amontonaron de un lado.',
    pronostico: 'El maquinista dice {pronostico}. Y el maquinista nunca se equivoca. Casi nunca.',
    regalo: 'Elsa, la guarda del tren, te dejó pan de la cuadrilla',
  },
};

// ---------------------------------------------------------------- las ayudas de cada oficio
// Una ayuda chica por día. `pide`: algo que hay que tener ({ tipo, k, n }); sin `pide`, es algo
// que se hace en el momento (`hace: true`). `devuelve`: lo que te da a veces (una ayuda sí, otra
// no; las otras, el consejo). `gracias`: lo que dice al terminar.
export const AYUDAS = {
  jefe: [
    { id: 'salamandra-anden', titulo: 'Alcanzarle un tronco para la salamandra de la sala de espera', pide: { tipo: 'material', k: 'tronco', n: 1 },
      gracias: ['Gracias. Con esto la sala de espera queda calentita hasta el último tren. Los pasajeros te lo agradecen sin saberlo.'],
      devuelve: { tipo: 'cosa', k: 'yerba', n: 1, texto: 'Tomá, yerba para el camino.' },
      consejo: 'Un consejo de ferroviario: la trochita para en todas las estaciones. Si estás lejos del refugio, subite y te ahorrás la caminata.' },
    { id: 'faroles', titulo: 'Cargarle kerosene a los faroles del andén', hace: true,
      gracias: ['Así, despacito, que el kerosene no perdona. Ya está: esta noche el andén se ve desde el lago.'],
      consejo: 'Los faroles se cargan de día. De noche, con el kerosene, uno termina prendiéndose la manga.' },
  ],
  nelida: [
    { id: 'bolsas', titulo: 'Ayudarla a bajar las bolsas de harina al depósito', hace: true,
      gracias: ['¡Ay, gracias! Sola tardo una hora y termino con la espalda torcida. Con vos fue un ratito.'],
      devuelve: { tipo: 'cosa', k: 'harina', n: 1, texto: 'Tomá una medida de harina. Ercilia no se va a dar cuenta… o sí, pero no va a decir nada.' },
      consejo: 'Si te falta algo, encargalo antes del jueves: el tren de los jueves trae todo lo pedido.' },
  ],
  abuela: [
    { id: 'lena-abuela', titulo: 'Entrarle dos troncos para la estufa', pide: { tipo: 'material', k: 'tronco', n: 2 },
      gracias: ['Gracias, tesoro. A mi edad, cargar leña es como subir el cerro. Ahora sí, esta noche duermo calentita.'],
      devuelve: { tipo: 'entrada', k: 'calafate-seco', n: 1, texto: 'Llevate unos calafates secos de mi alero.' },
      consejo: 'Dormí siempre con la manta a mano, aunque sea verano. El frío de la cordillera llega sin avisar.' },
    { id: 'aguja', titulo: 'Enhebrarle la aguja', hace: true,
      gracias: ['Ay, qué vista tenés. Yo hace diez minutos que le apunto al agujerito y no hay caso.'],
      consejo: 'Cuando veas una puertita en una raíz, golpeá. No hace falta que conteste nadie: es por respeto.' },
  ],
  padre: [
    { id: 'apilar', titulo: 'Apilar la leña con él', hace: true,
      gracias: ['Así se apila: la corteza para arriba, que escurra el agua. Entre dos se hace en la mitad de tiempo.'],
      devuelve: { tipo: 'material', k: 'tronco', n: 2, texto: 'Llevate dos troncos, que te los ganaste.' },
      consejo: 'La leña se corta en otoño y se quema en invierno. La leña verde llora en la estufa y no calienta.' },
  ],
  madre: [
    { id: 'frutos-dulce', titulo: 'Llevarle frutillas para el dulce', pide: { tipo: 'entrada', k: 'frutilla', n: 3 },
      gracias: ['¡Qué lindas! Esta tarde hago dulce y los chicos van a andar pegoteados hasta el domingo.'],
      devuelve: { tipo: 'entrada', k: 'frasco-frutilla', n: 1, texto: 'Llevate este frasco, que es de la tanda anterior.' },
      consejo: 'Las frutillas primero al rescoldo, tres sobre las brasas. Cuando ya sabés hacerlas así, el dulce en frasco sale solo.' },
  ],
  nene: [
    { id: 'pelota', titulo: 'Pasarle la pelota un rato', hace: true,
      gracias: ['¡Gol! ¡Te hice un gol! Bueno, vos me la dejaste pasar, pero cuenta igual.'],
      devuelve: { tipo: 'entrada', k: 'canto', n: 1, texto: 'Tomá, un canto rodado. No es de los más redondos, pero es lindo.' },
      consejo: '¿Sabés dónde hay cantos rodados? ¡Junto al agua! Son redondos de tanto rodar.' },
  ],
  nena: [
    { id: 'leer-nena', titulo: 'Leerle un cuento del cuaderno', hace: true,
      gracias: ['¡Otra vez la parte del huemul! Bueno, no, ya está. Gracias. Leés lindo, como la abuela.'],
      consejo: 'La abuela lee cuentos en la biblioteca los domingos a las diez. ¡Vení, que hay lugar!' },
  ],
  galesa: [
    { id: 'truchas-te', titulo: 'Llevarle dos truchas frescas para la cocina', pide: { tipo: 'entrada', k: 'trucha-fresca', n: 2 },
      gracias: ['Diolch! Con esto hago los sándwiches de trucha para el té de mañana. Los de la galería se van a chupar los dedos.'],
      devuelve: { tipo: 'entrada', k: 'pan-casero', n: 1, texto: 'Llevate un pan de la casa, que salió esta mañana.' },
      consejo: 'El té se deja reposar tres minutos, ni uno más. Si no, amarga.' },
    { id: 'tazas', titulo: 'Ayudarla a secar las tazas', hace: true,
      gracias: ['Qué ayuda. Las tazas de la galería son de mi nain: las seco yo, pero hoy te dejo. Es un honor, eh.'],
      consejo: 'En días de lluvia la galería se llena. Si querés mesa, vení temprano.' },
  ],
  ercilia: [
    { id: 'estantes', titulo: 'Ayudarla a acomodar los estantes', hace: true,
      gracias: ['Así, la yerba con la yerba y el kerosene lejos de la harina. Qué orden. Nélida va a pensar que lo hice yo sola.'],
      devuelve: { tipo: 'cosa', k: 'yerba', n: 1, texto: 'Tomá, yerba. Por las molestias.' },
      consejo: 'Si tenés plumas o cantos rodados de más, traelos: acá se cambian por cosas útiles.' },
  ],
  carpintero: [
    { id: 'sostener', titulo: 'Sostenerle la tabla mientras sierra', hace: true,
      gracias: ['Firme… firme… ¡listo! Derechita. Con alguien que sostenga, la sierra corre sola.'],
      devuelve: { tipo: 'material', k: 'tabla', n: 2, texto: 'Llevate estas dos, que me sobraron del corte.' },
      consejo: 'Aserrá en el banco de carpintero: a mano, un tronco te rinde dos tablas; en el banco, cuatro.' },
  ],
  panadera: [
    { id: 'lena-horno', titulo: 'Alcanzarle leña para el horno', pide: { tipo: 'material', k: 'tronco', n: 2 },
      gracias: ['¡Justo! Me quedaba leña para una tanda nada más. Con esto, mañana hay pan para todos.'],
      devuelve: { tipo: 'entrada', k: 'pan-casero', n: 1, texto: 'Tomá, un pan de la tanda. Está tibio.' },
      consejo: 'Para pan casero: dos medidas de harina y un tronco, en el horno de barro. Y paciencia, que la masa no se apura.' },
  ],
  herrero: [
    { id: 'piedras-fragua', titulo: 'Juntarle piedras para la fragua', pide: { tipo: 'material', k: 'piedra', n: 3 },
      gracias: ['Buenas piedras. Con esto le hago el borde nuevo a la fragua, que la vieja ya está rajada.'],
      consejo: 'Un hacha con filo cansa la mitad. Pasá cuando quieras y te la afilo.' },
  ],
  pescador: [
    { id: 'red', titulo: 'Ayudarlo a remendar la red', hace: true,
      gracias: ['Así, nudo por nudo. Tenés buena mano para esto. Si un día querés salir en el bote, avisame.'],
      devuelve: { tipo: 'entrada', k: 'trucha-fresca', n: 1, texto: 'Llevate una trucha de las de hoy.' },
      consejo: 'Las marrones grandes comen al amanecer y al anochecer. Al mediodía, ni las busques.' },
  ],
  maestra: [
    { id: 'leer-chicos', titulo: 'Leerles un rato a los chicos', hace: true,
      gracias: ['¡Qué bien leés! Los chicos no volaron ni una mosca. Eso conmigo no pasa nunca.'],
      consejo: 'Anotá todo, aunque te parezca poco. Lo que no se anota, se olvida.' },
  ],
  enfermera: [
    { id: 'canelo', titulo: 'Juntarle hojas de canelo para el té', hace: true,
      gracias: ['Perfectas. Con estas hojas hago té para todo el invierno. Gracias, me ahorraste una caminata.'],
      consejo: 'Si dormís cerca del fuego y bien abrigado, amanecés como nuevo. Con frío, el cuerpo no descansa.' },
  ],
  telegrafista: [
    { id: 'escalera', titulo: 'Sostenerle la escalera mientras tiende el cable', hace: true,
      gracias: ['¡Listo! Ya está tendido. Sin vos, me hubiera tenido que colgar de la rama como un mono.'],
      consejo: 'Si un vecino te escribe, contestale. Las cartas que no se contestan pesan.' },
  ],
  tejedora: [
    { id: 'ovillar', titulo: 'Devanarle la lana en ovillos', hace: true,
      gracias: ['Así, con las manos abiertas… perfecto. Ovillar entre dos es como charlar sin hablar.'],
      consejo: 'Con la tijera de esquilar, cada oveja del corral te da su vellón. Tratala bien, que la lana vuelve a crecer.' },
    { id: 'vellon', titulo: 'Llevarle un vellón para la trama', pide: { tipo: 'material', k: 'lana', n: 1 },
      gracias: ['Un vellón lindo. Lo lavo tres veces y entra en la trama del poncho grande. Gracias.'],
      consejo: 'La lana se lava con agua tibia, nunca caliente: si no, se apelmaza y no hay quien la hile.' },
  ],
  apicultor: [
    { id: 'ahumador', titulo: 'Pasarle el ahumador mientras revisa los cajones', hace: true,
      gracias: ['Despacito… así. Las abejas ni se enteraron. Tenés pulso de apicultor.'],
      devuelve: { tipo: 'entrada', k: 'miel', n: 1, texto: 'Tomá un frasco, que es de este cajón.' },
      consejo: 'Con harina y un frasco de miel, al fuego, salen sopaipillas. Probalas un día de lluvia.' },
  ],
  guardaparque: [
    { id: 'cartel', titulo: 'Ayudarla a repintar el cartel del sendero', hace: true,
      gracias: ['¡Quedó como nuevo! Ahora se lee «No hacer fuego» desde lejos, que es la idea.'],
      consejo: 'Al huemul buscalo en lo alto, al amanecer o al atardecer. Y si lo ves, quedate quieto.' },
  ],
  musico: [
    { id: 'cuerda', titulo: 'Sostenerle la guitarra mientras cambia una cuerda', hace: true,
      gracias: ['Ya está. Escuchá… ¡qué lindo suena! Esa nota la cantás vos el sábado.'],
      consejo: 'Una vez por semana te enseño una melodía para el tocadiscos del refugio. Pasá, que tengo varias.' },
  ],
  ramon: [
    { id: 'tranquera', titulo: 'Llevarle troncos para los postes de la tranquera', pide: { tipo: 'material', k: 'tronco', n: 2 },
      gracias: ['Buenos troncos, derechos. Con esto la tranquera aguanta otros veinte inviernos.'],
      devuelve: { tipo: 'cosa', k: 'yerba', n: 1, texto: 'Tomá, para el mate.' },
      consejo: 'Al pehuén no se lo tala. Se lo mira, se le juntan los piñones y se lo deja tranquilo.' },
  ],
  nicanor: [
    { id: 'bote', titulo: 'Ayudarlo a sacar el bote del agua', hace: true,
      gracias: ['¡Ahí está! Arriba, en la costa, que esta noche sopla. Gracias, solo me cuesta el doble.'],
      devuelve: { tipo: 'entrada', k: 'trucha-fresca', n: 1, texto: 'Llevate una trucha de las de hoy.' },
      consejo: 'Con viento de la tarde no salgas al lago. Ola corta, y te empuja para el medio.' },
  ],
  ema: [
    { id: 'basura', titulo: 'Juntar con ella lo que dejó la gente en el sendero', hace: true,
      gracias: ['Gracias. Es increíble lo que deja la gente: una lata, un papel, una media. El bosque te lo agradece.'],
      consejo: 'Con el pudú, moverse despacio y agachado ayuda. Es el más tímido del bosque.' },
  ],
  guarda: [
    { id: 'salamandra-tren', titulo: 'Cargarle un tronco a la salamandra del coche', pide: { tipo: 'material', k: 'tronco', n: 1 },
      gracias: ['¡Qué bien! Con esto el coche dos llega calentito hasta la última estación.'],
      devuelve: { tipo: 'entrada', k: 'pan-casero', n: 1, texto: 'Tomá, pan de la cuadrilla.' },
      consejo: 'Del tren te bajás en cualquier estación, pero nunca en marcha, eh.' },
  ],
};

// ---------------------------------------------------------------- lo que comentan de vos
// Por hecho, quién lo comenta y cómo. `_recibe`: el que recibió el regalo, la ayuda o la
// invitación (al día siguiente). `_chisme`: los que se enteran y lo cuentan. `_dueno`: el dueño
// del lote de la obra. Cada línea puede usar las marcas del hecho; si le falta alguna, se usa la
// siguiente que se pueda.
export const COMENTARIOS = {
  'trucha-grande': {
    pescador: ['Me contaron que sacaste una {especie} de {cm} centímetros. ¿La devolviste o la ahumaste? Las dos cosas están bien.', 'Me contaron que sacaste una grande. Eso no se saca con suerte sola.'],
    nicanor: ['Vi desde el bote que peleabas una grande. {cm} centímetros, me dijeron. Bien hecho.', 'Vi desde el bote que peleabas una grande. Bien hecho.'],
    herrero: ['¿Así que una trucha de {cm}? Si la ahumás, acordate de este herrero.'],
    nene: ['¡Me dijeron que sacaste una trucha más grande que yo! ¿Es verdad?'],
    jefe: ['En la estación no se habla de otra cosa: la trucha de {cm} centímetros. El maquinista ya dice que medía un metro.', 'En la estación no se habla de otra cosa que de tu trucha.'],
    guarda: ['En el tren contaban de una trucha de {cm}. Para cuando lleguemos a la última estación, va a medir dos metros.'],
  },
  'pez-nativo': {
    ema: ['Me contaron que sacaste una {especie}. Esa es de acá, de antes que las truchas. Ojalá la hayas devuelto.', 'Me contaron que sacaste un pez nativo. Ojalá lo hayas devuelto.'],
    guardaparque: ['Una {especie}, me dijeron. Va al registro: cada vez se ven menos.'],
    nicanor: ['¿Una {especie}? Esas eran las de mi padre. Ya casi no se ven grandes.'],
  },
  talar: {
    ema: ['Escuché hachazos todo el día para tu lado. Acordate de plantar algún renoval, que el bosque lleva la cuenta.'],
    guardaparque: ['Te escuché hachar desde la seccional. Llevate lo que necesites, pero dejá en pie los viejos, que son los que dan semilla.'],
    padre: ['¡Qué manera de hachar, eh! A ese ritmo me sacás el trabajo.'],
    carpintero: ['Si te sobran troncos de tanto hachar, traelos: tablas nunca sobran.'],
    ramon: ['Mucho hachazo ayer. El monte da, pero también se cansa.'],
  },
  renoval: {
    ema: ['Vi el renoval que plantaste. En cincuenta años alguien se va a sentar a su sombra sin saber tu nombre. Eso está bueno.'],
    guardaparque: ['Lo anoté en el registro: un renoval plantado. Pocos lo hacen.'],
    abuela: ['Plantaste un árbol, me contaron. Dicen que los duendes se ponen contentos con eso.'],
    ramon: ['Así me gusta: el que saca, devuelve.'],
  },
  'aporte-obra': {
    _dueno: ['Vi lo que trajiste para {lugar}. Sin eso, mi local era un dibujo en un papel. Gracias.', 'Gracias por lo de {lugar}. Cada tabla que traés es una mañana menos de espera.'],
    padre: ['Gracias por el material de {lugar}. Con eso los muchachos tenemos para toda la semana.'],
    jefe: ['Los pasajeros se asoman a mirar cómo sube {lugar}. Con tu material, el pueblo ya se ve desde la vía.'],
    nelida: ['Todo el mundo habla de lo que llevaste para {lugar}. Ya sos vecino de acá, aunque duermas lejos.'],
    abuela: ['Así se hacían los pueblos antes: cada uno traía lo que tenía. Gracias por lo de {lugar}.'],
    carpintero: ['Buena madera la que trajiste para {lugar}. Se nota que la elegiste.'],
    herrero: ['Con lo que trajiste para {lugar}, esta semana clavamos el techo.'],
  },
  capitulo: {
    maestra: ['Me enteré de lo tuyo. Eso hay que anotarlo con letra prolija: «{capitulo}».', 'Me enteré de lo tuyo. Eso hay que anotarlo con letra prolija.'],
    abuela: ['Ya se cuenta en la aldea lo de «{capitulo}». Así empiezan las leyendas, ¿sabías?', 'Ya se cuenta en la aldea lo que hiciste. Así empiezan las leyendas.'],
    ramon: ['Me llegó lo de «{capitulo}». Vas aprendiendo el valle.', 'Me llegó lo tuyo. Vas aprendiendo el valle.'],
    ercilia: ['En el almacén ya se comenta: «{capitulo}». ¡Qué cosa!', 'En el almacén ya se comenta lo tuyo. ¡Qué cosa!'],
    nena: ['¡Lo anoté en mi cuaderno! «{capitulo}». Con dibujo y todo.', '¡Lo anoté en mi cuaderno, con dibujo y todo!'],
  },
  poncho: {
    tejedora: ['Ese poncho nuevo te queda bien. Dejame ver la trama… Está parejo. Me gusta.'],
    ramon: ['Poncho nuevo, ¿eh? Ahora sí parecés de acá.'],
    abuela: ['Con ese poncho no te agarra ni el viento del lago.'],
    musico: ['Con ese poncho podés subir al escenario el sábado. Ya tenés la pinta.'],
    madre: ['¡Qué lindo poncho! Lucía va a querer uno igual.'],
  },
  'durmio-afuera': {
    enfermera: ['¿Dormiste afuera? Contame cómo amaneciste. Y la próxima, manta y medias de lana.'],
    ramon: ['Dormir afuera es lo que hacíamos en la veranada. Se aprende a escuchar el campo.'],
    ema: ['Si dormís afuera, apagá bien el fuego antes de cerrar los ojos. Con agua, no con tierra.'],
    nene: ['¡Dormiste en carpa! Yo también quiero. ¿Viste algún duende?'],
    guardaparque: ['Me dijeron que dormiste afuera. ¿Escuchaste al concón? De noche es el dueño del bosque.'],
  },
  cosecha: {
    madre: ['Me dijeron que levantaste la cosecha. ¿Tenés papas? Hago unas tortillas que no te imaginás.'],
    padre: ['Cosecha propia, eso es vivir bien.'],
    apicultor: ['Una huerta florecida le hace bien a las abejas. Gracias por eso, aunque no lo sepas.'],
    abuela: ['Cosechaste, me contaron. La tierra de acá es mezquina, pero al que la trabaja le da.'],
  },
  horneada: {
    panadera: ['¿Ya horneás en tu horno de barro? A ver si me vas a dejar sin trabajo, eh.'],
    galesa: ['Me dijeron que tu horno ya anda. La próxima, traeme una muestra, que soy curiosa.'],
    nene: ['¿Hiciste pan? ¿En un horno de verdad? ¿Me enseñás?'],
  },
  miel: {
    apicultor: ['Así que sacaste miel de tu colmena. ¿Te picaron? Eso es que las abejas te conocen.'],
    nena: ['¿Es verdad que tenés abejas? ¿No te dan miedo?'],
    enfermera: ['Miel propia, qué lujo. Guardá un frasco para los resfríos del invierno.'],
  },
  esquila: {
    tejedora: ['Me enteré de que esquilaste. Si tenés vellones lindos, mostrámelos antes de hacer cualquier cosa.'],
    ramon: ['Esquilar no es fácil. La primera oveja que esquilé me dejó un ojo morado.'],
  },
  tren: {
    jefe: ['Te vi bajar del tren. ¿Viajaste cómodo? El coche dos tiene la mejor salamandra.'],
    guarda: ['Gracias por viajar con nosotros. Se te veía contento en la ventanilla.'],
    nene: ['¿Viajaste en la trochita? ¿Te dejaron tocar el silbato?'],
    telegrafista: ['Te anoté en la planilla de pasajeros. Es costumbre, no te asustes.'],
  },
  'obra-propia': {
    carpintero: ['Me dijeron que levantaste {obra}. Cuando quieras te paso a mirar las uniones.', 'Me dijeron que levantaste algo nuevo. Cuando quieras te paso a mirar las uniones.'],
    padre: ['Así que {obra} ya está. Una obra propia se disfruta el doble.', 'Obra terminada, ¡bien ahí! Lo propio se disfruta el doble.'],
    herrero: ['Me contaron de {obra}. Si te faltan herrajes, ya sabés dónde estoy.', 'Me contaron que terminaste una obra. Si te faltan herrajes, ya sabés dónde estoy.'],
  },
  'foto-fauna': {
    guardaparque: ['Me llegó tu foto de {especie}. Va derecho al registro de la seccional.', 'Me llegó tu foto. Va derecho al registro de la seccional.'],
    ema: ['¡Qué foto la de {especie}! Esa la pegaría en la puerta de la guardería.', '¡Qué foto! Esa la pegaría en la puerta de la guardería.'],
    nena: ['¿Me mostrás la foto de {especie}? ¡Quiero dibujarla!', '¿Me mostrás tu foto? ¡Quiero dibujarla!'],
  },
  regalo: {
    _recibe: ['Todavía me acuerdo de {lacosa} que me trajiste. Gracias otra vez.', 'Gracias de nuevo por {lacosa}. Me alegró el día.', '{Lacosa} que me regalaste ya tiene su lugar en casa.'],
    _chisme: ['Me contó {quien} que le llevaste {cosa}. Le alegraste la semana.', 'Ya sé que le regalaste {cosa} a {quien}. Acá todo se sabe, eh.'],
  },
  ayuda: {
    _recibe: ['Gracias otra vez por la mano de ayer. Hoy anduve más liviano.', 'Lo de ayer me salvó el día. Gracias.'],
    _chisme: ['Me dijeron que le diste una mano a {quien}. Así da gusto.', 'Ya me enteré de que ayudaste a {quien}. Buena gente, vos.'],
  },
  invitacion: {
    _recibe: ['Qué lindo el {que} de ayer. La próxima invito yo.', 'Me quedé pensando en la charla de ayer, con el {que}. Gracias.'],
    _chisme: ['Me contó {quien} que tomaron {que} juntos. ¿Y a mí cuándo me invitás?'],
  },
};
// Los que cuentan lo que pasa (se enteran de los regalos, las ayudas y las invitaciones a otros).
export const CHISMOSOS = ['abuela', 'nelida', 'ercilia', 'madre', 'telegrafista'];

// ---------------------------------------------------------------- las frases de todos
export const FRASES = {
  yaHoy: [
    'Ya me diste algo hoy. Guardalo, que mañana es otro día.',
    'Hoy ya me alegraste el día una vez. No me malacostumbres.',
    'Con lo de hoy alcanza y sobra. Mañana, si querés.',
    'Dos regalos en un día es demasiado. Me vas a hacer sentir en deuda.',
  ],
  neutro: [
    'Gracias. No me lo esperaba, la verdad.',
    'Qué amable. Le voy a encontrar la vuelta.',
    'Mirá vos. Gracias por acordarte de mí.',
    'Te lo agradezco. Un gesto así vale más que lo que trae.',
  ],
  noTenes: 'No tenés {cosa} encima.',
  noSe: 'Eso no se puede regalar.',
  noche: [
    'A esta hora ya no, que mañana madrugo. Otro día, con luz.',
    'Es tarde ya. La pava se enfría y yo también. Mañana, si querés.',
    'De noche no salgo, que el camino engaña. Invitame mañana.',
  ],
  yaTomo: [
    'Ya tomamos hoy, ¿te acordás? Mañana repetimos.',
    'Por hoy ya estoy servido. Mañana, sin falta.',
    'Dos veces en un día no, que después no duermo.',
  ],
  teCerrado: 'La casa de té está cerrada a esta hora. Ceinwen abre la galería a las tres de la tarde.',
  teAnfitriona: 'Es mi casa de té, cariad: ahí la que invita soy yo. Sentate cuando quieras, que te sirvo.',
  abreMate: [
    'Qué rico está este mate. Bien cebado, sin quemar la yerba.',
    'Así me gusta el mate: amargo y con charla.',
    'Este mate tiene gusto a casa.',
  ],
  abreTe: [
    'El té de Ceinwen no tiene comparación. Y la torta negra, ni hablar.',
    'Qué lindo es sentarse en la galería con una taza caliente.',
    'El té se toma despacio, decía mi abuela. Hagámosle caso.',
  ],
  historiaAmigo: [
    'Eso es largo de contar. Otro día, cuando nos conozcamos un poco más.',
    'Lo que sigue me cuesta contarlo. Dame un poco de tiempo.',
  ],
  historiaCompadre: [
    'Lo que falta no se lo cuento a cualquiera. Todavía no, pero ya va a llegar.',
    'Hay una parte que sólo saben los de confianza. Algún día te la cuento.',
  ],
  historiaFin: [
    'Ya te conté todo lo mío. Ahora te toca a vos, ¿no?',
    'Eso es todo lo que hay para contar. Lo demás lo estamos viviendo.',
  ],
  sinNovedades: [
    'Por acá, todo tranquilo. Lo más nuevo es el viento, y ese siempre vuelve.',
    'Nada nuevo, por suerte. Cuando no pasa nada es que todo anda bien.',
    'Si me entero de algo, sos el primero en saberlo.',
  ],
  // las novedades del pueblo
  obra: [
    'Están levantando {lugar}: van {hechas} de {total} etapas. Si tenés material, se agradece.',
    'La obra de {lugar} va {hechas} de {total}. Con un empujón más, sale.',
  ],
  obraEmpieza: [
    'Ya marcaron el lote de {lugar}. Para los cimientos faltan piedras y troncos.',
    'Lo de {lugar} recién empieza: el lote marcado y nada más. Si tenés piedras, es el momento.',
  ],
  llego: [
    'Bajó del tren {quien}, {oficio}. Está esperando en el andén: andá a saludar.',
    'Hay gente nueva en la estación: {quien}, {oficio}. Dicen que viene a quedarse.',
  ],
  abrio: [
    '¿Viste que abrió {lugar}? Ya tiene el cartelito pintado y todo.',
    'Ya abrió sus puertas {lugar}. Un local más y esto es un pueblo hecho y derecho.',
  ],
  trenHora: 'El próximo tren pasa a eso de las {hora}.',
  tren: [
    'El tren de la tarde viene cargado: harina, kerosene y cartas.',
    'Dicen que el tren de esta semana trae un cajón de libros para la biblioteca.',
    'La trochita pasó con un vagón lleno de lana para la feria. Olía a oveja hasta la plaza.',
  ],
  pronostico: 'Dicen {pronostico}.',
  faunaGenerica: 'Hace poco vi {unbicho} por acá cerca.',
  pista: 'Para tu cuaderno: {pista}',
  // cómo andan: lo que vienen haciendo
  hizo: {
    te: 'Vengo de tomar un té, que con eso se arregla medio día.',
    plaza: 'Estuve un rato en la plaza, mirando pasar la gente.',
    visitar: 'Recién vengo de visitar a {amigo}. Me tuvo una hora con el mate.',
    compras: 'Fui al almacén por yerba y volví con la bolsa llena de novedades.',
    lena: 'Estuve partiendo leña. Para el invierno nunca alcanza.',
    regar: 'Regué las plantas de la entrada, que con este sol se secan.',
    palear: 'Estuve paleando la vereda, que la nieve no se va sola.',
    paseo: 'Me fui caminando hasta la estación. Desde el andén la cordillera se ve entera.',
    leer: 'Estuve en la biblioteca con un libro de viajes. Uno se va lejos sin moverse.',
    jugar: '¡Estuvimos jugando en la plaza! Gané yo. Bueno, casi.',
    galeria: 'Me quedé en la galería mirando llover. Hay pocas cosas más lindas.',
    descansar: 'Me tiré un rato. A cierta edad, la siesta no se negocia.',
  },
  clima: {
    sol: ['Qué día, ¿no? Así da gusto.', 'Con este sol hasta el lago se pone contento.'],
    nublado: ['Gris, pero tranquilo. Ni frío ni calor.', 'Está pesado el cielo. Algo se viene.'],
    viento: ['Este viento te despeina hasta las ideas.', 'Sopla como para volar las chapas. Agarrate el sombrero.'],
    lluvia: ['Con esta lluvia, lo mejor es estar bajo techo.', 'Llueve parejo. Bueno para la huerta, malo para los huesos.'],
    nieve: ['La nieve está linda para mirar, no tanto para palear.', 'Nieva despacito. El pueblo se pone callado.'],
  },
};
